### ISSUE TITLE
Unable to update nodes (in palette), all fail (10.1.0)

### ISSUE THREAD

**Issue by spudje** [hassio-addons/addon-node-red#1183]
# Problem/Motivation

Trying to update a node from the palette results in an error. Everytime, for all nodes with updates available.

## Expected behavior

Nodes update successfully, like in previous versions.

## Actual behavior

Nodes update process fails with error message
![image](https://user-images.githubusercontent.com/53037698/142380138-b740b21e-0f5b-4440-860f-1ece3b0fcb6f.png)

Similar bug was reported for v10.0.1 but just ignored by developers https://github.com/hassio-addons/addon-node-red/issues/1131
Although I myself didn't have the issue with previous Node-RED version.

## Steps to reproduce

- Open Node RED
- Go to "Manage Palette"
- Look for a Node that has an update available
- Press the update button and confirm with pressing the update button in the popup
- Then after some seconds the error message pop-up appears

## Proposed changes

Fix the update process.

Some example logs:

-----------------------------------------------------------
2021-11-18T08:36:04.033Z Install : node-red-contrib-modbus 5.15.0

2021-11-18T08:35:59.813Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-modbus@5.15.0
2021-11-18T08:36:13.932Z [err] npm
2021-11-18T08:36:13.933Z [err]  ERR! code 1
2021-11-18T08:36:13.933Z [err] npm ERR! path /config/node-red/node_modules/@serialport/bindings
2021-11-18T08:36:13.940Z [err] npm ERR! command failed
2021-11-18T08:36:13.941Z [err] npm ERR! command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2021-11-18T08:36:13.941Z [err] npm ERR! prebuild-install WARN install No prebuilt binaries found (target=14.18.1 runtime=node arch=arm64 libc=musl platform=linux)
2021-11-18T08:36:13.941Z [err] npm ERR! gyp info it worked if it ends with ok
2021-11-18T08:36:13.941Z [err] npm ERR! gyp info using node-gyp@7.1.2
2021-11-18T08:36:13.941Z [err] npm ERR! gyp info using node@14.18.1 | linux | arm64
2021-11-18T08:36:13.941Z [err] npm ERR! gyp info find Python using Python version 3.9.5 found at "/usr/bin/python3"
2021-11-18T08:36:13.941Z [err] npm ERR! gyp info spawn /usr/bin/python3
2021-11-18T08:36:13.941Z [err] npm ERR! gyp info spawn args [
2021-11-18T08:36:13.941Z [err] npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   'binding.gyp',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '-f',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   'make',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '-I',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '/config/node-red/node_modules/@serialport/bindings/build/config.gypi',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '-I',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '-I',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '/root/.cache/node-gyp/14.18.1/include/node/common.gypi',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '-Dvisibility=default',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.18.1',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.18.1/<(target_arch)/node.lib',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '-Dmodule_root_dir=/config/node-red/node_modules/@serialport/bindings',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '-Dnode_engine=v8',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '--depth=.',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '--no-parallel',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '--generator-output',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   'build',
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args   '-Goutput_dir=.'
2021-11-18T08:36:13.942Z [err] npm ERR! gyp info spawn args ]
2021-11-18T08:36:13.942Z [err] npm ERR! gyp ERR! build error 
2021-11-18T08:36:13.942Z [err] npm ERR! gyp ERR! stack Error: not found: make
2021-11-18T08:36:13.942Z [err] npm ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
2021-11-18T08:36:13.942Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
2021-11-18T08:36:13.942Z [err] npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2021-11-18T08:36:13.942Z [err] npm
2021-11-18T08:36:13.943Z [err]  ERR! gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
2021-11-18T08:36:13.943Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
2021-11-18T08:36:13.943Z [err] npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2021-11-18T08:36:13.943Z [err] npm ERR! gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
2021-11-18T08:36:13.943Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
2021-11-18T08:36:13.943Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2021-11-18T08:36:13.943Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2021-11-18T08:36:13.943Z [err] npm ERR! gyp ERR! System Linux 5.10.75
2021-11-18T08:36:13.943Z [err] npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-11-18T08:36:13.943Z [err] npm ERR! gyp ERR! cwd /config/node-red/node_modules/@serialport/bindings
2021-11-18T08:36:13.943Z [err] npm ERR! gyp ERR! node -v v14.18.1
2021-11-18T08:36:13.943Z [err] npm ERR! gyp ERR! node-gyp -v v7.1.2
2021-11-18T08:36:13.943Z [err] npm ERR! gyp ERR! not ok
2021-11-18T08:36:13.965Z [err] 
2021-11-18T08:36:13.965Z [err] npm 
2021-11-18T08:36:13.966Z [err] ERR! A complete log of this run can be found in:
2021-11-18T08:36:13.966Z [err] npm ERR!     /root/.npm/_logs/2021-11-18T08_36_13_947Z-debug.log
2021-11-18T08:36:13.985Z rc=1

-----------------------------------------------------------
2021-11-18T08:39:52.872Z Install : node-red-node-serialport 0.15.0

2021-11-18T08:39:48.655Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-node-serialport@0.15.0
2021-11-18T08:39:55.132Z [err] npm
2021-11-18T08:39:55.133Z [err]  ERR! code 1
2021-11-18T08:39:55.133Z [err] npm ERR! 
2021-11-18T08:39:55.133Z [err] path /config/node-red/node_modules/@serialport/bindings
2021-11-18T08:39:55.142Z [err] npm ERR!
2021-11-18T08:39:55.143Z [err]  command failed
2021-11-18T08:39:55.143Z [err] npm ERR! command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2021-11-18T08:39:55.143Z [err] npm 
2021-11-18T08:39:55.143Z [err] ERR! prebuild-install WARN install No prebuilt binaries found (target=14.18.1 runtime=node arch=arm64 libc=musl platform=linux)
2021-11-18T08:39:55.143Z [err] npm ERR! gyp info it worked if it ends with ok
2021-11-18T08:39:55.143Z [err] npm ERR! gyp info using node-gyp@7.1.2
2021-11-18T08:39:55.143Z [err] npm 
2021-11-18T08:39:55.143Z [err] ERR! gyp info using node@14.18.1 | linux | arm64
2021-11-18T08:39:55.143Z [err] npm ERR! gyp info find Python using Python version 3.9.5 found at "/usr/bin/python3"
2021-11-18T08:39:55.143Z [err] npm ERR! gyp info spawn /usr/bin/python3
2021-11-18T08:39:55.143Z [err] npm ERR! gyp info spawn args [
2021-11-18T08:39:55.143Z [err] npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2021-11-18T08:39:55.143Z [err] npm 
2021-11-18T08:39:55.143Z [err] ERR! gyp info spawn args   'binding.gyp',
2021-11-18T08:39:55.143Z [err] npm ERR! gyp info spawn args   '-f',
2021-11-18T08:39:55.143Z [err] npm 
2021-11-18T08:39:55.143Z [err] ERR! gyp info spawn args   'make',
2021-11-18T08:39:55.143Z [err] npm ERR! gyp info spawn args   '-I',
2021-11-18T08:39:55.143Z [err] npm ERR!
2021-11-18T08:39:55.143Z [err]  gyp info spawn args   '/config/node-red/node_modules/@serialport/bindings/build/config.gypi',
2021-11-18T08:39:55.143Z [err] npm ERR! gyp info spawn args   '-I',
2021-11-18T08:39:55.143Z [err] npm ERR!
2021-11-18T08:39:55.144Z [err]  gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2021-11-18T08:39:55.144Z [err] npm ERR! gyp info spawn args   '-I',
2021-11-18T08:39:55.144Z [err] npm 
2021-11-18T08:39:55.144Z [err] ERR! gyp info spawn args   '/root/.cache/node-gyp/14.18.1/include/node/common.gypi',
2021-11-18T08:39:55.144Z [err] npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
2021-11-18T08:39:55.144Z [err] npm 
2021-11-18T08:39:55.144Z [err] ERR! gyp info spawn args   '-Dvisibility=default',
2021-11-18T08:39:55.144Z [err] npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.18.1',
2021-11-18T08:39:55.144Z [err] npm 
2021-11-18T08:39:55.144Z [err] ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
2021-11-18T08:39:55.144Z [err] npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.18.1/<(target_arch)/node.lib',
2021-11-18T08:39:55.144Z [err] npm
2021-11-18T08:39:55.144Z [err]  ERR! gyp info spawn args   '-Dmodule_root_dir=/config/node-red/node_modules/@serialport/bindings',
2021-11-18T08:39:55.144Z [err] npm ERR! gyp info spawn args   '-Dnode_engine=v8',
2021-11-18T08:39:55.144Z [err] npm ERR!
2021-11-18T08:39:55.146Z [err]  gyp info spawn args   '--depth=.',
2021-11-18T08:39:55.146Z [err] npm ERR! gyp info spawn args   '--no-parallel',
2021-11-18T08:39:55.146Z [err] npm ERR! gyp info spawn args   '--generator-output',
2021-11-18T08:39:55.146Z [err] npm ERR! gyp info spawn args   'build',
2021-11-18T08:39:55.146Z [err] npm ERR! gyp info spawn args   '-Goutput_dir=.'
2021-11-18T08:39:55.146Z [err] npm ERR! gyp info spawn args ]
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! build error 
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! stack Error: not found: make
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! System Linux 5.10.75
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! cwd /config/node-red/node_modules/@serialport/bindings
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! node -v v14.18.1
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! node-gyp -v v7.1.2
2021-11-18T08:39:55.146Z [err] npm ERR! gyp ERR! not ok
2021-11-18T08:39:55.166Z [err] 
2021-11-18T08:39:55.166Z [err] npm ERR! A complete log of this run can be found in:
2021-11-18T08:39:55.166Z [err] npm ERR!     /root/.npm/_logs/2021-11-18T08_39_55_150Z-debug.log
2021-11-18T08:39:55.184Z rc=1

**Comment by sanderlv** [comment]
I have the same. Not all nodes fail, but modbus, gpio and serialport do.

**Comment by frenck** [comment]
modbus (and so is serial/gpio) is a built-in node of the add-on, updates will be shipped with the add-on.

If you like to update and built them manually, that is possible, but you'll have to install the build/compile environment yourself using the `system_packages` option of the add-on.

This is not a bug.
