### ISSUE TITLE
Fail on start

### ISSUE THREAD

**Issue by rpeders** [hassio-addons/addon-node-red#120]
# Problem/Motivation
Nodered wont start
> (Why the issue was filed)
this is what i get in the log:

26 Jan 21:42:26 - [info] Started flows
26 Jan 21:42:28 - [warn] [api-call-service:admin] Call-Service attempted without connection to server.
26 Jan 21:42:28 - [warn] [api-call-service:dusk] Call-Service attempted without connection to server.
26 Jan 21:42:28 - [red] Uncaught Exception:
26 Jan 21:42:28 - TypeError [ERR_INVALID_URL]: Invalid URL: ws/api/websocket
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at WebSocket.initAsClient (/opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/websocket.js:470:27)
    at new WebSocket (/opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/websocket.js:62:20)
    at connect (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/ha-websocket.js:243:28)
    at Timeout.setTimeout [as _onTimeout] (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/ha-websocket.js:322:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio-addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hassio-addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-26T21_42_29_061Z-debug.log
> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
26 Jan 21:42:42 - [info] 
Welcome to Node-RED
===================
26 Jan 21:42:42 - [info] Node-RED version: v0.19.5

Any idea how to fix this? i would be grateful since i had most my automations and stuff in nodered.
Rune Pedersen (skjeggpt)
I have two pi's running hassio with my zwave stuff on one and nodered on another... if that factors in

**Comment by rpeders** [comment]
Was able to fix this by editing the config.json and setting websocket to false, start nodred and rmove a node. then i set it to true again and restarted
