### ISSUE TITLE
Not loading RPi.GPIO pallete

### ISSUE THREAD

**Issue by hellresistor** [hassio-addons/addon-node-red#1209]
# Problem/Motivation

Addon Log Reports Error on loading RPi.GPIO pallete.
I am in Raspberry pi 4 8GB in supervised HA using Debian 11 aarch64

## Expected behavior

RPi.GPIO be loaded successfull after NodeRed Addon Start.

## Actual behavior

 ```
[10:45:42] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
12 Dec 10:45:45 - [info] 
Welcome to Node-RED
===================
12 Dec 10:45:45 - [info] Node-RED version: v2.1.4
12 Dec 10:45:45 - [info] Node.js  version: v16.13.1
12 Dec 10:45:45 - [info] Linux 5.10.0-9-arm64 arm64 LE
12 Dec 10:45:47 - [info] Loading palette nodes
12 Dec 10:45:54 - [info] Dashboard version 3.1.2 started at /endpoint/ui
Traceback (most recent call last):
  File "/opt/node_modules/node-red-node-pi-gpio/testgpio.py", line 3, in <module>
    import RPi.GPIO as GPIO
  File "/usr/lib/python3.9/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
12 Dec 10:45:56 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
12 Dec 10:45:56 - [info] Settings file  : /etc/node-red/config.js
12 Dec 10:45:56 - [info] Context store  : 'default' [module=memory]
12 Dec 10:45:56 - [info] User directory : /config/node-red/
12 Dec 10:45:56 - [warn] Projects disabled : editorTheme.projects.enabled=false
12 Dec 10:45:56 - [info] Flows file     : /config/node-red/flows.json
12 Dec 10:45:56 - [info] Server now running at http://127.0.0.1:46836/
12 Dec 10:45:56 - [info] Starting flows
12 Dec 10:45:56 - [info] Started flows
[10:45:56] INFO: Starting NGinx...
```

## Steps to reproduce

> Start NodeRed Addon

**Comment by dethpickle** [comment]
I'm seeing something similar after upgrading to the Node-Red integration 10.2.0 and HA to 2021.12.0.  I honestly can't recall if it was working in the in-between couple of minutes between the two upgrades.

I'm running it as a VM:
## System Health

version | core-2021.12.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.83
arch | x86_64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.18.0
Stage | running
Available Repositories | 910
Installed Repositories | 27

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 7, 2022, 4:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-west-2-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.1
docker_version | 20.10.9
disk_total | 58.4 GB
disk_used | 27.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Mosquitto broker (6.0.1), SSH & Web Terminal (9.1.1), Node-RED (10.2.0), Studio Code Server (3.7.0), Home Assistant Google Drive Backup (0.105.2), Let's Encrypt (4.12.0)

</details>

<details><summary>Universal Devices ISY994</summary>

host_reachable | ok
-- | --
device_connected | true
last_heartbeat | December 12, 2021, 7:19 PM
websocket_status | connected

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 15
views | 17
mode | storage

</details>

Node-Red just gives the following when you go to it's page:
```
502 Bad Gateway

nginx
```

Node-Red Log:
```
12 Dec 19:17:37 - [error] [cron:December Cycle] Invalid Expression
12 Dec 19:17:37 - [info] Started flows
12 Dec 19:17:37 - [info] [mqtt-broker:Local MQTT] Connected to broker: nodered@http://<<redacted/
12 Dec 19:17:37 - [warn] [sun events:ae9be1e3.2e7ab] calculating sunevents for <<redacted>>
12 Dec 19:17:37 - [red] Uncaught Exception:
12 Dec 19:17:37 - [error] HTTPError: Response code 502 (Bad Gateway)
    at EventEmitter.<anonymous> (/config/node-red/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[19:17:37] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
12 Dec 19:17:38 - [info] 
Welcome to Node-RED
===================
12 Dec 19:17:38 - [info] Node-RED version: v2.1.4
12 Dec 19:17:38 - [info] Node.js  version: v16.13.1
12 Dec 19:17:38 - [info] Linux 5.10.83 x64 LE
12 Dec 19:17:39 - [info] Loading palette nodes
12 Dec 19:17:41 - [info] Dashboard version 3.1.2 started at /endpoint/ui
Traceback (most recent call last):
  File "/opt/node_modules/node-red-node-pi-gpio/testgpio.py", line 3, in <module>
    import RPi.GPIO as GPIO
  File "/usr/lib/python3.9/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
12 Dec 19:17:41 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
12 Dec 19:17:41 - [info] Settings file  : /etc/node-red/config.js
12 Dec 19:17:41 - [info] Context store  : 'default' [module=memory]
12 Dec 19:17:41 - [info] User directory : /config/node-red/
12 Dec 19:17:41 - [warn] Projects disabled : editorTheme.projects.enabled=false
12 Dec 19:17:41 - [info] Flows file     : /config/node-red/flows.json
12 Dec 19:17:41 - [info] Server now running at http://127.0.0.1:46836/
12 Dec 19:17:41 - [info] Starting flows
[2021-12-12 19:17:42] info: US Controller created
[2021-12-12 19:17:42] info: Bluelinky is loging in automatically, to disable use autoLogin: false
12 Dec 19:17:42 - [error] [cron:December Cycle] Invalid Expression
12 Dec 19:17:42 - [info] Started flows
12 Dec 19:17:42 - [info] [mqtt-broker:Local MQTT] Connected to broker: nodered@http://<<redacted/
12 Dec 19:17:42 - [warn] [sun events:ae9be1e3.2e7ab] calculating sunevents for <<redacted>>
12 Dec 19:17:42 - [red] Uncaught Exception:
12 Dec 19:17:42 - [error] HTTPError: Response code 502 (Bad Gateway)
    at EventEmitter.<anonymous> (/config/node-red/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[19:17:42] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
12 Dec 19:17:43 - [info] 
Welcome to Node-RED
===================
12 Dec 19:17:43 - [info] Node-RED version: v2.1.4
12 Dec 19:17:43 - [info] Node.js  version: v16.13.1
12 Dec 19:17:43 - [info] Linux 5.10.83 x64 LE
12 Dec 19:17:44 - [info] Loading palette nodes
12 Dec 19:17:46 - [info] Dashboard version 3.1.2 started at /endpoint/ui
Traceback (most recent call last):
  File "/opt/node_modules/node-red-node-pi-gpio/testgpio.py", line 3, in <module>
    import RPi.GPIO as GPIO
  File "/usr/lib/python3.9/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
12 Dec 19:17:47 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
12 Dec 19:17:47 - [info] Settings file  : /etc/node-red/config.js
12 Dec 19:17:47 - [info] Context store  : 'default' [module=memory]
12 Dec 19:17:47 - [info] User directory : /config/node-red/
12 Dec 19:17:47 - [warn] Projects disabled : editorTheme.projects.enabled=false
12 Dec 19:17:47 - [info] Flows file     : /config/node-red/flows.json
12 Dec 19:17:47 - [info] Server now running at http://127.0.0.1:46836/
12 Dec 19:17:47 - [info] Starting flows
[2021-12-12 19:17:47] info: US Controller created
[2021-12-12 19:17:47] info: Bluelinky is loging in automatically, to disable use autoLogin: false
12 Dec 19:17:47 - [error] [cron:December Cycle] Invalid Expression
12 Dec 19:17:47 - [info] Started flows
12 Dec 19:17:47 - [info] [mqtt-broker:Local MQTT] Connected to broker: nodered@http://<<redacted/
12 Dec 19:17:47 - [warn] [sun events:ae9be1e3.2e7ab] calculating sunevents for <<redacted>>
12 Dec 19:17:47 - [red] Uncaught Exception:
12 Dec 19:17:47 - [error] HTTPError: Response code 502 (Bad Gateway)
    at EventEmitter.<anonymous> (/config/node-red/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[19:17:47] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
12 Dec 19:17:49 - [info] 
Welcome to Node-RED
===================
12 Dec 19:17:49 - [info] Node-RED version: v2.1.4
12 Dec 19:17:49 - [info] Node.js  version: v16.13.1
12 Dec 19:17:49 - [info] Linux 5.10.83 x64 LE
12 Dec 19:17:49 - [info] Loading palette nodes
```

**Comment by dethpickle** [comment]
Please disregard - I found the other issue: #1198 and used what folks were saying to figure out that my issue was the Bluelinky module.  I removed from packages.json as they described and my node-red is working again. 

@hellresistor, you might try looking in the rest of your log and seeing if you have something similar to chase down.

Cheers!

**Comment by hellresistor** [comment]
NodeRed Addon Full LOG

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 10.2.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.12.1
 Home Assistant Supervisor: 2021.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] customizations.sh: executing... 
[cont-init.d] customizations.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1162 (offset 631 lines).
up to date, audited 1 package in 2s
found 0 vulnerabilities
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[07:05:47] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
13 Dec 07:05:51 - [info] 
Welcome to Node-RED
===================
13 Dec 07:05:51 - [info] Node-RED version: v2.1.4
13 Dec 07:05:51 - [info] Node.js  version: v16.13.1
13 Dec 07:05:51 - [info] Linux 5.10.0-9-arm64 arm64 LE
13 Dec 07:05:52 - [info] Loading palette nodes
13 Dec 07:06:00 - [info] Dashboard version 3.1.2 started at /endpoint/ui
Traceback (most recent call last):
  File "/opt/node_modules/node-red-node-pi-gpio/testgpio.py", line 3, in <module>
    import RPi.GPIO as GPIO
  File "/usr/lib/python3.9/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
13 Dec 07:06:01 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
13 Dec 07:06:01 - [info] Settings file  : /etc/node-red/config.js
13 Dec 07:06:01 - [info] Context store  : 'default' [module=memory]
13 Dec 07:06:01 - [info] User directory : /config/node-red/
13 Dec 07:06:01 - [warn] Projects disabled : editorTheme.projects.enabled=false
13 Dec 07:06:01 - [info] Flows file     : /config/node-red/flows.json
13 Dec 07:06:01 - [info] Server now running at http://127.0.0.1:46836/
13 Dec 07:06:01 - [info] Starting flows
13 Dec 07:06:01 - [info] Started flows
[07:06:01] INFO: Starting NGinx...
13 Dec 07:06:06 - [info] [server:Home Assistant] Connecting to undefined
13 Dec 07:06:06 - [info] [server:Home Assistant] Connected to undefined
```

**Comment by hellresistor** [comment]
Keeps after NodeRed Addon v10.2.1 update
