### ISSUE TITLE
Bigtimer causes infinite restart loop

### ISSUE THREAD

**Issue by henriAbel** [hassio-addons/addon-node-red#1349]
# Problem/Motivation

By default bigtimer module is configured to output on startup. When bigtimer module is connected to the `device` entity it will try to send message to the home assistant server over the websocket. Issue happens at startup when bigtimer module fires output before connection to the home assistant server is made. 

```
[error] TypeError: Cannot read properties of undefined (reading 'sendMessagePromise')
at Websocket.send (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:405:28)
at DeviceAction.onInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/device/action-controller.js:26:34)
at DeviceAction.preOnInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:411:18)
at /opt/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
at Object.trigger (/opt/node_modules/@node-red/util/lib/hooks.js:166:13)
at deviceNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
at deviceNode.Node.emit (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
at deviceNode.Node.receive (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:485:10)
at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
at processImmediate (node:internal/timers:466:21)
```

This error causes whole container to restart and whole process starts again. I will also attach the full log file.
[node_red.txt](https://github.com/hassio-addons/addon-node-red/files/8749928/node_red.txt)

## Expected behavior

I would expect that this error is correctly handled, probably this issue is not limited to the startup procedure and can happen at any time when there is connection issue with the home assistant. 

## Actual behavior

Infinite container restarts

## Steps to reproduce

1. Add empty bigtimer node
2. Connect it to the 'device' entity
3. Press deploy
4. Refresh the page, you will see nginx gateway not reachable error

![image](https://user-images.githubusercontent.com/2768279/169708248-0426deaf-8d4d-4ec8-8d94-84697d97f8a0.png)

## Proposed changes

My current workaround is to use `call service` node instead of `device` node, which seems to handle this error. When `call service` node is used i can see following error in the UI: `No connection at: xx:xx`. I have not looked how this is implemented in the `call service` node but i guess same logic can be applied to the `device' node`

![image](https://user-images.githubusercontent.com/2768279/169708271-0e3f0aa2-c3f3-48fd-b12a-5eec5c33c9eb.png)

**Comment by sinclairpaul** [comment]
Your issue appears to be with the node-red-contrib-home-assistant-websocket palette.

Please log your issue there https://github.com/zachowj/node-red-contrib-home-assistant-websocket
