### ISSUE TITLE
Nodered restarts on its own

### ISSUE THREAD

**Issue by zoic21** [hassio-addons/addon-node-red#1350]
# Problem/Motivation

Nodered restarts on its own about one time by hour

## Expected behavior

Nodered not restart on its own 

## Actual behavior

Nodered restarts on its own. Here the log : 

```
23 May 17:03:18 - [info] [server:Home Assistant] Connecting to http://supervisor/core
23 May 17:03:18 - [info] [server:Home Assistant] Connected to http://supervisor/core
23 May 17:39:05 - [red] Uncaught Exception:
23 May 17:39:05 - [error] Error: Invalid context key
    at Object.value (/opt/node_modules/@node-red/runtime/lib/nodes/context/index.js:291:31)
    at EventsState.getContextValue (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:143:34)
    at EventsState.getComparatorResult (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:167:27)
    at EventsState.onHaEventsStateChanged (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/events-state/controller.js:71:32)
    at EventEmitter.emit (node:events:538:35)
    at Websocket.emitEvent (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:35:30)
    at Websocket.onClientEvents (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:257:22)
    at Object.callback (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:188:65)
    at WebSocket.Connection._handleMessage (/opt/node_modules/home-assistant-js-websocket/dist/haws.cjs:174:30)
    at WebSocket.onMessage (/opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/event-target.js:199:18)
[17:39:05] INFO: Starting Node-RED...
```

Nodered is install by home assistant on Home Assistant OS.

I try to reinstall it => sameissue. I also try to : 
- remove nodered
- restart home assistant VM
- delete nodered folder
- restart home assistant VM
- reinstall nodered
- reimport my flows
=> Same issue

Version of home assistant websocker node (last version) : 
![image](https://user-images.githubusercontent.com/1536036/169857908-108393cd-d316-4d38-9bcf-d02ca4e313cb.png)

Home assistant OS is up to date (8.1) and core-2022.5.5. I don't known if it happens after an update I just begin with homeassistant/nodered

## Steps to reproduce

I do not know

**Comment by frenck** [comment]
It means it crashes, caused by an uncaught exception in `node-red-contrib-home-assistant-websocket`.

Please report this issue with that project, so they can fix/guard for it. You can find it here: <https://github.com/zachowj/node-red-contrib-home-assistant-websocket>

../Frenck
