### ISSUE TITLE
Bad gateway

### ISSUE THREAD

**Issue by milandzuris** [hassio-addons/addon-node-red#1370]
version 12.0.2

core 6.0.3

node red addon log:

8 Jun 23:36:10 - [info] Started flows
8 Jun 23:36:10 - [error] [function:Notification] SyntaxError: Unexpected token '{' (body:line 7)
8 Jun 23:36:10 - [error] [function:Notification] SyntaxError: Unexpected token ']' (body:line 11)
8 Jun 23:36:11 - [info] [server:Dzuriš Home] Connecting to http://supervisor/core
8 Jun 23:36:12 - [error] [api-current-state:Boiler Schedule ON] Entity could not be found in cache for entity_id: input_boolean.boiler_schedule
8 Jun 23:36:12 - [info] [mqtt-broker:Dzuriš MQTT Server] Connected to broker: mqtt://192.168.0.2:1883
8 Jun 23:36:12 - [info] [mqtt-broker:Dzuriš Home MQTT] Connected to broker: mqtt://192.168.0.2:1883
8 Jun 23:36:16 - [error] [api-current-state:All Away] Entity could not be found in cache for entity_id: 
8 Jun 23:36:16 - [error] [api-current-state:Shed Light] Entity could not be found in cache for entity_id: switch.shed_light
8 Jun 23:36:16 - [red] Uncaught Exception:
8 Jun 23:36:16 - [error] TypeError: sendEvent.destination.node.receive is not a function
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
    at processImmediate (node:internal/timers:466:21)
[23:36:17] WARNING: Node-RED crashed, halting add-on
[23:36:17] INFO: Node-RED stoped, restarting...
s6-rc: info: service legacy-services: stopping
[23:36:17] INFO: Node-RED stoped, restarting...
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

TypeError: Cannot read properties of undefined (reading 'id')
    at /opt/node_modules/@node-red/runtime/lib/flows/Subflow.js:209:140
    at Array.map (<anonymous>)
    at /opt/node_modules/@node-red/runtime/lib/flows/Subflow.js:209:95
    at Array.map (<anonymous>)
    at Subflow.start (/opt/node_modules/@node-red/runtime/lib/flows/Subflow.js:209:62)
    at Flow.start (/opt/node_modules/@node-red/runtime/lib/flows/Flow.js:224:41)
    at start (/opt/node_modules/@node-red/runtime/lib/flows/index.js:371:33)
TypeError: Cannot read properties of undefined (reading 'id')
    at /opt/node_modules/@node-red/runtime/lib/flows/Subflow.js:209:140
    at Array.map (<anonymous>)
    at /opt/node_modules/@node-red/runtime/lib/flows/Subflow.js:209:95
    at Array.map (<anonymous>)
    at Subflow.start (/opt/node_modules/@node-red/runtime/lib/flows/Subflow.js:209:62)
    at Flow.start (/opt/node_modules/@node-red/runtime/lib/flows/Flow.js:224:41)
    at start (/opt/node_modules/@node-red/runtime/lib/flows/index.js:371:33)
8 Jun 23:37:57 - [error] [mqtt in:Master Bedroom Motion] topic not defined

**Comment by sinclairpaul** [comment]
One of the flows is crashing, which maybe to do with the removed nodes in the release notes.

You should be able to set the safe mode flag https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#option-safe_mode to start Node-Red and then identify the problematic flow

**Comment by milandzuris** [comment]
safe mode work thx, and how i find problem in flow? @sinclairpaul

**Comment by milandzuris** [comment]
working thx so much

**Comment by milandzuris** [comment]
again same problem, im turn on safe mode after 3-5min NR is down, it restarts itself.

TypeError: Cannot read properties of undefined (reading 'id')
    at /opt/node_modules/@node-red/runtime/lib/flows/Subflow.js:209:140
    at Array.map (<anonymous>)
    at /opt/node_modules/@node-red/runtime/lib/flows/Subflow.js:209:95
    at Array.map (<anonymous>)
    at Subflow.start (/opt/node_modules/@node-red/runtime/lib/flows/Subflow.js:209:62)
    at Flow.start (/opt/node_modules/@node-red/runtime/lib/flows/Flow.js:224:41)
    at start (/opt/node_modules/@node-red/runtime/lib/flows/index.js:371:33)

9 Jun 01:46:56 - [red] Uncaught Exception:
9 Jun 01:46:56 - [error] TypeError: sendEvent.destination.node.receive is not a function
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
    at processImmediate (node:internal/timers:466:21)
2022/06/09 01:46:56 [error] 371#371: *249 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "POST /flows HTTP/1.1", upstream: "http://127.0.0.1:46836/flows", host: "dzurishome:8123", referrer: "http://dzurishome:8123/api/hassio_ingress/1q6qC33btqwM8RsK1ZRfcJ8FCx7BjYUHbtbSiaKDZa8/"
[01:46:56] WARNING: Node-RED crashed, halting add-on
s6-rc: info: service legacy-services: stopping
[01:46:56] INFO: Node-RED stoped, restarting...
[01:46:56] INFO: Node-RED stoped, restarting...
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
