### ISSUE TITLE
package won't install or uninstall

### ISSUE THREAD

**Issue by defisit** [hassio-addons/addon-node-red#1417]
# Problem/Motivation

Attempting to update node-red-node-email 1.17.0, an error is thrown (see log).
Attempting to updatenode-red-contrib-modbus 5.23.1 an other error is thrown (see log).

This behaviour seems to have presented itself first from starting version 13.0.0 

## Expected behavior

The specific package is installed or uninstalled without error.

## Actual behavior

An error occurs and the it will not install

## Steps to reproduce

Under 'Manage Palette" go to Nodes and press the upgrade button for the specific package.

For the node-red-node-email package, it seems a directory name is incorrect. I have attempted to rename it according to recommendation in the error log (snippit below), however, renaming the provided directory to --> .node-red-node-email-9kimBKpy is not succesful.

ENOTEMPTY: directory not empty, rename '/config/node-red/node_modules/node-red-node-email' -> '/config/node-red/node_modules/.node-red-node-email-9kimBKpy'

For the node-red-contrib-modbus 5.23.1 package, other errors are displayed. Check the log.

## Proposed changes

-----------------------------------------------------------
2022-08-05T08:56:53.586Z Install : node-red-node-email 1.17.0

2022-08-05T08:56:53.632Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-node-email@1.17.0
2022-08-05T08:56:54.004Z [err] npm
2022-08-05T08:56:54.005Z [err]  
2022-08-05T08:56:54.005Z [err] WARN
2022-08-05T08:56:54.005Z [err]  
2022-08-05T08:56:54.005Z [err] config
2022-08-05T08:56:54.005Z [err]  production Use `--omit=dev` instead.
2022-08-05T08:56:55.183Z [err] npm
2022-08-05T08:56:55.184Z [err]  ERR! code ENOTEMPTY
2022-08-05T08:56:55.184Z [err] npm ERR! syscall rename
2022-08-05T08:56:55.184Z [err] npm ERR! path
2022-08-05T08:56:55.184Z [err]  /config/node-red/node_modules/node-red-node-email
2022-08-05T08:56:55.184Z [err] npm ERR! dest /config/node-red/node_modules/.node-red-node-email-9kimBKpy
2022-08-05T08:56:55.185Z [err] npm ERR!
2022-08-05T08:56:55.185Z [err]  errno -39
2022-08-05T08:56:55.186Z [err] npm ERR!
2022-08-05T08:56:55.186Z [err]  ENOTEMPTY: directory not empty, rename '/config/node-red/node_modules/node-red-node-email' -> '/config/node-red/node_modules/.node-red-node-email-9kimBKpy'
2022-08-05T08:56:55.189Z [err] 
2022-08-05T08:56:55.189Z [err] npm 
2022-08-05T08:56:55.189Z [err] ERR! A complete log of this run can be found in:
2022-08-05T08:56:55.189Z [err] npm ERR!     /root/.npm/_logs/2022-08-05T08_56_53_971Z-debug-0.log
2022-08-05T08:56:55.196Z rc=217

-----------------------------------------------------------
2022-08-05T08:58:01.927Z Install : node-red-contrib-modbus 5.23.1

2022-08-05T08:58:01.955Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-modbus@5.23.1
2022-08-05T08:58:02.333Z [err] npm
2022-08-05T08:58:02.333Z [err]  WARN config production Use `--omit=dev` instead.
2022-08-05T08:58:15.001Z [err] npm
2022-08-05T08:58:15.001Z [err]  ERR! code 1
2022-08-05T08:58:15.001Z [err] npm ERR! 
2022-08-05T08:58:15.001Z [err] path /config/node-red/node_modules/@serialport/bindings
2022-08-05T08:58:15.002Z [err] npm 
2022-08-05T08:58:15.002Z [err] ERR! command failed
2022-08-05T08:58:15.002Z [err] npm ERR! command
2022-08-05T08:58:15.002Z [err]  sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2022-08-05T08:58:15.002Z [err] npm ERR!
2022-08-05T08:58:15.003Z [err]  prebuild-install warn install No prebuilt binaries found (target=16.16.0 runtime=node arch=x64 libc=musl platform=linux)
2022-08-05T08:58:15.003Z [err] npm ERR! gyp info it worked if it ends with ok
2022-08-05T08:58:15.003Z [err] npm ERR! gyp info using node-gyp@9.0.0
2022-08-05T08:58:15.003Z [err] npm ERR!
2022-08-05T08:58:15.003Z [err]  gyp info using node@16.16.0 | linux | x64
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python 
2022-08-05T08:58:15.003Z [err] npm 
2022-08-05T08:58:15.003Z [err] ERR! gyp ERR! find Python checking Python explicitly set from command line or npm configuration
2022-08-05T08:58:15.003Z [err] npm ERR!
2022-08-05T08:58:15.003Z [err]  gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
2022-08-05T08:58:15.003Z [err] npm
2022-08-05T08:58:15.003Z [err]  ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python checking if "python3" can be used
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2022-08-05T08:58:15.003Z [err] npm 
2022-08-05T08:58:15.003Z [err] ERR! gyp ERR! find Python checking if "python" can be used
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python 
2022-08-05T08:58:15.003Z [err] npm ERR!
2022-08-05T08:58:15.003Z [err]  gyp ERR! find Python **********************************************************
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2022-08-05T08:58:15.003Z [err] npm ERR!
2022-08-05T08:58:15.003Z [err]  gyp ERR! find Python you can try one of the following options:
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python For more information consult the documentation at:
2022-08-05T08:58:15.003Z [err] npm
2022-08-05T08:58:15.003Z [err]  ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python **********************************************************
2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python 
2022-08-05T08:58:15.003Z [err] npm 
2022-08-05T08:58:15.004Z [err] ERR! gyp ERR! configure error 
2022-08-05T08:58:15.004Z [err] npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
2022-08-05T08:58:15.004Z [err] npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
2022-08-05T08:58:15.004Z [err] npm ERR!
2022-08-05T08:58:15.004Z [err]  gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
2022-08-05T08:58:15.004Z [err] npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
2022-08-05T08:58:15.004Z [err] npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
2022-08-05T08:58:15.004Z [err] npm ERR!
2022-08-05T08:58:15.004Z [err]  gyp ERR! stack     at exithandler (node:child_process:406:5)
2022-08-05T08:58:15.004Z [err] npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
2022-08-05T08:58:15.004Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
2022-08-05T08:58:15.004Z [err] npm ERR!
2022-08-05T08:58:15.004Z [err]  gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
2022-08-05T08:58:15.004Z [err] npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
2022-08-05T08:58:15.004Z [err] npm
2022-08-05T08:58:15.004Z [err]  ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-08-05T08:58:15.004Z [err] npm ERR!
2022-08-05T08:58:15.004Z [err]  gyp ERR! System Linux 5.15.55
2022-08-05T08:58:15.004Z [err] npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2022-08-05T08:58:15.004Z [err] npm 
2022-08-05T08:58:15.004Z [err] ERR! gyp ERR! cwd /config/node-red/node_modules/@serialport/bindings
2022-08-05T08:58:15.004Z [err] npm ERR!
2022-08-05T08:58:15.004Z [err]  gyp ERR! node -v v16.16.0
2022-08-05T08:58:15.004Z [err] npm ERR! gyp ERR! node-gyp -v v9.0.0
2022-08-05T08:58:15.004Z [err] npm 
2022-08-05T08:58:15.004Z [err] ERR! gyp ERR! not ok
2022-08-05T08:58:15.006Z [err] 
2022-08-05T08:58:15.006Z [err] npm 
2022-08-05T08:58:15.006Z [err] ERR! A complete log of this run can be found in:
2022-08-05T08:58:15.006Z [err] npm ERR!     /root/.npm/_logs/2022-08-05T08_58_02_297Z-debug-0.log
2022-08-05T08:58:15.015Z rc=1

![image](https://user-images.githubusercontent.com/61313374/183062709-02de921e-517c-4aee-b041-42210330aea6.png)

**Comment by frenck** [comment]
> Attempting to update node-red-node-email 1.17.0, an error is thrown (see log).
> Attempting to updatenode-red-contrib-modbus 5.23.1 an other error is thrown (see log).

Are built-in nodes and are updated by the add-on automatically 🤷 

Anyways, if you want to override that and install different nodes (or versions) yourself, that is fine, but you'll need to provide them the environment they need to install.

It is in your logs...

> 2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
> 2022-08-05T08:58:15.003Z [err] npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,

See the add-on documentation on how you can install additional packages if your set up requires that.

<https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#option-system_packages>

../Frenck

**Comment by defisit** [comment]
Thank you. I wasnt aware that built-in nodes are updated automatically and so manually pressing Update is not needed.
