### ISSUE TITLE
 Could not find any Python installation to use

### ISSUE THREAD

**Issue by Wolvverine** [hassio-addons/addon-node-red#1450]
When some nodes are install, example:
```
2022-09-27T19:42:46.174Z Install : node-red-contrib-modbus 5.23.2

2022-09-27T19:42:44.544Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-modbus@5.23.2
2022-09-27T19:42:47.287Z [err] npm
2022-09-27T19:42:47.288Z [err]  
2022-09-27T19:42:47.288Z [err] WARN config production Use `--omit=dev` instead.
2022-09-27T19:43:05.125Z [err] npm
2022-09-27T19:43:05.125Z [err]  ERR! code 1
2022-09-27T19:43:05.126Z [err] npm 
2022-09-27T19:43:05.127Z [err] ERR! path /config/node-red/node_modules/@serialport/bindings
2022-09-27T19:43:05.135Z [err] npm ERR!
2022-09-27T19:43:05.136Z [err]  command failed
2022-09-27T19:43:05.136Z [err] npm ERR! command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2022-09-27T19:43:05.136Z [err] npm ERR!
2022-09-27T19:43:05.137Z [err]  prebuild-install warn install No prebuilt binaries found (target=16.16.0 runtime=node arch=x64 libc=musl platform=linux)
2022-09-27T19:43:05.137Z [err] npm ERR! gyp info it worked if it ends with ok
2022-09-27T19:43:05.137Z [err] npm ERR!
2022-09-27T19:43:05.137Z [err]  gyp info using node-gyp@9.0.0
2022-09-27T19:43:05.137Z [err] npm ERR! gyp info using node@16.16.0 | linux | x64
2022-09-27T19:43:05.137Z [err] npm 
2022-09-27T19:43:05.137Z [err] ERR! gyp ERR! find Python 
2022-09-27T19:43:05.138Z [err] npm 
2022-09-27T19:43:05.138Z [err] ERR! gyp ERR! find Python checking Python explicitly set from command line or npm configuration
2022-09-27T19:43:05.138Z [err] npm
2022-09-27T19:43:05.138Z [err]  ERR! gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
2022-09-27T19:43:05.138Z [err] npm 
2022-09-27T19:43:05.138Z [err] ERR! gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
2022-09-27T19:43:05.138Z [err] npm 
2022-09-27T19:43:05.138Z [err] ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2022-09-27T19:43:05.138Z [err] npm 
2022-09-27T19:43:05.139Z [err] ERR! gyp ERR! find Python checking if "python3" can be used
2022-09-27T19:43:05.139Z [err] npm 
2022-09-27T19:43:05.139Z [err] ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2022-09-27T19:43:05.139Z [err] npm 
2022-09-27T19:43:05.139Z [err] ERR! gyp ERR! find Python checking if "python" can be used
2022-09-27T19:43:05.139Z [err] npm 
2022-09-27T19:43:05.139Z [err] ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2022-09-27T19:43:05.139Z [err] npm
2022-09-27T19:43:05.139Z [err]  ERR! gyp ERR! find Python 
2022-09-27T19:43:05.139Z [err] npm
2022-09-27T19:43:05.140Z [err]  ERR! gyp ERR! find Python **********************************************************
2022-09-27T19:43:05.140Z [err] npm
2022-09-27T19:43:05.140Z [err]  ERR! gyp ERR! find Python You need to install the latest version of Python.
2022-09-27T19:43:05.140Z [err] npm
2022-09-27T19:43:05.140Z [err]  ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2022-09-27T19:43:05.140Z [err] npm 
2022-09-27T19:43:05.140Z [err] ERR! gyp ERR! find Python you can try one of the following options:
2022-09-27T19:43:05.140Z [err] npm 
2022-09-27T19:43:05.140Z [err] ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2022-09-27T19:43:05.140Z [err] npm 
2022-09-27T19:43:05.141Z [err] ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2022-09-27T19:43:05.141Z [err] npm 
2022-09-27T19:43:05.141Z [err] ERR! gyp ERR! find Python - Set the environment variable PYTHON
2022-09-27T19:43:05.141Z [err] npm 
2022-09-27T19:43:05.141Z [err] ERR! gyp ERR! find Python - Set the npm configuration variable python:
2022-09-27T19:43:05.141Z [err] npm 
2022-09-27T19:43:05.141Z [err] ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2022-09-27T19:43:05.141Z [err] npm 
2022-09-27T19:43:05.141Z [err] ERR! gyp ERR! find Python For more information consult the documentation at:
2022-09-27T19:43:05.141Z [err] npm 
2022-09-27T19:43:05.142Z [err] ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2022-09-27T19:43:05.142Z [err] npm 
2022-09-27T19:43:05.142Z [err] ERR! gyp ERR! find Python **********************************************************
2022-09-27T19:43:05.142Z [err] npm 
2022-09-27T19:43:05.142Z [err] ERR! gyp ERR! find Python 
2022-09-27T19:43:05.142Z [err] npm ERR! gyp ERR! configure error 
2022-09-27T19:43:05.142Z [err] npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
2022-09-27T19:43:05.142Z [err] npm ERR!
2022-09-27T19:43:05.143Z [err]  gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
2022-09-27T19:43:05.143Z [err] npm ERR!
2022-09-27T19:43:05.143Z [err]  gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
2022-09-27T19:43:05.143Z [err] npm ERR!
2022-09-27T19:43:05.143Z [err]  gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
2022-09-27T19:43:05.143Z [err] npm ERR!
2022-09-27T19:43:05.143Z [err]  gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
2022-09-27T19:43:05.143Z [err] npm ERR!
2022-09-27T19:43:05.143Z [err]  gyp ERR! stack     at exithandler (node:child_process:406:5)
2022-09-27T19:43:05.143Z [err] npm ERR!
2022-09-27T19:43:05.144Z [err]  gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
2022-09-27T19:43:05.144Z [err] npm ERR!
2022-09-27T19:43:05.144Z [err]  gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
2022-09-27T19:43:05.144Z [err] npm ERR!
2022-09-27T19:43:05.144Z [err]  gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
2022-09-27T19:43:05.144Z [err] npm ERR!
2022-09-27T19:43:05.144Z [err]  gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
2022-09-27T19:43:05.144Z [err] npm ERR!
2022-09-27T19:43:05.144Z [err]  gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-09-27T19:43:05.144Z [err] npm ERR!
2022-09-27T19:43:05.144Z [err]  gyp ERR! System Linux 5.15.67
2022-09-27T19:43:05.144Z [err] npm ERR!
2022-09-27T19:43:05.145Z [err]  gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2022-09-27T19:43:05.145Z [err] npm ERR!
2022-09-27T19:43:05.145Z [err]  gyp ERR! cwd /config/node-red/node_modules/@serialport/bindings
2022-09-27T19:43:05.145Z [err] npm ERR!
2022-09-27T19:43:05.145Z [err]  gyp ERR! node -v v16.16.0
2022-09-27T19:43:05.145Z [err] npm ERR!
2022-09-27T19:43:05.145Z [err]  gyp ERR! node-gyp -v v9.0.0
2022-09-27T19:43:05.145Z [err] npm ERR!
2022-09-27T19:43:05.145Z [err]  gyp ERR! not ok
2022-09-27T19:43:05.156Z [err] 
2022-09-27T19:43:05.157Z [err] npm ERR!
2022-09-27T19:43:05.157Z [err]  A complete log of this run can be found in:
2022-09-27T19:43:05.157Z [err] npm ERR!
2022-09-27T19:43:05.157Z [err]      /root/.npm/_logs/2022-09-27T19_42_47_198Z-debug-0.log
2022-09-27T19:43:05.210Z rc=1


```

**Comment by frenck** [comment]
Python is not needed to run node-red. If you are building/manually installing nodes that do need it, feel free to install the needed dependencies using the add-on configuration option (as per add-on documentation).

../Frenck

**Comment by Wolvverine** [comment]
Installed from Palette in Node-Red, the same:

https://github.com/hassio-addons/addon-node-red/issues/1183

**Comment by frenck** [comment]
> Installed from Palette in Node-Red, the same:

Same answer as above.
