### ISSUE TITLE
Error by Update "node-red-contrib-modbus"

### ISSUE THREAD

**Issue by mathiaslehmann** [hassio-addons/addon-node-red#1451]
Hello I get the following error when updating "node-red-contrib-modbus" via the palette management of Node Red. Is my environment broken or is something really missing here? If yes, how can I correct it?

`
-----------------------------------------------------------
2022-09-27T19:45:16.049Z Installieren : node-red-contrib-modbus 5.23.2

2022-09-27T19:45:15.897Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-modbus@5.23.2
2022-09-27T19:45:16.419Z [err] npm
2022-09-27T19:45:16.420Z [err]  
2022-09-27T19:45:16.420Z [err] WARN
2022-09-27T19:45:16.420Z [err]  
2022-09-27T19:45:16.420Z [err] config
2022-09-27T19:45:16.420Z [err]  production Use `--omit=dev` instead.
2022-09-27T19:45:26.446Z [err] npm
2022-09-27T19:45:26.446Z [err]  
2022-09-27T19:45:26.447Z [err] ERR!
2022-09-27T19:45:26.447Z [err]  
2022-09-27T19:45:26.447Z [err] code
2022-09-27T19:45:26.447Z [err]  1
2022-09-27T19:45:26.447Z [err] npm
2022-09-27T19:45:26.447Z [err]  
2022-09-27T19:45:26.447Z [err] ERR!
2022-09-27T19:45:26.447Z [err]  
2022-09-27T19:45:26.448Z [err] path
2022-09-27T19:45:26.448Z [err]  /config/node-red/node_modules/@serialport/bindings
2022-09-27T19:45:26.449Z [err] npm
2022-09-27T19:45:26.450Z [err]  
2022-09-27T19:45:26.450Z [err] ERR!
2022-09-27T19:45:26.450Z [err]  command failed
2022-09-27T19:45:26.450Z [err] npm
2022-09-27T19:45:26.450Z [err]  
2022-09-27T19:45:26.450Z [err] ERR!
2022-09-27T19:45:26.450Z [err]  
2022-09-27T19:45:26.450Z [err] command
2022-09-27T19:45:26.450Z [err]  sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2022-09-27T19:45:26.451Z [err] npm
2022-09-27T19:45:26.451Z [err]  
2022-09-27T19:45:26.451Z [err] ERR!
2022-09-27T19:45:26.451Z [err]  prebuild-install warn install No prebuilt binaries found (target=16.16.0 runtime=node arch=x64 libc=musl platform=linux)
2022-09-27T19:45:26.451Z [err] npm
2022-09-27T19:45:26.451Z [err]  
2022-09-27T19:45:26.451Z [err] ERR!
2022-09-27T19:45:26.451Z [err]  gyp info it worked if it ends with ok
2022-09-27T19:45:26.451Z [err] npm
2022-09-27T19:45:26.451Z [err]  
2022-09-27T19:45:26.451Z [err] ERR!
2022-09-27T19:45:26.452Z [err]  gyp info using node-gyp@9.0.0
2022-09-27T19:45:26.452Z [err] npm
2022-09-27T19:45:26.452Z [err]  
2022-09-27T19:45:26.452Z [err] ERR!
2022-09-27T19:45:26.452Z [err]  gyp info using node@16.16.0 | linux | x64
2022-09-27T19:45:26.452Z [err] npm
2022-09-27T19:45:26.452Z [err]  
2022-09-27T19:45:26.452Z [err] ERR!
2022-09-27T19:45:26.452Z [err]  gyp ERR! find Python 
2022-09-27T19:45:26.452Z [err] npm
2022-09-27T19:45:26.453Z [err]  
2022-09-27T19:45:26.453Z [err] ERR!
2022-09-27T19:45:26.453Z [err]  gyp ERR! find Python checking Python explicitly set from command line or npm configuration
2022-09-27T19:45:26.453Z [err] npm
2022-09-27T19:45:26.453Z [err]  
2022-09-27T19:45:26.453Z [err] ERR!
2022-09-27T19:45:26.453Z [err]  gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
2022-09-27T19:45:26.453Z [err] npm
2022-09-27T19:45:26.453Z [err]  
2022-09-27T19:45:26.453Z [err] ERR!
2022-09-27T19:45:26.453Z [err]  gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
2022-09-27T19:45:26.454Z [err] npm
2022-09-27T19:45:26.454Z [err]  
2022-09-27T19:45:26.454Z [err] ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2022-09-27T19:45:26.454Z [err] npm ERR! gyp ERR! find Python checking if "python3" can be used
2022-09-27T19:45:26.454Z [err] npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2022-09-27T19:45:26.454Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2022-09-27T19:45:26.454Z [err] npm ERR!
2022-09-27T19:45:26.454Z [err]  gyp ERR! find Python - "python" is not in PATH or produced an error
2022-09-27T19:45:26.454Z [err] npm
2022-09-27T19:45:26.457Z [err]  ERR! gyp ERR! find Python 
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! find Python **********************************************************
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! find Python you can try one of the following options:
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! find Python For more information consult the documentation at:
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! find Python **********************************************************
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! find Python 
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! configure error 
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! stack     at exithandler (node:child_process:406:5)
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! System Linux 5.15.67
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! cwd /config/node-red/node_modules/@serialport/bindings
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! node -v v16.16.0
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! node-gyp -v v9.0.0
2022-09-27T19:45:26.457Z [err] npm ERR! gyp ERR! not ok
2022-09-27T19:45:26.458Z [err] 
2022-09-27T19:45:26.458Z [err] npm
2022-09-27T19:45:26.458Z [err]  
2022-09-27T19:45:26.458Z [err] ERR!
2022-09-27T19:45:26.458Z [err]  A complete log of this run can be found in:
2022-09-27T19:45:26.458Z [err] npm
2022-09-27T19:45:26.458Z [err]  
2022-09-27T19:45:26.458Z [err] ERR!
2022-09-27T19:45:26.459Z [err]      /root/.npm/_logs/2022-09-27T19_45_16_372Z-debug-0.log
2022-09-27T19:45:26.468Z rc=1`

**Comment by frenck** [comment]
As per logs, Python is not installed (including all build tools as well). If you manage nodes manually, you are also required to provide all requirements manually. You can configure/add system packages to meet that requirement using the add-on configuration (see add-on documentation).

../Frenck

**Comment by mathiaslehmann** [comment]
Hello frenck, thanks for the quick reply and the great work on the whole project. Unfortunately, I'm not that deep into the matter, so I have to ask again. I don't even use the "node-red-contrib-modbus" module myself, but I always try to keep the modules up-to-date and update them in the palette management when an update is pending for a module. Isn't that correct of me to do that? I have already installed a brand new Node Red, the module "node-red-contrib-modbus" is available by default in Node Red and would like to be updated immediately, but it fails with the error described.

Thank you for your help.

**Comment by frenck** [comment]
> Isn't that correct of me to do that?

Nope. It means you are managing the palette instead of the built-in shipped one. 

The version you have updated too / installed is not the version provided by the add-on, thus you are responsible for keeping it up to date (including all its dependencies).

**Comment by mathiaslehmann** [comment]
Thanks for the explanation. So if I understand it correctly, the official modules are updated with the official updates of the add-on like it happened here 2 days ago #1449 .This adaptation will then come with the next add-on update?

Thank you very much and sorry for the questions but I'm not that good with these things yet.

**Comment by frenck** [comment]
> This adaptation will then come with the next add-on update?

yes
