### ISSUE TITLE
Cannot update Modbus 

### ISSUE THREAD

**Issue by vantech14** [hassio-addons/addon-node-red#1461]
Running the latest version of NodeRed (13.4.0) and received the following error when trying to update the Modbus module. 

-----------------------------------------------------------
2022-10-06T18:14:43.222Z Install : node-red-contrib-modbus 5.23.2

2022-10-06T18:14:43.623Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-modbus@5.23.2
2022-10-06T18:14:43.888Z [err] npm
2022-10-06T18:14:43.888Z [err]  WARN config production Use `--omit=dev` instead.
2022-10-06T18:14:50.214Z [err] npm
2022-10-06T18:14:50.214Z [err]  ERR! code 1
2022-10-06T18:14:50.214Z [err] npm ERR! path /config/node-red/node_modules/@serialport/bindings
2022-10-06T18:14:50.215Z [err] npm ERR! command failed
2022-10-06T18:14:50.215Z [err] npm ERR! command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2022-10-06T18:14:50.215Z [err] npm ERR! prebuild-install warn install No prebuilt binaries found (target=16.16.0 runtime=node arch=x64 libc=musl platform=linux)
2022-10-06T18:14:50.215Z [err] npm ERR! gyp info it worked if it ends with ok
2022-10-06T18:14:50.215Z [err] npm ERR! gyp info using node-gyp@9.0.0
2022-10-06T18:14:50.215Z [err] npm ERR! gyp info using node@16.16.0 | linux | x64
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python 
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python checking Python explicitly set from command line or npm configuration
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
2022-10-06T18:14:50.215Z [err] npm ERR!
2022-10-06T18:14:50.215Z [err]  gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python checking if "python3" can be used
2022-10-06T18:14:50.215Z [err] npm 
2022-10-06T18:14:50.215Z [err] ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python 
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python **********************************************************
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python you can try one of the following options:
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2022-10-06T18:14:50.215Z [err] npm 
2022-10-06T18:14:50.215Z [err] ERR! gyp ERR! find Python - Set the environment variable PYTHON
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2022-10-06T18:14:50.215Z [err] npm 
2022-10-06T18:14:50.215Z [err] ERR! gyp ERR! find Python For more information consult the documentation at:
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2022-10-06T18:14:50.215Z [err] npm ERR!
2022-10-06T18:14:50.215Z [err]  gyp ERR! find Python **********************************************************
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python 
2022-10-06T18:14:50.215Z [err] npm 
2022-10-06T18:14:50.215Z [err] ERR! gyp ERR! configure error 
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
2022-10-06T18:14:50.215Z [err] npm 
2022-10-06T18:14:50.216Z [err] ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
2022-10-06T18:14:50.216Z [err] npm 
2022-10-06T18:14:50.216Z [err] ERR!
2022-10-06T18:14:50.216Z [err]  gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
2022-10-06T18:14:50.216Z [err] npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
2022-10-06T18:14:50.216Z [err] npm ERR!
2022-10-06T18:14:50.216Z [err]  gyp ERR! stack     at exithandler (node:child_process:406:5)
2022-10-06T18:14:50.216Z [err] npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
2022-10-06T18:14:50.216Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
2022-10-06T18:14:50.216Z [err] npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
2022-10-06T18:14:50.216Z [err] npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
2022-10-06T18:14:50.216Z [err] npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-10-06T18:14:50.216Z [err] npm 
2022-10-06T18:14:50.216Z [err] ERR! gyp ERR! System Linux 5.15.67
2022-10-06T18:14:50.216Z [err] npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2022-10-06T18:14:50.216Z [err] npm ERR! gyp ERR! cwd /config/node-red/node_modules/@serialport/bindings
2022-10-06T18:14:50.216Z [err] npm
2022-10-06T18:14:50.216Z [err]  ERR! gyp ERR! node -v v16.16.0
2022-10-06T18:14:50.216Z [err] npm ERR! gyp ERR! node-gyp -v v9.0.0
2022-10-06T18:14:50.216Z [err] npm 
2022-10-06T18:14:50.216Z [err] ERR! gyp ERR! not ok
2022-10-06T18:14:50.217Z [err] 
2022-10-06T18:14:50.217Z [err] npm ERR! A complete log of this run can be found in:
2022-10-06T18:14:50.217Z [err] npm ERR!     /root/.npm/_logs/2022-10-06T18_14_43_859Z-debug-0.log
2022-10-06T18:14:50.229Z rc=1

**Comment by frenck** [comment]
```
2022-10-06T18:14:50.215Z [err] ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python **********************************************************
2022-10-06T18:14:50.215Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
```

If you manually manage your nodes, you'll also need to manually take care of their dependencies. See the add-on documentation on how to install extra system dependencies when needed.

**Comment by vantech14** [comment]
@frenck this module was installed at the same time as installing node red into home assistant. 

This wasn't manually added by me. There is no option to remove the module, either in the UI or the backend. 

Thanks.
