### ISSUE TITLE
Endless disconnect loop

### ISSUE THREAD

**Issue by xaralis** [hassio-addons/addon-node-red#1467]
# Problem/Motivation

Out of nowhere, my node-red addon stopped working after uptime of at least several months without issues. It doesn't seem to be related to any update, it just stopped working.

## Expected behavior

Node-RED starts up, connects to Homeassistant and works as intended.

## Actual behavior

After booting up, Node-RED tries to connect to HASS repeatedly and is constantly reporting it got disconnected:

```
[10:22:09] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
17 Oct 10:22:13 - [info] 
Welcome to Node-RED
===================
17 Oct 10:22:13 - [info] Node-RED version: v3.0.2
17 Oct 10:22:13 - [info] Node.js  version: v16.16.0
17 Oct 10:22:13 - [info] Linux 5.15.32-v8 arm64 LE
17 Oct 10:22:15 - [info] Loading palette nodes
17 Oct 10:22:22 - [info] Dashboard version 3.2.0 started at /endpoint/ui
17 Oct 10:22:24 - [info] Settings file  : /etc/node-red/config.js
17 Oct 10:22:24 - [info] Context store  : 'default' [module=memory]
17 Oct 10:22:24 - [info] User directory : /config/node-red/
17 Oct 10:22:24 - [warn] Projects disabled : editorTheme.projects.enabled=false
17 Oct 10:22:24 - [info] Flows file     : /config/node-red/flows.json
17 Oct 10:22:24 - [warn] Encrypted credentials not found
17 Oct 10:22:24 - [info] Server now running at http://127.0.0.1:46836/
17 Oct 10:22:24 - [info] Starting flows
17 Oct 10:22:24 - [info] Started flows
[10:22:25] INFO: Starting NGinx...
17 Oct 10:22:29 - [info] [server:Home Assistant] Connecting to http://supervisor/core
17 Oct 10:22:29 - [info] [server:Home Assistant] Connected to http://supervisor/core
17 Oct 10:22:30 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
17 Oct 10:22:35 - [info] [server:Home Assistant] Connecting to http://supervisor/core
17 Oct 10:22:35 - [info] [server:Home Assistant] Connected to http://supervisor/core
17 Oct 10:22:35 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
17 Oct 10:22:40 - [info] [server:Home Assistant] Connecting to http://supervisor/core
17 Oct 10:22:40 - [info] [server:Home Assistant] Connected to http://supervisor/core
17 Oct 10:22:41 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
17 Oct 10:22:46 - [info] [server:Home Assistant] Connecting to http://supervisor/core
17 Oct 10:22:46 - [info] [server:Home Assistant] Connected to http://supervisor/core
17 Oct 10:22:46 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
17 Oct 10:22:51 - [info] [server:Home Assistant] Connecting to http://supervisor/core
17 Oct 10:22:51 - [info] [server:Home Assistant] Connected to http://supervisor/core
17 Oct 10:22:52 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
```

Sometimes (but not always so I guess it's unrelated), I can also see following in my Homassistant logs:

```
2022-10-17 10:16:22.013 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547861319536] Client exceeded max pending messages [2]: 2048
2022-10-17 10:16:22.015 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547440633616] Client exceeded max pending messages [2]: 2048
2022-10-17 10:16:22.017 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548064447072] Client exceeded max pending messages [2]: 2048
2022-10-17 10:16:22.019 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547861319536] Client exceeded max pending messages [2]: 2048
2022-10-17 10:16:22.021 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547440633616] Client exceeded max pending messages [2]: 2048
2022-10-17 10:16:22.024 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548064447072] Client exceeded max pending messages [2]: 2048
2022-10-17 10:16:22.026 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547861319536] Client exceeded max pending messages [2]: 2048
2022-10-17 10:16:22.028 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547440633616] Client exceeded max pending messages [2]: 2048
2022-10-17 10:16:23.603 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-10-17 10:16:24.345 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 52, in get
return await WebSocketHandler(request.app["hass"], request).async_handle()
File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 178, in async_handle
await wsock.prepare(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_ws.py", line 138, in prepare
payload_writer = await super().prepare(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_response.py", line 421, in prepare
return await self._start(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_response.py", line 429, in _start
await self._write_headers()
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_response.py", line 502, in _write_headers
await writer.write_headers(status_line, self._headers)
File "/usr/local/lib/python3.10/site-packages/aiohttp/http_writer.py", line 131, in write_headers
self._write(buf)
File "/usr/local/lib/python3.10/site-packages/aiohttp/http_writer.py", line 76, in _write
raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

## Steps to reproduce

Can't tell, I even reverted to older backup (when things definitely worked) but to no avail.

**Comment by xaralis** [comment]
Well, it seems that reverting to even older backup fixed things up and Node-RED doesn't disconnect. Still, I would appreciate to understand what might have gone wrong.

**Comment by xaralis** [comment]
After updating Homeassistant to latest version, the problem has returned :(

**Comment by xaralis** [comment]
I was able to work around the issue by unchecking the "Using the Home Assistant Add-on"  box and supplying the Base URL and Access token by hand.

<img width="473" alt="image" src="https://user-images.githubusercontent.com/441739/196359860-db1925f3-990c-47dd-9771-2479c01a73ff.png">

The connection issue now seems to be gone. However, another problem appeared: all the inject nodes now have manual injection button greyed out:

<img width="330" alt="image" src="https://user-images.githubusercontent.com/441739/196360066-0cb654ec-7a47-4225-8d26-310f87053166.png">

... and cannot be clicked which makes developing flows pretty hard. Also, all the nodes seem to be missing those status messages. It looks like a connection issue of sorts once again.

**Comment by slx-io** [comment]
I have a similar issue. I went so far as to completely uninstall the addon and the companion integration, remove ~/config/node-red and start again to no avail.

Even on a fresh install I add a call_service node and there are no domains, services or entities found. I can type the entities myself, but the lack of autocomplete doesn't let me do the same for domains or services.

And I have the exact same issue as the inject button being greyed out.

I've purged my backups from early September so I can't go back to the previous version.

Nothing helpful in the logs (Even when in trace/debug mode).

**Comment by slx-io** [comment]
Yup. This worked for me too.

**Comment by MRobi1** [comment]
Am I understanding this correctly that a restart is supposed to solve this issue? I've been having it since updating to 2022.11.X and have restarted 5 or 6 times in the past few weeks.

I'm running into this around once per day. Usually a restart of the add-on buys me another 24hrs. But after restarting HA it still seems to come back.

```
18 Nov 17:27:58 - [error] [api-call-service:Set Temp 20] Call-Service attempted without connection to server.
18 Nov 17:27:58 - [error] [api-call-service:Set Temp 17] Call-Service attempted without connection to server.
18 Nov 17:27:58 - [error] [api-call-service:Set Temp 19] Call-Service attempted without connection to server.
18 Nov 17:28:02 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:02 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:05 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:28:10 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:10 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:13 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:28:18 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:18 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:20 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:28:25 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:26 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:26 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:28:31 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:31 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:35 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:28:40 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:40 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:43 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:28:48 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:48 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:50 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:28:55 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:55 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:56 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:29:01 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:29:01 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:29:05 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:29:10 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:29:10 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:29:13 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:29:18 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:29:18 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:29:20 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:29:25 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:29:25 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:29:26 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:29:31 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:29:31 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:29:35 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:29:40 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:29:40 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:29:43 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:29:48 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:29:51 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:29:53 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:29:58 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:29:58 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:30:00 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:30:05 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:30:05 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:30:05 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:30:10 - [error] [api-call-service:Turn Off Lights] Call-Service attempted without connection to server.
18 Nov 17:30:10 - [info] [server:Home Assistant] Connecting to http://supervisor/core
```

**Comment by xaralis** [comment]
@MRobi1 No, restart won't fix it. See instructions here

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/736#issuecomment-1304072318

**Comment by MRobi1** [comment]
OK, missed the part about deleting known_devices.yaml.
Made a backup of the file, deleted it, rebooted HA. A new known_devices.yaml was created (odd, isn't this deprecated?) this time with only 4 devices.

Although shortly after....
```
19 Nov 16:08:03 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
19 Nov 16:08:08 - [info] [server:Home Assistant] Connecting to http://supervisor/core
19 Nov 16:08:08 - [info] [server:Home Assistant] Connected to http://supervisor/core
```

I'd say there is something else causing this.

**Comment by xaralis** [comment]
@MRobi1 Well the issue itself is kinda generic in nature. It seems to be related to too many data being transferred in scope of a single WebSocket message. In my case (and few others) it was due to `known_devices.yml` simply being too big. I think it gets sent to Node RED in form of entity list, . This was then tracked down to the Bluetooth tracker integration which is used to sniff new BT devices. If left out with `track_new_devices: true` for long time period, it might fill up the `known_devices.yml` file with tons of scrap. In my case, it got like 20k lines while only 3 devices were in fact relevant.

If this doesn't help in your case, I suggest looking out for something similar elsewhere in your HA setup. Or, as this issue has little to do with this HA addon, go and ask on https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/ issue tracker where your chances to find suggestions are definitely higher.

**Comment by MRobi1** [comment]
@xaralis question for yourself or others who are having this issue.
After the latest update, the NR add-on would not start at all. Reading others with the issue, there was an npm-package or system-package (I forget which now, it's been a few weeks) that had to be removed to allow it to boot. I'm wondering if these 2 issues may be related?

What do you have in your config under npm_packages and system_packages?
