### ISSUE TITLE
v14.0.0 will not start

### ISSUE THREAD

**Issue by Swiftnesses** [hassio-addons/addon-node-red#1514]
My add-on automatically updated a few hours ago and now will not start.

This is the error I see in the container log:

```
To address issues that do not require attention, run:
  npm audit fix
To address all issues possible (including breaking changes), run:
  npm audit fix --force
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[11:13:43] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js
13 Dec 11:13:44 - [info] 
Welcome to Node-RED
===================
13 Dec 11:13:44 - [info] Node-RED version: v3.0.2
13 Dec 11:13:44 - [info] Node.js  version: v18.12.1
13 Dec 11:13:44 - [info] Linux 5.10.0-19-amd64 x64 LE
13 Dec 11:13:45 - [info] Loading palette nodes
13 Dec 11:13:47 - [info] Dashboard version 3.2.3 started at /endpoint/ui
/config/node-red/node_modules/node-red-node-pi-gpio/testgpio: line 8: python: command not found
13 Dec 11:13:47 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
13 Dec 11:13:48 - [warn] ------------------------------------------------------
13 Dec 11:13:48 - [warn] [node-red-node-rbe/rbe] 'rbe' already registered by module node-red
13 Dec 11:13:48 - [warn] ------------------------------------------------------
13 Dec 11:13:48 - [info] Settings file  : /etc/node-red/config.js
13 Dec 11:13:48 - [warn] Use of httpRoot is DEPRECATED. Use httpNodeRoot/httpAdminRoot instead
13 Dec 11:13:48 - [info] Context store  : 'memory' [module=memory]
13 Dec 11:13:48 - [info] Context store  : 'disk' [module=localfilesystem]
13 Dec 11:13:48 - [info] User directory : /config/node-red/
13 Dec 11:13:48 - [warn] Projects disabled : editorTheme.projects.enabled=false
13 Dec 11:13:48 - [info] Flows file     : /config/node-red/flows.json
13 Dec 11:13:48 - [info] Server now running at http://127.0.0.1:46836/
[11:13:48] INFO: Starting NGinx...
13 Dec 11:13:48 - [info] Starting flows
13 Dec 11:13:49 - [info] Started flows
13 Dec 11:13:49 - [info] [mqtt-broker:Mosquito (Home Assistant)] Connected to broker: node-red@mqtt://localhost:1883
Tue, 13 Dec 2022 11:13:49 GMT express deprecated res.status("200"): use res.status(200) instead at node_modules/@node-red/nodes/core/network/21-httpin.js:328:34
13 Dec 11:13:53 - [info] [server:Home Assistant] Connecting to http://supervisor/core
13 Dec 11:13:53 - [info] [server:Home Assistant] Connected to http://supervisor/core
13 Dec 11:13:53 - [red] Uncaught Exception:
13 Dec 11:13:53 - [error] Error: error:0308010C:digital envelope routines::unsupported
    at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:141:10)
    at /config/node-red/node_modules/ntlm/lib/smbhash.js:46:22
    at Array.forEach (<anonymous>)
    at lmhashbuf (/config/node-red/node_modules/ntlm/lib/smbhash.js:45:20)
    at Object.encodeType3 (/config/node-red/node_modules/ntlm/lib/ntlm.js:106:3)
    at Object.generate (/config/node-red/node_modules/@marsaud/smb2/lib/messages/session_setup_step2.js:14:22)
    at SMB2Forge.request (/config/node-red/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:16:24)
    at /config/node-red/node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:114:11
    at Object.01000000 (/config/node-red/node_modules/@marsaud/smb2/lib/tools/message.js:15:15)
    at Socket.<anonymous> (/config/node-red/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:71:31)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
2022/12/13 11:13:53 [error] 324#324: *7 upstream prematurely closed connection while reading response header from upstream, client: 192.168.1.35, server: a0d7b954-nodered, request: "GET /endpoint/lametric/weather HTTP/1.1", upstream: "http://127.0.0.1:46836/endpoint/lametric/weather", host: "192.168.1.16:1880"
2022/12/13 11:13:53 [error] 324#324: *8 upstream prematurely closed connection while reading response header from upstream, client: 192.168.1.35, server: a0d7b954-nodered, request: "GET /endpoint/lametric/neurio HTTP/1.1", upstream: "http://127.0.0.1:46836/endpoint/lametric/neurio", host: "192.168.1.16:1880"
2022/12/13 11:13:53 [error] 324#324: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.35, server: a0d7b954-nodered, request: "GET /endpoint/lametric/weather HTTP/1.1", upstream: "http://127.0.0.1:46836/endpoint/lametric/weather", host: "192.168.1.16:1880"
2022/12/13 11:13:53 [error] 324#324: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.35, server: a0d7b954-nodered, request: "GET /endpoint/lametric/neurio HTTP/1.1", upstream: "http://127.0.0.1:46836/endpoint/lametric/neurio", host: "192.168.1.16:1880"
[11:13:53] INFO: Service Node-RED exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[11:13:54] INFO: Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service nodered: stopping
s6-rc: info: service init-nginx successfully stopped
[11:13:54] INFO: Service Node-RED exited with code 256 (by signal 15)
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by frenck** [comment]
```json
13 Dec 11:13:53 - [error] Error: error:0308010C:digital envelope routines::unsupported
    at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:141:10)
    at /config/node-red/node_modules/ntlm/lib/smbhash.js:46:22
```

This is loading a module from your config folder, meaning this is caused by an custom node you are using.

The v14.0.0 release of this add-on is a major release because a new major version of both Alpine Linux (3.17) and NodeJS (18) is now being used.

See also: <https://github.com/hassio-addons/addon-node-red/releases/tag/v14.0.0>

Make sure your custom-installed modules are compatible with that. You can enable safe mode for Node-RED in the add-on configuration options. Safe mode will skip the loading of nodes, allowing Node-RED to start and you to update and/or change things to be compatible.

Ref: <https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#option-safe_mode>

../Frenck

**Comment by Swiftnesses** [comment]
Hi @frenck that's helpful, thanks.

**Comment by frenck** [comment]
No problem! 👍 

../Frenck

**Comment by g4seb** [comment]
Hi @frenck . I try to put safe_mode to true, but impossible to start node red too.

**Comment by frenck** [comment]
Clean out your node_modules folder, that might help.

**Comment by g4seb** [comment]
> Clean out your node_modules folder, that might help.

you mean erase everything in it?

**Comment by g4seb** [comment]
I don't understand what did i do to clean the node module. Could give me example please ?
