### ISSUE TITLE
Error during instalation node-red-contrib-i2c 0.9.0

### ISSUE THREAD

**Issue by kfulko** [hassio-addons/addon-node-red#1564]
Hardware: Rpi 4B
Home Assistant Supervised 2023.2.4
Supervisor: 2023.01.1
OS: Debian 11

# Problem/Motivation

Error when installing node-red-contrib-i2c 0.9.0
Can't find python.
Deprecate bcypt@3.0.6 &  node-pre-gyp@0.12.0

## Expected behavior

Bump bcrypt@5.0.0
Upgrade node-pre-gyp@0.12 to @mapbox/node-pre-gyp
Fix the python location issue.

## Actual behavior

Error

Logfile:

> -----------------------------------------------------------

2023-02-28T10:53:09.747Z` Install : node-red-contrib-i2c 0.9.0

2023-02-28T10:53:09.289Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-i2c@0.9.0
2023-02-28T10:53:11.929Z [err] npm
2023-02-28T10:53:11.931Z [err]  WARN
2023-02-28T10:53:11.931Z [err]  config production Use `--omit=dev` instead.
2023-02-28T10:53:21.197Z [err] npm
2023-02-28T10:53:21.198Z [err]  
2023-02-28T10:53:21.198Z [err] WARN
2023-02-28T10:53:21.198Z [err]  
2023-02-28T10:53:21.199Z [err] deprecated
2023-02-28T10:53:21.199Z [err]  bcrypt@3.0.6: versions < v5.0.0 do not handle NUL in passwords properly
2023-02-28T10:53:21.233Z [err] npm
2023-02-28T10:53:21.234Z [err]  
2023-02-28T10:53:21.234Z [err] WARN
2023-02-28T10:53:21.236Z [err]  
2023-02-28T10:53:21.236Z [err] deprecated
2023-02-28T10:53:21.236Z [err]  node-pre-gyp@0.12.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
2023-02-28T10:53:23.624Z [err] npm 
2023-02-28T10:53:23.625Z [err] ERR! code 1
2023-02-28T10:53:23.625Z [err] npm ERR! path /config/node-red/node_modules/i2c-bus
2023-02-28T10:53:23.631Z [err] npm
2023-02-28T10:53:23.632Z [err]  ERR! command failed
2023-02-28T10:53:23.632Z [err] npm ERR! 
2023-02-28T10:53:23.632Z [err] command sh -c node-gyp rebuild
2023-02-28T10:53:23.632Z [err] npm ERR!
2023-02-28T10:53:23.633Z [err]  gyp info it worked if it ends with ok
2023-02-28T10:53:23.633Z [err] npm ERR! gyp info using node-gyp@9.3.0
2023-02-28T10:53:23.633Z [err] npm
2023-02-28T10:53:23.634Z [err]  ERR!
2023-02-28T10:53:23.634Z [err]  gyp info using node@18.14.1 | linux | arm64
2023-02-28T10:53:23.634Z [err] npm ERR! gyp ERR! find Python 
2023-02-28T10:53:23.634Z [err] npm ERR! gyp ERR! find Python checking Python explicitly set from command line or npm configuration
2023-02-28T10:53:23.634Z [err] npm
2023-02-28T10:53:23.634Z [err]  ERR! gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
2023-02-28T10:53:23.634Z [err] npm ERR! gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
2023-02-28T10:53:23.634Z [err] npm
2023-02-28T10:53:23.634Z [err]  ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2023-02-28T10:53:23.634Z [err] npm ERR! gyp ERR! find Python checking if "python3" can be used
2023-02-28T10:53:23.634Z [err] npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2023-02-28T10:53:23.634Z [err] npm ERR!
2023-02-28T10:53:23.634Z [err]  gyp ERR! find Python checking if "python" can be used
2023-02-28T10:53:23.634Z [err] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2023-02-28T10:53:23.634Z [err] npm
2023-02-28T10:53:23.635Z [err]  ERR! gyp ERR! find Python 
2023-02-28T10:53:23.635Z [err] npm ERR!
2023-02-28T10:53:23.635Z [err]  gyp ERR! find Python **********************************************************
2023-02-28T10:53:23.635Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2023-02-28T10:53:23.635Z [err] npm
2023-02-28T10:53:23.635Z [err]  ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2023-02-28T10:53:23.635Z [err] npm ERR!
2023-02-28T10:53:23.635Z [err]  gyp ERR! find Python you can try one of the following options:
2023-02-28T10:53:23.635Z [err] npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2023-02-28T10:53:23.635Z [err] npm
2023-02-28T10:53:23.635Z [err]  ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2023-02-28T10:53:23.635Z [err] npm ERR!
2023-02-28T10:53:23.635Z [err]  gyp ERR! find Python - Set the environment variable PYTHON
2023-02-28T10:53:23.635Z [err] npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
2023-02-28T10:53:23.635Z [err] npm
2023-02-28T10:53:23.636Z [err]  ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2023-02-28T10:53:23.636Z [err] npm ERR! gyp ERR! find Python For more information consult the documentation at:
2023-02-28T10:53:23.636Z [err] npm 
2023-02-28T10:53:23.636Z [err] ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2023-02-28T10:53:23.636Z [err] npm ERR! gyp ERR! find Python **********************************************************
2023-02-28T10:53:23.636Z [err] npm
2023-02-28T10:53:23.636Z [err]  ERR! gyp ERR! find Python 
2023-02-28T10:53:23.636Z [err] npm ERR!
2023-02-28T10:53:23.636Z [err]  gyp ERR! configure error 
2023-02-28T10:53:23.636Z [err] npm ERR!
2023-02-28T10:53:23.636Z [err]  gyp ERR! stack Error: Could not find any Python installation to use
2023-02-28T10:53:23.636Z [err] npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
2023-02-28T10:53:23.636Z [err] npm
2023-02-28T10:53:23.636Z [err]  ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
2023-02-28T10:53:23.636Z [err] npm ERR!
2023-02-28T10:53:23.637Z [err]  gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
2023-02-28T10:53:23.637Z [err] npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
2023-02-28T10:53:23.637Z [err] npm
2023-02-28T10:53:23.637Z [err]  ERR! gyp ERR! stack     at exithandler (node:child_process:427:5)
2023-02-28T10:53:23.637Z [err] npm ERR!
2023-02-28T10:53:23.637Z [err]  gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
2023-02-28T10:53:23.637Z [err] npm ERR!
2023-02-28T10:53:23.637Z [err]  gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
2023-02-28T10:53:23.637Z [err] npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
2023-02-28T10:53:23.637Z [err] npm
2023-02-28T10:53:23.637Z [err]  ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
2023-02-28T10:53:23.637Z [err] npm 
2023-02-28T10:53:23.637Z [err] ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-02-28T10:53:23.637Z [err] npm ERR! gyp ERR! System Linux 5.15.84-v8+
2023-02-28T10:53:23.637Z [err] npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2023-02-28T10:53:23.637Z [err] npm
2023-02-28T10:53:23.638Z [err]  ERR! gyp ERR! cwd /config/node-red/node_modules/i2c-bus
2023-02-28T10:53:23.638Z [err] npm ERR!
2023-02-28T10:53:23.638Z [err]  gyp ERR! node -v v18.14.1
2023-02-28T10:53:23.638Z [err] npm ERR!
2023-02-28T10:53:23.638Z [err]  gyp ERR! node-gyp -v v9.3.0
2023-02-28T10:53:23.638Z [err] npm ERR! gyp ERR! not ok
2023-02-28T10:53:23.646Z [err] 
2023-02-28T10:53:23.647Z [err] npm ERR!
2023-02-28T10:53:23.647Z [err]  A complete log of this run can be found in:
2023-02-28T10:53:23.647Z [err] npm ERR!     /root/.npm/_logs/2023-02-28T10_53_11_773Z-debug-0.log
2023-02-28T10:53:23.695Z rc=1

>

**Comment by tnagels** [comment]
I have the same issue with `node-red-contrib-rfxcom`. It seems python is missing in the Docker container; it seems to break quite a lot of node installations.

**Comment by frenck** [comment]
As the error says, Python is missing. You need to add dependencies that are needed for the nodes you are installing.

Closing this, as it is not an add-on issue.

../Frenck

**Comment by tnagels** [comment]
@frenck Can you at least give some indication as to how this is done from the frontend? Thanks.

**Comment by frenck** [comment]
Try reading the docs?

**Comment by tnagels** [comment]
Yes, I did read the docs and still cannot figure it out. If I add "python" as 'npm_packages', I get the same error, and in the Alpine Packages list it is not clear to me what I should install using 'system_packages'.

I also searched the internet and did find this issue multiple times, but not a solution which is applicable to the HA addon.
