### ISSUE TITLE
I can't run or access node-red anymore after the update v1.3.5

### ISSUE THREAD

**Issue by pico563** [hassio-addons/addon-node-red#157]
```
-----------------------------------------------------------
 armhf / HassOS 2.8 / HA 0.89.1 / SU 148 / stable
-----------------------------------------------------------

SyntaxError: Error parsing /opt/node_modules/mime/package.json: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at readPackage (module.js:126:52)
    at tryPackage (module.js:136:13)
    at Function.Module._findPath (module.js:218:20)
    at Function.Module._resolveFilename (module.js:546:25)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/node_modules/send/index.js:24:12)
    at Module._compile (module.js:653:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio-addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hassio-addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-10T06_57_44_576Z-debug.log
```
I also don't know how to reach the debug.log in HASSIO.

**Comment by pico563** [comment]
### is there a way to return to previous version ?
I hope someone can answer me.

**Comment by pico563** [comment]
```
The installation of this add-on is pretty straightforward and not different in comparison to installing any other Hass.io add-on.

- Add our Hass.io add-ons repository to your Hass.io instance.
- Install the "Node-RED" add-on.
- Set a credential_secret, which is used to encrypt sensitive data. This is just a "password", which you should save on a secondary location.
- If you do NOT use SSL, be sure to set the ssl option to false.
- Start the "Node-RED" add-on.
- Check the logs of "Node-RED" to see if everything went well.
- Log in with your Home Assistant username/password.
- The add-on works straight out the box! No need to configure a server!

Note: The add-on is pre-configured out of the box! There is no need to add/change/update the server connection settings!

Please read the rest of this document further instructions.
```
