### ISSUE TITLE
Deploy failed PayloadTooLargeError

### ISSUE THREAD

**Issue by milandzuris** [hassio-addons/addon-node-red#1658]
# Version
14.4.4

# Logs
PayloadTooLargeError: request entity too large
    at readStream (/opt/node_modules/raw-body/index.js:156:17)
    at getRawBody (/opt/node_modules/raw-body/index.js:109:12)
    at read (/opt/node_modules/body-parser/lib/read.js:79:3)
    at jsonParser (/opt/node_modules/body-parser/lib/types/json.js:135:5)
    at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/node_modules/express/lib/router/index.js:328:13)
    at /opt/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/opt/node_modules/express/lib/router/index.js:346:12)
    at next (/opt/node_modules/express/lib/router/index.js:280:10)
    at cors (/opt/node_modules/cors/lib/index.js:188:7)
    at /opt/node_modules/cors/lib/index.js:224:17
    at originCallback (/opt/node_modules/cors/lib/index.js:214:15)
    at /opt/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/opt/node_modules/cors/lib/index.js:199:9)
    at corsMiddleware (/opt/node_modules/cors/lib/index.js:204:7)
    at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)

**Comment by milandzuris** [comment]
![image](https://github.com/hassio-addons/addon-node-red/assets/42905545/099d3773-a519-4ce9-9457-c4326903e301)
