### ISSUE TITLE
Deprecated API warning with NodeRed 3.1.0

### ISSUE THREAD

**Issue by plague-doctor** [hassio-addons/addon-node-red#1674]
With the latest NodeRed (running `NodeJS v18.17.1` and `node-red-contrib-home-assistant-websocket version 0.56.1`) I get a Warning:

`12 Sep 09:09:55 - [warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.`

and an Error:

```
12 Sep 08:57:43 - [warn] Error
    at Object.evaluateJSONataExpression (/usr/src/node-red/node_modules/@node-red/util/lib/util.js:775:18)
    at JSONataService.evaluate (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
    at TypedInputService.getValue (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/TypedInputService.js:58:85)
    at /data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/controllers/OutputController.js:53:50
    at Array.forEach (<anonymous>)
    at CurrentStateController.setCustomOutputs (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/controllers/OutputController.js:52:20)
    at CurrentStateController.onInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/current-state/CurrentStateController.js:58:14)
    at CurrentStateController._InputOutputController_preOnInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/controllers/InputOutputController.js:61:76)
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
```

**Comment by sinclairpaul** [comment]
The addon installs the node palette, I would suggest reporting at <https://github.com/zachowj/node-red-contrib-home-assistant-websocket>
