### ISSUE TITLE
Latest build (14.5.0) causes strange error messages with HA 2023.9

### ISSUE THREAD

**Issue by lucode** [hassio-addons/addon-node-red#1683]
# Problem/Motivation
After updating my server to the latest version I get strange error messages in Node-Red, but as far as I can see for now most of the automations still work correctly. I suspect that an incompatibility, either with some new libraries or with the installed Node-RED Companion V2.2.2 exists.

I have noticed that the flow "binary_sensor.ev_imediate_charging_run" doesn't work correctly, it works but it randomly gets a state change. Here comes something more into play as this binary_sensor is actually a variable generated by a HACS addon ["Variable and History"](https://github.com/Wibias/hass-variables).

```
Home Assistant 2023.9.2 
Supervisor 2023.09.2 
Operating System 10.5 
Frontend 20230911.0 - latest 
```
## Expected behavior

Get rid of these error messages 

## Actual behavior

```
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 14.5.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.9.2
 Home Assistant Supervisor: 2023.09.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nginx successfully started
16 Sep 12:01:00 - [error] [api-current-state:Mode =Solar/sch] InputError:  input_select.ev_charging_mode
16 Sep 12:01:00 - [error] [api-current-state:Mode off] InputError:  input_select.ev_charging_mode
16 Sep 12:01:00 - [error] [api-current-state:Immediate run] InputError:  binary_sensor.ev_imediate_charging_run
16 Sep 12:01:00 - [warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.
16 Sep 12:01:00 - [warn] Error: 
    at Object.evaluateJSONataExpression (/opt/node_modules/@node-red/util/lib/util.js:775:18)
    at JSONataService.evaluate (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
    at ComparatorService.getComparatorResult (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/ComparatorService.js:47:91)
    at PollState.getComparatorResult (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:128:39)
    at PollState.onTimer (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/poll-state/controller.js:82:30)
    at EventEmitter.<anonymous> (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/EventsNode.js:39:17)
    at EventEmitter.emit (node:events:526:35)
    at /opt/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:223:68
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
16 Sep 12:01:00 - [warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.
16 Sep 12:01:00 - [warn] Error: 
    at Object.evaluateJSONataExpression (/opt/node_modules/@node-red/util/lib/util.js:775:18)
    at JSONataService.evaluate (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
    at ComparatorService.getComparatorResult (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/ComparatorService.js:47:91)
    at PollState.getComparatorResult (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:128:39)
    at PollState.onTimer (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/poll-state/controller.js:82:30)
    at EventEmitter.<anonymous> (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/EventsNode.js:39:17)
    at EventEmitter.emit (node:events:526:35)
    at /opt/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:223:68
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
16 Sep 12:01:00 - [warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.
16 Sep 12:01:00 - [warn] Error: 
    at Object.evaluateJSONataExpression (/opt/node_modules/@node-red/util/lib/util.js:775:18)
    at JSONataService.evaluate (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
    at ComparatorService.getComparatorResult (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/ComparatorService.js:47:91)
    at PollState.getComparatorResult (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:128:39)
    at PollState.onTimer (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/poll-state/controller.js:82:30)
    at EventEmitter.<anonymous> (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/EventsNode.js:39:17)

```
## Steps to reproduce

Try Node-Red with the same configuration (incl. Node-Red companion). 

## Proposed changes
Nothing to share except downgrading.

**Comment by jlo88** [comment]
Same here, I had to change my logging level to fatal because the log grew to a huge size.

**Comment by sinclairpaul** [comment]
This is an issue with the node-red-contrib-home-assistant-websocket module, please see the repo for that <https://github.com/zachowj/node-red-contrib-home-assistant-websocket>

**Comment by lucode** [comment]
> Same here, I had to change my logging level to fatal because the log grew to a huge size.

Can someone please share the correct name for the Nod-Red logging entry in the configuration.yaml?

```
# LOGGING 
logger:
  default: critical
  logs:
    # log level for HA core
    homeassistant.core: fatal 
    # homeassistant.components.nodered: critical
    custom_components.nodered: critical
```
