### ISSUE TITLE
NodeRED errors in logging

### ISSUE THREAD

**Issue by SynoUser-NL** [hassio-addons/addon-node-red#1692]
# Problem/Motivation

Since updating to 2023.9 and\or OS 10.5 (not sure when they stopped working exactly) my Node-RED automations are only partly working. Automations using the (pink) "device" node do not function at all. This is especially obvious with Shelly Button and Zigbee Button devices, where I use this node to "capture" a button trigger.

The NodeRED logging shows errors:
30 Sep 23:11:42 - [warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.
30 Sep 23:11:42 - [warn] Error: 
    at Object.evaluateJSONataExpression (/opt/node_modules/@node-red/util/lib/util.js:775:18)
    at JSONataService.evaluate (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
    at CallService.evaluateJSONata (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:131:36)
    at CallService.onInput (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/call-service/controller.js:63:50)
    at CallService.preOnInput (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:208:18)
    at /opt/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at Object.trigger (/opt/node_modules/@node-red/util/lib/hooks.js:166:13)
    at callServiceNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
    at callServiceNode.Node.emit (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
    at callServiceNode.Node.receive (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:494:10)

The errors are numerous, but always these same 2.

## Expected behavior

After the update, automations should work as previously configured.

## Actual behavior

NodeRED automations are not triggered.

## Steps to reproduce

Use the "device" node (part of NodeRED in Home Assistant) to trigger an automation.

## Proposed changes

ehmm... fix it ??!
Not sure what exactly is causing this..

**Comment by fenderle** [comment]
+1 -- same here

**Comment by SynoUser-NL** [comment]
Issues seem to have been resolved with update 2023.10, HAOS 10.0, NodeRED 14.6.1 and websocket update 0.57.2.
