### ISSUE TITLE
Node Red crashes on get_entities unknown error

### ISSUE THREAD

**Issue by stevegroom** [hassio-addons/addon-node-red#1777]
# Problem/Motivation

Node Red crashes on get_entities unknown error

## Expected behavior

Get entities node should not crash NR

## Actual behavior

NR crashes and usually restarts

```log
15 Dec 07:37:23 - [red] Uncaught Exception:
15 Dec 07:37:23 - [error] TypeError: Cannot read properties of undefined (reading 'heating')
    at /opt/node_modules/@node-red/util/lib/util.js:430:29
    at Array.reduce (<anonymous>)
    at getObjectProperty (/opt/node_modules/@node-red/util/lib/util.js:429:18)
    at Object.getMessageProperty (/opt/node_modules/@node-red/util/lib/util.js:401:12)
    at NodeRedContextService.get (/config/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/NodeRedContextService.js:36:39)
    at ComparatorService.getComparatorResult (/config/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/ComparatorService.js:39:98)
    at GetEntities.getComparatorResult (/config/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:128:39)
    at /config/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/get-entities/controller.js:114:47
    at Array.reduce (<anonymous>)
    at GetEntities.onInput (/config/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/get-entities/controller.js:108:52)
[07:37:23] INFO: Service Node-RED exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[07:37:24] INFO: Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
```

## Steps to reproduce

Set up Inject > Get Entities > Debug 
Inject adds a roominfo.heating.target_set_back which contains the name of an input_number helper. 
Get entities node matches on entity_id and msg.roominfo.heating.target_set_back

Deploy and trigger the inject node, nothing shows in the NR debug log, NR shows ERROR 502 whilst NR reloads

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Your issue is with the `node-red-contrib-home-assistant-websocket` node, please reach out these.

Please note there have been some challenges seen recently in users manually updating nodes without checking version constraints.
