### ISSUE TITLE
cannot install any pattern 

### ISSUE THREAD

**Issue by tamerhamdyelsayed** [hassio-addons/addon-node-red#1992]
# Problem/Motivation
try to install any pattern it get fail

> (Why the issue was filed)

-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 18.1.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (amd64 / qemux86-64)
 Home Assistant Core: 2024.11.1
 Home Assistant Supervisor: 2024.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nginx successfully started
npm notice
npm notice New minor version of npm available! 10.7.0 -> 10.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
npm notice To update run: npm install -g npm@10.9.0
npm notice
npm error code ENOTEMPTY
npm error syscall rename
npm error path /config/node_modules/@napi-rs/wasm-runtime
npm error dest /config/node_modules/@napi-rs/.wasm-runtime-VbRjXh94
npm error errno -39
npm error ENOTEMPTY: directory not empty, rename '/config/node_modules/@napi-rs/wasm-runtime' -> '/config/node_modules/@napi-rs/.wasm-runtime-VbRjXh94'
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-11-09T07_51_03_802Z-debug-0.log
[09:52:14] WARNING: Failed un-installing conflicting packages
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[09:52:16] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js
9 Nov 09:53:22 - [info] 
Welcome to Node-RED
===================
9 Nov 09:53:22 - [info] Node-RED version: v4.0.3
9 Nov 09:53:22 - [info] Node.js  version: v18.20.4
9 Nov 09:53:22 - [info] Linux 6.6.54-haos x64 LE
9 Nov 09:53:23 - [info] Loading palette nodes
9 Nov 09:53:37 - [info] Node-RED Contrib Theme Collection version: v4.0.11
9 Nov 09:56:34 - [info] Dashboard version 3.6.5 started at /endpoint/ui
(node:467) [DEP0128] DeprecationWarning: Invalid 'main' field in '/config/node_modules/javascript-opentimestamps/package.json' of 'open-timestamps.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
9 Nov 09:56:41 - [info] node-red-contrib-home-assistant-websocket v0.74.2 nodes initialized
9 Nov 09:56:43 - [info] Settings file  : /etc/node-red/config.js
9 Nov 09:56:43 - [info] Context store  : 'default' [module=localfilesystem]
9 Nov 09:56:43 - [info] User directory : /config/
9 Nov 09:56:43 - [warn] Projects disabled : editorTheme.projects.enabled=false
9 Nov 09:56:43 - [info] Flows file     : /config/flows.json
9 Nov 09:56:44 - [info] Server now running at http://127.0.0.1:46836/
9 Nov 09:56:44 - [info] Starting flows
[09:56:44] INFO: Starting NGinx...
9 Nov 09:56:44 - [info] Started flows
9 Nov 09:56:44 - [info] [alexa-remote-account:Amazon Alexa Account] intialising "Amazon Alexa Account" with the PROXY method and saved data...
9 Nov 09:56:46 - [error] [api-call-service:f63039ebbc30b0f2] NoConnectionError
9 Nov 09:56:49 - [info] [server:Home Assistant] Connecting to http://supervisor/core
9 Nov 09:56:49 - [info] [server:Home Assistant] Connected to http://supervisor/core
9 Nov 09:56:58 - [warn] [ha-time:fdef503ec86916ae] Date is in the past: 2024-11-09T02:46:00+00:00
9 Nov 13:29:29 - [info] Stopping modified nodes
9 Nov 13:29:29 - [info] Stopped modified nodes
9 Nov 13:29:29 - [info] Updated flows
9 Nov 13:29:29 - [info] Starting modified nodes
9 Nov 13:29:29 - [info] Started modified nodes
9 Nov 13:30:29 - [info] Stopping modified nodes
9 Nov 13:30:29 - [info] Stopped modified nodes
9 Nov 13:30:29 - [info] Updated flows
9 Nov 13:30:29 - [info] Starting modified nodes
9 Nov 13:30:29 - [info] Started modified nodes
9 Nov 13:31:06 - [info] Stopping modified nodes
9 Nov 13:31:06 - [info] Stopped modified nodes
9 Nov 13:31:06 - [info] Updated flows
9 Nov 13:31:06 - [info] Starting modified nodes
9 Nov 13:31:06 - [info] Started modified nodes
9 Nov 13:32:12 - [info] Stopping modified nodes
9 Nov 13:32:12 - [info] Stopped modified nodes
9 Nov 13:32:12 - [info] Updated flows
9 Nov 13:32:12 - [info] Starting modified nodes
9 Nov 13:32:12 - [info] Started modified nodes
9 Nov 13:32:35 - [info] Stopping modified nodes
9 Nov 13:32:35 - [info] Stopped modified nodes
9 Nov 13:32:35 - [info] Updated flows
9 Nov 13:32:35 - [info] Starting modified nodes
9 Nov 13:32:35 - [info] Started modified nodes
9 Nov 14:41:40 - [warn] [ha-time:14cd56fbe0d4d20e] Date is in the past: 2024-11-09T12:40:00+00:00
9 Nov 14:41:46 - [error] [ha-time:fdef503ec86916ae] ConfigError: Unavailable
9 Nov 14:41:46 - [error] [ha-time:508de79ca8e0c6bf] ConfigError: Unavailable
9 Nov 14:41:46 - [error] [ha-time:14cd56fbe0d4d20e] ConfigError: Unavailable
9 Nov 14:41:46 - [error] [ha-time:b5c2371103776879] ConfigError: Unavailable
9 Nov 14:41:46 - [error] [ha-time:6376af91be596228] ConfigError: Unavailable
9 Nov 14:41:46 - [warn] [ha-time:fdef503ec86916ae] Date is in the past: 2024-11-09T02:46:00+00:00
9 Nov 14:41:46 - [warn] [ha-time:508de79ca8e0c6bf] Date is in the past: 2024-11-09T09:39:00+00:00
9 Nov 14:41:46 - [warn] [ha-time:14cd56fbe0d4d20e] Date is in the past: 2024-11-09T12:40:00+00:00
9 Nov 17:03:49 - [error] [alexa-home-conf:b5eed9c024009d80] Error: read ECONNRESET
9 Nov 20:05:48 - [info] Installing module: @technithusiast/node-red-contrib-ai-intent, version: 2.1.2
9 Nov 20:06:28 - [warn] Installation of module @technithusiast/node-red-contrib-ai-intent failed:
9 Nov 20:06:28 - [warn] ------------------------------------------
9 Nov 20:06:28 - [warn] npm error code ENOTEMPTY
npm error syscall rename
npm error path /config/node_modules/@napi-rs/wasm-runtime
npm error dest /config/node_modules/@napi-rs/.wasm-runtime-VbRjXh94
npm error errno -39
npm error ENOTEMPTY: directory not empty, rename '/config/node_modules/@napi-rs/wasm-runtime' -> '/config/node_modules/@napi-rs/.wasm-runtime-VbRjXh94'
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-11-09T18_05_52_858Z-debug-0.log
9 Nov 20:06:28 - [warn] ------------------------------------------
Error: Install failed
    at /opt/node_modules/@node-red/registry/lib/installer.js:290:25
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
9 Nov 20:06:28 - [error] Error: Install failed
9 Nov 20:14:53 - [info] Installing module: @technithusiast/node-red-contrib-ai-intent, version: 2.1.2
9 Nov 20:15:09 - [warn] Installation of module @technithusiast/node-red-contrib-ai-intent failed:
9 Nov 20:15:09 - [warn] ------------------------------------------
9 Nov 20:15:09 - [warn] npm error code ENOTEMPTY
npm error syscall rename
npm error path /config/node_modules/@napi-rs/wasm-runtime
npm error dest /config/node_modules/@napi-rs/.wasm-runtime-VbRjXh94
npm error errno -39
npm error ENOTEMPTY: directory not empty, rename '/config/node_modules/@napi-rs/wasm-runtime' -> '/config/node_modules/@napi-rs/.wasm-runtime-VbRjXh94'
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-11-09T18_14_53_705Z-debug-0.log
9 Nov 20:15:09 - [warn] ------------------------------------------
Error: Install failed
    at /opt/node_modules/@node-red/registry/lib/installer.js:290:25
9 Nov 20:15:09 - [error] Error: Install failed
9 Nov 20:29:22 - [error] [alexa-home-conf:b5eed9c024009d80] Error: read ECONNRESET

## Expected behavior

> pattern install success 

## Actual behavior

> cannot install any pattern

## Steps to reproduce

> open pattern and try to install any

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by tamerhamdyelsayed** [comment]
i found the solution bt removing '/config/node_modules/@napi-rs/.wasm-runtime-VbRjXh94'
