### ISSUE TITLE
Node-Red UI has connectivity/update issues with latest 3.x update

### ISSUE THREAD

**Issue by hanssep** [hassio-addons/addon-node-red#209]
# Problem/Motivation

After 3.0.x upgrade Node-Red is not working with Safari 12.1.1 and freshping.io anymore. Node-Red shows "Lost Connection to server" pop-up, doesn't show debug messages in debug pane. Uptime monitoring via Freshping.io has also stopped working. This despite all NR flows working as expected. When logging in via Firefox NR UI behaves as expected. Access is direct via port 1880.

## Expected behavior

No connect popup, debug messages show in debug pane, freshping shows nr as up. NR _is_ up and flows work as expected.

## Actual behavior

I see 401 errors in the NR log in HASS:

[23/Apr/2019:08:23:46 -0700] 401 -(192.168.0.149) GET /comms HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15)

AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15)
[23/Apr/2019:08:24:48 -0700] 401 52.42.49.200(192.168.0.3) GET / HTTP/1.1 (FreshpingBot/1.0 (+https://freshping.io/))

## Steps to reproduce

Upgrade to latest HA. latest NR plugin.

**Comment by frenck** [comment]
Please provide the actual start log output

**Comment by hanssep** [comment]
```
Supervisor version: 160
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 

> bufferutil@1.2.1 install /config/node-red/node_modules/bufferutil
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 3.16.0-7-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /config/node-red/node_modules/bufferutil
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> utf-8-validate@1.2.2 install /config/node-red/node_modules/utf-8-validate
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 3.16.0-7-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /config/node-red/node_modules/utf-8-validate
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules/utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 804 packages in 5.245s
found 16 vulnerabilities (2 low, 11 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:24:55] INFO: Starting Node-RED...

> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"

23 Apr 12:24:57 - [info] 

Welcome to Node-RED
===================

23 Apr 12:24:57 - [info] Node-RED version: v0.20.5
23 Apr 12:24:57 - [info] Node.js  version: v10.14.2
23 Apr 12:24:57 - [info] Linux 3.16.0-7-amd64 x64 LE
23 Apr 12:24:57 - [info] Loading palette nodes
23 Apr 12:24:59 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
23 Apr 12:24:59 - [info] Settings file  : /etc/node-red/config.js
23 Apr 12:24:59 - [info] Context store  : 'default' [module=memory]
23 Apr 12:24:59 - [info] User directory : /config/node-red/
23 Apr 12:24:59 - [warn] Projects disabled : editorTheme.projects.enabled=false
23 Apr 12:24:59 - [info] Flows file     : /config/node-red/flows.json
23 Apr 12:24:59 - [info] Server now running at http://127.0.0.1:46836/
23 Apr 12:25:00 - [info] Starting flows
23 Apr 12:25:00 - [info] Started flows
[12:25:00] INFO: Starting NGinx...
23 Apr 12:25:00 - [info] [mqtt-broker:463e2e08.11437] Connected to broker: mqtt://192.168.0.50:1883
23 Apr 12:25:00 - [info] [debug:3942762a.f15272] ok
23 Apr 12:25:00 - [info] [debug:3942762a.f15272] ok
23 Apr 12:25:01 - [info] [debug:3942762a.f15272] ok
23 Apr 12:25:01 - [info] [debug:3942762a.f15272] ok
23 Apr 12:25:01 - [info] [debug:3942762a.f15272] ok
23 Apr 12:25:01 - [info] [debug:3942762a.f15272] ok
23 Apr 12:25:05 - [info] [server:Home Assistant] WebSocket Connected to http://hassio/homeassistant
```

**Comment by andrewjfreyer** [comment]
Same issue here.

**Comment by frenck** [comment]
Freshping gets a 401....
Which means it is not allowed to access Node-RE, which makes sense.
Does it authenticate?

**Comment by frenck** [comment]
The latest update has non-authenticated/native authenticated endpoints available.
