### ISSUE TITLE
Installation of node failed. maybe because of serial port changes?

### ISSUE THREAD

**Issue by schluden** [hassio-addons/addon-node-red#233]
# Problem/Motivation

I can not install node-red-contrib-smartmeter 0.2.1
everything is up to date right now. node red add-on 3.1.1 
home assistant 0.93.2

## Expected behavior

just a normal installation of the node

## Actual behavior

message: install failed with logs:

```
2019-05-30T20:19:21.583Z installieren : node-red-contrib-smartmeter 0.2.1

2019-05-30T20:19:22.087Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-smartmeter@0.2.1
2019-05-30T20:20:21.087Z [out] 
2019-05-30T20:20:21.087Z [out] > serialport@6.2.2 install /config/node-red/node_modules/serialport
2019-05-30T20:20:21.087Z [out] > prebuild-install || node-gyp rebuild
2019-05-30T20:20:21.087Z [out] 
2019-05-30T20:20:27.966Z [err] prebuild-install
2019-05-30T20:20:27.967Z [err]  
2019-05-30T20:20:27.968Z [err] WARN
2019-05-30T20:20:27.969Z [err]  
2019-05-30T20:20:27.970Z [err] install
2019-05-30T20:20:27.971Z [err]  No prebuilt binaries found (target=10.14.2 runtime=node arch=arm platform=linux)
2019-05-30T20:20:33.887Z [err] gyp
2019-05-30T20:20:33.890Z [err]  
2019-05-30T20:20:33.890Z [err] ERR! 
2019-05-30T20:20:33.891Z [err] build error 
2019-05-30T20:20:33.895Z [err] gyp
2019-05-30T20:20:33.896Z [err]  ERR! stack
2019-05-30T20:20:33.897Z [err]  Error: not found: make
2019-05-30T20:20:33.897Z [err] gyp
2019-05-30T20:20:33.897Z [err]  ERR! 
2019-05-30T20:20:33.897Z [err] stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2019-05-30T20:20:33.897Z [err] gyp
2019-05-30T20:20:33.898Z [err]  ERR!
2019-05-30T20:20:33.898Z [err]  stack
2019-05-30T20:20:33.898Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2019-05-30T20:20:33.898Z [err] gyp 
2019-05-30T20:20:33.899Z [err] ERR! stack
2019-05-30T20:20:33.899Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2019-05-30T20:20:33.899Z [err] gyp
2019-05-30T20:20:33.899Z [err]  ERR!
2019-05-30T20:20:33.900Z [err]  stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2019-05-30T20:20:33.900Z [err] gyp 
2019-05-30T20:20:33.900Z [err] ERR! 
2019-05-30T20:20:33.901Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2019-05-30T20:20:33.901Z [err] gyp
2019-05-30T20:20:33.901Z [err]  ERR!
2019-05-30T20:20:33.901Z [err]  stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2019-05-30T20:20:33.902Z [err] gyp 
2019-05-30T20:20:33.902Z [err] ERR! stack
2019-05-30T20:20:33.902Z [err]      at FSReqWrap.oncomplete (fs.js:154:21)
2019-05-30T20:20:33.904Z [err] gyp
2019-05-30T20:20:33.905Z [err]  ERR! System
2019-05-30T20:20:33.905Z [err]  Linux 4.14.66-v7
2019-05-30T20:20:33.906Z [err] gyp
2019-05-30T20:20:33.906Z [err]  ERR!
2019-05-30T20:20:33.907Z [err]  command
2019-05-30T20:20:33.907Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-05-30T20:20:33.908Z [err] gyp
2019-05-30T20:20:33.908Z [err]  ERR! 
2019-05-30T20:20:33.908Z [err] cwd /config/node-red/node_modules/serialport
2019-05-30T20:20:33.909Z [err] gyp
2019-05-30T20:20:33.909Z [err]  ERR!
2019-05-30T20:20:33.910Z [err]  node -v v10.14.2
2019-05-30T20:20:33.910Z [err] gyp
2019-05-30T20:20:33.910Z [err]  ERR!
2019-05-30T20:20:33.911Z [err]  node-gyp -v
2019-05-30T20:20:33.911Z [err]  v3.8.0
2019-05-30T20:20:33.912Z [err] gyp 
2019-05-30T20:20:33.912Z [err] ERR! not ok
2019-05-30T20:20:33.912Z [err]  
2019-05-30T20:20:37.130Z [err] npm
2019-05-30T20:20:37.132Z [err]  
2019-05-30T20:20:37.132Z [err] ERR! code ELIFECYCLE
2019-05-30T20:20:37.134Z [err] npm
2019-05-30T20:20:37.135Z [err]  ERR! errno
2019-05-30T20:20:37.135Z [err]  1
2019-05-30T20:20:37.149Z [err] npm
2019-05-30T20:20:37.149Z [err]  ERR! serialport@6.2.2 install: `prebuild-install || node-gyp rebuild`
2019-05-30T20:20:37.149Z [err] npm
2019-05-30T20:20:37.150Z [err]  ERR! Exit status 1
2019-05-30T20:20:37.151Z [err] npm
2019-05-30T20:20:37.152Z [err]  ERR!
2019-05-30T20:20:37.152Z [err]  
2019-05-30T20:20:37.152Z [err] npm ERR!
2019-05-30T20:20:37.153Z [err]  Failed at the serialport@6.2.2 install script.
2019-05-30T20:20:37.153Z [err] npm
2019-05-30T20:20:37.153Z [err]  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-05-30T20:20:37.485Z [err] 
2019-05-30T20:20:37.487Z [err] npm
2019-05-30T20:20:37.488Z [err]  
2019-05-30T20:20:37.489Z [err] ERR!
2019-05-30T20:20:37.490Z [err]  A complete log of this run can be found in:
2019-05-30T20:20:37.491Z [err] npm
2019-05-30T20:20:37.491Z [err]  
2019-05-30T20:20:37.492Z [err] ERR!
2019-05-30T20:20:37.493Z [err]      /root/.npm/_logs/2019-05-30T20_20_37_399Z-debug.log
2019-05-30T20:20:37.579Z rc=1
```

## Steps to reproduce

installing the node

**Comment by frenck** [comment]
You are installing a custom node. It apparently relies on serialport@6.2.2.
Since this add-on does not ship with that old of a version, it tries to build it manually, which fails because of missing dependencies.

Please be sure to install the required build tools and dependencies using the `system_packages` add-on config
