### ISSUE TITLE
can't update Node-RED Addon

### ISSUE THREAD

**Issue by niccolobusato** [hassio-addons/addon-node-red#306]
# Problem/Motivation

I'm stuck on v.3.1.4 if i try to upgrade after 20minutes my HA goes offline and i need to restart everything.

## Expected behavior

> (What you expected to happen)

## Actual behavior

I'm stuck on v.3.1.4 if i try to upgrade after 20minutes my HA goes offline and i need to restart everything. 

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

i need to restore an older version (3.1.4 actually works)

**Comment by sinclairpaul** [comment]
Can you post the supervisor logs please?

**Comment by niccolobusato** [comment]
no error in the home-assistant.log

where should i look into?

**Comment by sinclairpaul** [comment]
Hass.io/System/System Log

Also please confirm your version of HA.

**Comment by ragde22** [comment]
I am in the same problem!!!!
4.2.0, said I am ready for update, click on update button and just stop the addon and nothing happens, just stay stopped and I have to start it. Over and over as many time I try, same!!

**Comment by ragde22** [comment]
The log I have is this:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 4.2.0
 There is an update available for this add-on!
 Latest add-on version: 4.2.1
 Please consider upgrading as soon as possible.
 System: HassOS 2.12  (armv7 / raspberrypi3)
 Home Assistant version: 0.100.1
 Supervisor version: 189
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
[17:25:29] INFO: Password is NOT in the Have I Been Pwned database! Nice!
patching file nodes/ui_base.html
Hunk #1 succeeded at 1243 (offset 712 lines).
audited 3 packages in 1.052s
found 0 vulnerabilities
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:25:34] INFO: Starting Node-RED...
> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
13 Oct 17:25:38 - [info] 
Welcome to Node-RED
===================
13 Oct 17:25:38 - [info] Node-RED version: v0.20.8
13 Oct 17:25:38 - [info] Node.js  version: v10.16.3
13 Oct 17:25:38 - [info] Linux 4.14.98-v7 arm LE
13 Oct 17:25:40 - [info] Loading palette nodes
13 Oct 17:25:45 - [info] Dashboard version 2.16.3 started at /endpoint/ui
13 Oct 17:25:47 - [info] Settings file  : /etc/node-red/config.js
13 Oct 17:25:47 - [info] Context store  : 'default' [module=memory]
13 Oct 17:25:47 - [info] User directory : /config/node-red/
13 Oct 17:25:47 - [warn] Projects disabled : editorTheme.projects.enabled=false
13 Oct 17:25:47 - [info] Flows file     : /config/node-red/flows.json
13 Oct 17:25:47 - [info] Server now running at http://127.0.0.1:46836/
13 Oct 17:25:47 - [info] Starting flows
[17:25:47] INFO: Starting NGinx...
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
13 Oct 17:25:47 - [info] Started flows
13 Oct 17:25:49 - [info] [mqtt-broker:fd4bc19c.ca7d4] Connected to broker: nodered_client@mqtt://10.0.0.150:1883
13 Oct 17:25:52 - [info] [server:Home Assistant] WebSocket Connected to http://hassio/homeassistant

**Comment by sinclairpaul** [comment]
Without the supervisor log, there really is nothing that can be looked at.  I doubt the issues are related.

**Comment by ragde22** [comment]
Hass.io supervisor
Ver: 189

System log

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 147, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 39, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/addons/__init__.py", line 205, in update
    await addon.instance.cleanup()
  File "/usr/src/hassio/hassio/utils/__init__.py", line 29, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/hassio/hassio/docker/interface.py", line 320, in _cleanup
    for image in self.sys_docker.images.list(name=self.image):
  File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 363, in list
    return [self.get(r["Id"]) for r in resp]
  File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 363, in <listcomp>
    return [self.get(r["Id"]) for r in resp]
  File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 316, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/image.py", line 245, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")
19-10-14 00:25:09 INFO (SyncWorker_2) [hassio.docker.interface] Update image hassioaddons/node-red-armv7:4.2.1 to hassioaddons/node-red-armv7:4.2.1
19-10-14 00:25:09 INFO (SyncWorker_2) [hassio.docker.interface] Pull image hassioaddons/node-red-armv7 tag 4.2.1.
19-10-14 00:25:10 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.39/images/sha256:6446459bc255fc64a1b0ab8aeed77b65ab821fde6d4e636864705ad5b5251639/json
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 147, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 39, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/addons/__init__.py", line 205, in update
    await addon.instance.cleanup()
  File "/usr/src/hassio/hassio/utils/__init__.py", line 29, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/hassio/hassio/docker/interface.py", line 320, in _cleanup
    for image in self.sys_docker.images.list(name=self.image):
  File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 363, in list
    return [self.get(r["Id"]) for r in resp]
  File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 363, in <listcomp>
    return [self.get(r["Id"]) for r in resp]
  File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 316, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/image.py", line 245, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")
19-10-14 00:25:21 INFO (SyncWorker_0) [hassio.docker.addon] Start Docker add-on hassioaddons/node-red-armv7 with version 4.2.0
19-10-14 00:25:23 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_nodered
19-10-14 00:25:27 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_nodered
19-10-14 00:25:48 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for ragde22
19-10-14 00:25:49 INFO (MainThread) [hassio.auth] Success login from ragde22
19-10-14 00:25:52 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-10-14 00:25:52 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-10-14 00:25:52 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request running
19-10-14 00:33:41 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/hassio-addons/repository repository
19-10-14 00:33:41 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
19-10-14 00:33:41 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/hassio-addons/repository-edge repository
19-10-14 00:33:41 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/esphome/hassio repository
19-10-14 00:33:41 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
19-10-14 00:33:42 INFO (MainThread) [hassio.store] Load add-ons from store: 109 all - 0 new - 0 remove

**Comment by sinclairpaul** [comment]
@ragde22 Your issue is related to docker, you can attempt to run `hassio supervisor repair` from a console.  If not you would need to seek help with Hassio itself not the addon.
