### ISSUE TITLE
Doesnt start after upgrade.

### ISSUE THREAD

**Issue by supersonical** [hassio-addons/addon-node-red#325]
# Problem/Motivation

Doesnt start, loops below log

## Actual behavior

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: ce54052
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.3 LTS  (amd64 / qemux86-64)
 Home Assistant version: 0.99.3
 Supervisor version: 189

[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1243 (offset 712 lines).
[18:09:36] WARNING: 
[18:09:36] WARNING: Direct access mode is disabled, Node-RED Dashboard
[18:09:36] WARNING: will not work!
[18:09:36] WARNING: 
[18:09:36] WARNING: Please assign a port in the Network section of this
[18:09:36] WARNING: add-on configuration.
[18:09:36] WARNING: 
up to date in 0.58s
found 0 vulnerabilities

[cont-init.d] node-red.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:09:39] INFO: Starting Node-RED...

> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"

Failed to start server:
Error: Cannot find module './examples'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.init (/opt/node_modules/@node-red/runtime/lib/library/index.js:28:31)
    at Object.init (/opt/node_modules/@node-red/runtime/lib/index.js:80:13)
    at Object.init (/opt/node_modules/node-red/lib/red.js:70:21)
    at Object.<anonymous> (/opt/node_modules/node-red/red.js:197:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio-addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hassio-addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-03T16_09_40_973Z-debug.log
[18:09:41] INFO: Starting Node-RED...

> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"

Failed to start server:
Error: Cannot find module './examples'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.init (/opt/node_modules/@node-red/runtime/lib/library/index.js:28:31)
    at Object.init (/opt/node_modules/@node-red/runtime/lib/index.js:80:13)
    at Object.init (/opt/node_modules/node-red/lib/red.js:70:21)
    at Object.<anonymous> (/opt/node_modules/node-red/red.js:197:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio-addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hassio-addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by supersonical** [comment]
Please close the issue, resolved it. :)

**Comment by bonanitech** [comment]
> Please close the issue, resolved it. :)

How did you solve the issue? How about creating a pull request with the fix? 😉
