### ISSUE TITLE
no working websocket connection to HA

### ISSUE THREAD

**Issue by tarbax** [hassio-addons/addon-node-red#340]
how do i fix this issue ?
i got this after doing a recovery from a backup (ssd failed!)

node red log:
`[server:Home Assistant TARBAX] WebSocket Connected to http://hassio/homeassistant`
settings
![image](https://user-images.githubusercontent.com/34491557/66862214-c28f2180-ef90-11e9-8983-03c37a4153b6.png)

Hassio log:
```
19-10-15 19:09:58 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-10-15 19:09:58 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-10-15 19:09:58 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 111, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/proxy.py", line 203, in websocket
    client = await self._websocket_client()
  File "/usr/src/hassio/hassio/api/proxy.py", line 114, in _websocket_client
    url, heartbeat=30, verify_ssl=False
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 738, in _ws_connect
    headers=resp.headers)
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='http://172.30.32.1:8123/api/websocket
```
i discovered that i have 2 hassio system users:
![image](https://user-images.githubusercontent.com/34491557/66862771-e3a44200-ef91-11e9-9e22-dc55ae440314.png)

**Comment by sinclairpaul** [comment]
Please check to see if you have an ip_bans.yaml in your configuration folder, and remove it if it exists.

**Comment by sinclairpaul** [comment]
Will assume as there is no update on Discord or here that this resolved your issue.
