### ISSUE TITLE
I can not install node-red-contrib-opcua

### ISSUE THREAD

**Issue by maslovmike** [hassio-addons/addon-node-red#363]
Raspberry Pi 3 B+
Raspbian buster
Hassio 0.101.3
Docker 19.03.4
Hass.io Add-ons: Node-RED Release 5.03

----------------------------------------------------------
2019-11-10T00:47:17.905Z Install : node-red-contrib-opcua 0.2.49

2019-11-10T00:47:16.941Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-opcua@0.2.49
2019-11-10T00:48:37.080Z [out] 
2019-11-10T00:48:37.080Z [out] > deasync@0.1.15 install /config/node-red/node_modules/deasync
2019-11-10T00:48:37.080Z [out] > node ./build.js
2019-11-10T00:48:37.080Z [out] 
2019-11-10T00:48:47.746Z [err] gyp
2019-11-10T00:48:47.747Z [err]  
2019-11-10T00:48:47.747Z [err] ERR! build error 
2019-11-10T00:48:47.749Z [err] gyp
2019-11-10T00:48:47.750Z [err]  ERR! stack Error: not found: make
2019-11-10T00:48:47.750Z [err] gyp ERR! 
2019-11-10T00:48:47.750Z [err] stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2019-11-10T00:48:47.750Z [err] gyp
2019-11-10T00:48:47.750Z [err]  ERR! 
2019-11-10T00:48:47.750Z [err] stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2019-11-10T00:48:47.750Z [err] gyp
2019-11-10T00:48:47.751Z [err]  ERR! 
2019-11-10T00:48:47.751Z [err] stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2019-11-10T00:48:47.751Z [err] gyp ERR!
2019-11-10T00:48:47.751Z [err]  stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2019-11-10T00:48:47.751Z [err] gyp ERR!
2019-11-10T00:48:47.751Z [err]  stack
2019-11-10T00:48:47.751Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2019-11-10T00:48:47.751Z [err] gyp 
2019-11-10T00:48:47.752Z [err] ERR! stack
2019-11-10T00:48:47.752Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2019-11-10T00:48:47.752Z [err] gyp 
2019-11-10T00:48:47.752Z [err] ERR! stack
2019-11-10T00:48:47.752Z [err]      at FSReqWrap.oncomplete (fs.js:153:21)
2019-11-10T00:48:47.753Z [err] gyp
2019-11-10T00:48:47.753Z [err]  ERR! System Linux 4.19.75-v7+
2019-11-10T00:48:47.754Z [err] gyp
2019-11-10T00:48:47.754Z [err]  ERR! 
2019-11-10T00:48:47.754Z [err] command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-11-10T00:48:47.754Z [err] gyp
2019-11-10T00:48:47.754Z [err]  ERR! 
2019-11-10T00:48:47.755Z [err] cwd /config/node-red/node_modules/deasync
2019-11-10T00:48:47.755Z [err] gyp 
2019-11-10T00:48:47.755Z [err] ERR! node -v
2019-11-10T00:48:47.755Z [err]  v10.16.3
2019-11-10T00:48:47.755Z [err] gyp
2019-11-10T00:48:47.755Z [err]  ERR! 
2019-11-10T00:48:47.755Z [err] node-gyp -v v3.8.0
2019-11-10T00:48:47.755Z [err] gyp 
2019-11-10T00:48:47.756Z [err] ERR! not ok
2019-11-10T00:48:47.756Z [err]  
2019-11-10T00:48:47.773Z [err] Build failed
2019-11-10T00:48:49.174Z [err] npm
2019-11-10T00:48:49.174Z [err]  
2019-11-10T00:48:49.175Z [err] ERR!
2019-11-10T00:48:49.175Z [err]  
2019-11-10T00:48:49.175Z [err] code
2019-11-10T00:48:49.175Z [err]  ELIFECYCLE
2019-11-10T00:48:49.177Z [err] npm
2019-11-10T00:48:49.177Z [err]  
2019-11-10T00:48:49.177Z [err] ERR!
2019-11-10T00:48:49.178Z [err]  
2019-11-10T00:48:49.178Z [err] errno
2019-11-10T00:48:49.178Z [err]  1
2019-11-10T00:48:49.183Z [err] npm
2019-11-10T00:48:49.184Z [err]  
2019-11-10T00:48:49.184Z [err] ERR!
2019-11-10T00:48:49.185Z [err]  deasync@0.1.15 install: `node ./build.js`
2019-11-10T00:48:49.185Z [err] npm
2019-11-10T00:48:49.185Z [err]  
2019-11-10T00:48:49.185Z [err] ERR!
2019-11-10T00:48:49.186Z [err]  Exit status 1
2019-11-10T00:48:49.186Z [err] npm
2019-11-10T00:48:49.187Z [err]  
2019-11-10T00:48:49.187Z [err] ERR!
2019-11-10T00:48:49.187Z [err]  
2019-11-10T00:48:49.188Z [err] npm
2019-11-10T00:48:49.188Z [err]  
2019-11-10T00:48:49.188Z [err] ERR!
2019-11-10T00:48:49.189Z [err]  Failed at the deasync@0.1.15 install script.
2019-11-10T00:48:49.189Z [err] npm
2019-11-10T00:48:49.189Z [err]  
2019-11-10T00:48:49.189Z [err] ERR!
2019-11-10T00:48:49.190Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2019-11-10T00:48:49.396Z [err] 
2019-11-10T00:48:49.397Z [err] npm
2019-11-10T00:48:49.397Z [err]  
2019-11-10T00:48:49.397Z [err] ERR!
2019-11-10T00:48:49.397Z [err]  A complete log of this run can be found in:
2019-11-10T00:48:49.398Z [err] npm
2019-11-10T00:48:49.398Z [err]  
2019-11-10T00:48:49.399Z [err] ERR!
2019-11-10T00:48:49.399Z [err]      /root/.npm/_logs/2019-11-10T00_48_49_295Z-debug.log
2019-11-10T00:48:49.440Z rc=1

**Comment by tjorim** [comment]
`2019-11-10T00:48:47.750Z [err] ERR! stack Error: not found: make`
**make** is missing, install it.

**Comment by maslovmike** [comment]
Did this:

mike@raspberrypi:~ $ sudo -s
[sudo] password for mike:
root@raspberrypi:/home/mike# apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Hit:3 https://download.docker.com/linux/raspbian buster InRelease
Reading package lists... Done
root@raspberrypi:/home/mike# apt-get install build-essential
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.6).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@raspberrypi:/home/mike# mike@raspberrypi:~

the error persists.
Help!

**Comment by sinclairpaul** [comment]
You need to put it in the `  "system_packages": [
    "xxxxx"
  ],` config for the addon, the Readme gives more details.

**Comment by maslovmike** [comment]
{
  "credential_secret": "KJHhfdhiFRENCKfsdfdsDHFHDJS",
  "dark_mode": false,
  "http_node": {
    "username": "mike",
    "password": "maslovmike"
  },
  "http_static": {
    "username": "mike",
    "password": "maslovmike"
  },
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": false,
  **"system_packages": [
    "make"
  ],**
  "npm_packages": [],
  "init_commands": []
}

SAVE GONFIG
RESTART NODE-RED
INSTALL NODES

-----------------------------------------------------------
2019-11-10T15:15:59.430Z Install : node-red-contrib-opcua 0.2.49

2019-11-10T15:15:59.564Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-opcua@0.2.49
2019-11-10T15:16:55.975Z [out] 
2019-11-10T15:16:55.975Z [out] > deasync@0.1.15 install /config/node-red/node_modules/deasync
2019-11-10T15:16:55.975Z [out] > node ./build.js
2019-11-10T15:16:55.975Z [out] 
2019-11-10T15:17:06.264Z [out] make: Entering directory '/config/node-red/node_modules/deasync/build'
2019-11-10T15:17:06.266Z [out]   CXX(target) Release/obj.target/deasync/src/deasync.o
2019-11-10T15:17:06.272Z [err] make: g++: Command not found
2019-11-10T15:17:06.272Z [err] make: *** [deasync.target.mk:97: Release/obj.target/deasync/src/deasync.o] Error 127
2019-11-10T15:17:06.272Z [out] make: Leaving directory '/config/node-red/node_modules/deasync/build'
2019-11-10T15:17:06.278Z [err] gyp
2019-11-10T15:17:06.279Z [err]  
2019-11-10T15:17:06.280Z [err] ERR! build error 
2019-11-10T15:17:06.282Z [err] gyp
2019-11-10T15:17:06.282Z [err]  ERR! stack
2019-11-10T15:17:06.282Z [err]  Error: `make` failed with exit code: 2
2019-11-10T15:17:06.282Z [err] gyp ERR! 
2019-11-10T15:17:06.282Z [err] stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
2019-11-10T15:17:06.282Z [err] gyp
2019-11-10T15:17:06.283Z [err]  ERR! 
2019-11-10T15:17:06.283Z [err] stack     at ChildProcess.emit (events.js:198:13)
2019-11-10T15:17:06.283Z [err] gyp
2019-11-10T15:17:06.283Z [err]  ERR! 
2019-11-10T15:17:06.283Z [err] stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
2019-11-10T15:17:06.284Z [err] gyp
2019-11-10T15:17:06.284Z [err]  ERR! System Linux 4.19.75-v7+
2019-11-10T15:17:06.285Z [err] gyp
2019-11-10T15:17:06.285Z [err]  ERR! command
2019-11-10T15:17:06.286Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-11-10T15:17:06.286Z [err] gyp
2019-11-10T15:17:06.286Z [err]  ERR! 
2019-11-10T15:17:06.286Z [err] cwd /config/node-red/node_modules/deasync
2019-11-10T15:17:06.286Z [err] gyp ERR!
2019-11-10T15:17:06.286Z [err]  node -v v10.16.3
2019-11-10T15:17:06.286Z [err] gyp 
2019-11-10T15:17:06.287Z [err] ERR! node-gyp -v
2019-11-10T15:17:06.287Z [err]  v3.8.0
2019-11-10T15:17:06.287Z [err] gyp ERR!
2019-11-10T15:17:06.287Z [err]  not ok 
2019-11-10T15:17:06.303Z [err] Build failed
2019-11-10T15:17:07.613Z [err] npm
2019-11-10T15:17:07.614Z [err]  ERR! code ELIFECYCLE
2019-11-10T15:17:07.614Z [err] npm
2019-11-10T15:17:07.615Z [err]  ERR! errno 1
2019-11-10T15:17:07.620Z [err] npm
2019-11-10T15:17:07.620Z [err]  ERR! deasync@0.1.15 install: `node ./build.js`
2019-11-10T15:17:07.620Z [err] npm ERR! Exit status 1
2019-11-10T15:17:07.620Z [err] npm
2019-11-10T15:17:07.620Z [err]  ERR! 
2019-11-10T15:17:07.620Z [err] npm
2019-11-10T15:17:07.621Z [err]  ERR! Failed at the deasync@0.1.15 install script.
2019-11-10T15:17:07.621Z [err] npm 
2019-11-10T15:17:07.621Z [err] ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-11-10T15:17:07.918Z [err] 
2019-11-10T15:17:07.919Z [err] npm ERR! A complete log of this run can be found in:
2019-11-10T15:17:07.919Z [err] npm ERR!     /root/.npm/_logs/2019-11-10T15_17_07_719Z-debug.log
2019-11-10T15:17:07.949Z rc=1

**Comment by sinclairpaul** [comment]
gcc is now missing, you will probably be better off just installing build-base

When I add the nodes via Manage Pallette in the app, I do not see these issues.
