### ISSUE TITLE
Modbus Read node stopped working

### ISSUE THREAD

**Issue by PierreScerri** [hassio-addons/addon-node-red#386]
# Problem/Motivation
Modbus Read Node has stopped working
> (Why the issue was filed)

## Expected behavior
Continue working as it has been 
> (What you expected to happen)

## Actual behavior
Modbus Read node throwing continuous FSM Reset on State error.  This is part of the log where the error starts:

```
[08:58:52] INFO: Starting NGinx...
6 Dec 08:58:52 - [info] Started flows
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
6 Dec 08:58:55 - [info] [mqtt-broker:c28a2dad.22663] Connected to broker: mqtt://192.168.1.200:1883
6 Dec 08:58:57 - [info] [server:Home Assistant] WebSocket Connected to http://hassio/homeassistant
6 Dec 08:59:05 - [error] [modbus-read:SDM 230 Voltage] Timed out
6 Dec 08:59:05 - [warn] [modbus-read:SDM 230 Voltage] FSM Reset On State [object Object]
6 Dec 08:59:05 - [warn] [modbus-read:SDM 230 Current] FSM Reset On State [object Object]
6 Dec 08:59:05 - [warn] [modbus-read:SDM 230 Power] FSM Reset On State [object Object]
6 Dec 08:59:05 - [warn] [modbus-read:SDM 230 Energy Imp] FSM Reset On State [object Object]
6 Dec 08:59:05 - [warn] [modbus-read:SDM 230 Energy Exp] FSM Reset On State [object Object]
6 Dec 08:59:05 - [warn] [modbus-read:SDM 120 Voltage] FSM Reset On State [object Object]
6 Dec 08:59:05 - [warn] [modbus-read:SDM 120 Current] FSM Reset On State [object Object]
6 Dec 08:59:05 - [warn] [modbus-read:SDM 120 Power] FSM Reset On State [object Object]
6 Dec 08:59:05 - [warn] [modbus-read:SDM 120 Energy Sol] FSM Reset On State [object Object]
6 Dec 08:59:05 - [error] [modbus-read:SDM 120 Voltage] Timed out
> (What actually happened)

```
## Steps to reproduce
Did it all by itself
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Please include some version information, I have no idea what I am looking at right now.

**Comment by PierreScerri** [comment]
Sorry:

```
Add-on version: 5.0.4
 You are running the latest version of this add-on.
 System: HassOS 2.12  (armv7 / raspberrypi3)
 Home Assistant version: 0.102.2
 Supervisor version: 192
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1243 (offset 712 lines).
audited 200 packages in 7.77s
found 0 vulnerabilities
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:58:34] INFO: Starting Node-RED...
> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
6 Dec 08:58:38 - [info] 
Welcome to Node-RED
===================
6 Dec 08:58:39 - [info] Node-RED version: v1.0.3
6 Dec 08:58:39 - [info] Node.js  version: v10.16.3
6 Dec 08:58:39 - [info] Linux 4.14.98-v7 arm LE
6 Dec 08:58:40 - [info] Loading palette nodes
6 Dec 08:58:49 - [info] Dashboard version 2.14.0 started at /endpoint/ui
6 Dec 08:58:52 - [info] Settings file  : /etc/node-red/config.js
6 Dec 08:58:52 - [info] Context store  : 'default' [module=memory]
6 Dec 08:58:52 - [info] User directory : /config/node-red/
6 Dec 08:58:52 - [warn] Projects disabled : editorTheme.projects.enabled=false
6 Dec 08:58:52 - [info] Flows file     : /config/node-red/flows.json
6 Dec 08:58:52 - [info] Server now running at http://127.0.0.1:46836/
6 Dec 08:58:52 - [info] Starting flows
```

**Comment by sinclairpaul** [comment]
I see you found your way to the repo for this module and they appear to have fixed your issue.  Closing this out.

**Comment by PierreScerri** [comment]
Not yet

**Comment by sinclairpaul** [comment]
As its package update, you can either wait for the next addon release where it will be updated, or add the following to your config.
`  "system_packages": [
    "make",
    "g++",
    "gcc",
    "linux-headers"
  ],
  "npm_packages": [
    "node-red-contrib-modbus@5.2.0"
  ],`

**Comment by frenck** [comment]
New version of the add-on is estimated to land within 24 hours.

**Comment by PierreScerri** [comment]
Ah OK.  Thanks.  Hope it fixes the issue.

**Comment by PierreScerri** [comment]
Followed @sinclairpaul's suggestion.

Update now available in Node-Red but stops with:


```
-----------------------------------------------------------
2019-12-08T20:16:22.638Z Install : node-red-contrib-modbus 5.2.0

2019-12-08T20:16:22.713Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-modbus@5.2.0
2019-12-08T20:16:49.757Z [out] 
2019-12-08T20:16:49.757Z [out] > @serialport/bindings@8.0.4 install /config/node-red/node_modules/@serialport/bindings
2019-12-08T20:16:49.757Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2019-12-08T20:16:49.757Z [out] 
2019-12-08T20:16:52.159Z [err] prebuild-install
2019-12-08T20:16:52.160Z [err]  WARN install No prebuilt binaries found (target=10.16.3 runtime=node arch=arm libc=musl platform=linux)
2019-12-08T20:17:05.481Z [err] gyp
2019-12-08T20:17:05.483Z [err]  
2019-12-08T20:17:05.483Z [err] ERR! build error
2019-12-08T20:17:05.484Z [err]  
2019-12-08T20:17:05.486Z [err] gyp
2019-12-08T20:17:05.487Z [err]  ERR! 
2019-12-08T20:17:05.487Z [err] stack Error: not found: make
2019-12-08T20:17:05.487Z [err] gyp
2019-12-08T20:17:05.487Z [err]  ERR! 
2019-12-08T20:17:05.487Z [err] stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2019-12-08T20:17:05.487Z [err] gyp ERR!
2019-12-08T20:17:05.487Z [err]  stack
2019-12-08T20:17:05.488Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2019-12-08T20:17:05.488Z [err] gyp
2019-12-08T20:17:05.488Z [err]  ERR! 
2019-12-08T20:17:05.488Z [err] stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2019-12-08T20:17:05.488Z [err] gyp 
2019-12-08T20:17:05.488Z [err] ERR! stack
2019-12-08T20:17:05.488Z [err]      at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2019-12-08T20:17:05.488Z [err] gyp
2019-12-08T20:17:05.489Z [err]  ERR! 
2019-12-08T20:17:05.489Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2019-12-08T20:17:05.489Z [err] gyp ERR!
2019-12-08T20:17:05.489Z [err]  
2019-12-08T20:17:05.489Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2019-12-08T20:17:05.489Z [err] gyp
2019-12-08T20:17:05.489Z [err]  ERR!
2019-12-08T20:17:05.490Z [err]  stack     at FSReqWrap.oncomplete (fs.js:153:21)
2019-12-08T20:17:05.491Z [err] gyp
2019-12-08T20:17:05.491Z [err]  ERR! System
2019-12-08T20:17:05.491Z [err]  Linux 4.14.98-v7
2019-12-08T20:17:05.492Z [err] gyp
2019-12-08T20:17:05.492Z [err]  ERR! 
2019-12-08T20:17:05.492Z [err] command
2019-12-08T20:17:05.492Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-12-08T20:17:05.493Z [err] gyp 
2019-12-08T20:17:05.493Z [err] ERR! 
2019-12-08T20:17:05.493Z [err] cwd /config/node-red/node_modules/@serialport/bindings
2019-12-08T20:17:05.493Z [err] gyp
2019-12-08T20:17:05.493Z [err]  ERR!
2019-12-08T20:17:05.493Z [err]  node -v v10.16.3
2019-12-08T20:17:05.494Z [err] gyp
2019-12-08T20:17:05.494Z [err]  ERR!
2019-12-08T20:17:05.494Z [err]  node-gyp -v v3.8.0
2019-12-08T20:17:05.494Z [err] gyp
2019-12-08T20:17:05.494Z [err]  
2019-12-08T20:17:05.494Z [err] ERR! not ok
2019-12-08T20:17:05.495Z [err]  
2019-12-08T20:17:05.534Z [out] 
2019-12-08T20:17:05.534Z [out] > @serialport/bindings@2.0.8 install /config/node-red/node_modules/modbus-serial/node_modules/@serialport/bindings
2019-12-08T20:17:05.534Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2019-12-08T20:17:05.534Z [out] 
2019-12-08T20:17:07.864Z [err] prebuild-install
2019-12-08T20:17:07.864Z [err]  WARN install
2019-12-08T20:17:07.864Z [err]  No prebuilt binaries found (target=10.16.3 runtime=node arch=arm libc=musl platform=linux)
2019-12-08T20:17:10.912Z [err] gyp
2019-12-08T20:17:10.913Z [err]  
2019-12-08T20:17:10.913Z [err] ERR! 
2019-12-08T20:17:10.914Z [err] build error 
2019-12-08T20:17:10.916Z [err] gyp
2019-12-08T20:17:10.916Z [err]  ERR! stack
2019-12-08T20:17:10.917Z [err]  Error: not found: make
2019-12-08T20:17:10.917Z [err] gyp 
2019-12-08T20:17:10.917Z [err] ERR! stack
2019-12-08T20:17:10.917Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2019-12-08T20:17:10.917Z [err] gyp
2019-12-08T20:17:10.917Z [err]  ERR! 
2019-12-08T20:17:10.917Z [err] stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2019-12-08T20:17:10.918Z [err] gyp ERR!
2019-12-08T20:17:10.918Z [err]  stack
2019-12-08T20:17:10.918Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2019-12-08T20:17:10.918Z [err] gyp 
2019-12-08T20:17:10.918Z [err] ERR! 
2019-12-08T20:17:10.918Z [err] stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2019-12-08T20:17:10.918Z [err] gyp
2019-12-08T20:17:10.918Z [err]  ERR!
2019-12-08T20:17:10.919Z [err]  stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2019-12-08T20:17:10.919Z [err] gyp 
2019-12-08T20:17:10.919Z [err] ERR! 
2019-12-08T20:17:10.919Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2019-12-08T20:17:10.919Z [err] gyp
2019-12-08T20:17:10.919Z [err]  ERR!
2019-12-08T20:17:10.919Z [err]  stack     at FSReqWrap.oncomplete (fs.js:153:21)
2019-12-08T20:17:10.920Z [err] gyp
2019-12-08T20:17:10.921Z [err]  ERR! System Linux 4.14.98-v7
2019-12-08T20:17:10.921Z [err] gyp
2019-12-08T20:17:10.922Z [err]  ERR! command
2019-12-08T20:17:10.922Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-12-08T20:17:10.922Z [err] gyp
2019-12-08T20:17:10.922Z [err]  ERR! 
2019-12-08T20:17:10.922Z [err] cwd /config/node-red/node_modules/modbus-serial/node_modules/@serialport/bindings
2019-12-08T20:17:10.922Z [err] gyp
2019-12-08T20:17:10.923Z [err]  ERR! 
2019-12-08T20:17:10.923Z [err] node -v v10.16.3
2019-12-08T20:17:10.923Z [err] gyp 
2019-12-08T20:17:10.923Z [err] ERR! 
2019-12-08T20:17:10.923Z [err] node-gyp -v v3.8.0
2019-12-08T20:17:10.923Z [err] gyp
2019-12-08T20:17:10.924Z [err]  ERR!
2019-12-08T20:17:10.924Z [err]  not ok 
2019-12-08T20:17:11.830Z [err] npm
2019-12-08T20:17:11.831Z [err]  WARN optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@8.0.4 (node_modules/@serialport/bindings):
2019-12-08T20:17:11.831Z [err] npm WARN
2019-12-08T20:17:11.831Z [err]  optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@8.0.4 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2019-12-08T20:17:11.831Z [err] npm
2019-12-08T20:17:11.831Z [err]  WARN optional
2019-12-08T20:17:11.832Z [err]  SKIPPING OPTIONAL DEPENDENCY: Exit status 1
2019-12-08T20:17:11.833Z [err] 
2019-12-08T20:17:11.841Z [err] npm
2019-12-08T20:17:11.841Z [err]  ERR! code ELIFECYCLE
2019-12-08T20:17:11.842Z [err] npm
2019-12-08T20:17:11.842Z [err]  ERR! errno 1
2019-12-08T20:17:11.843Z [err] npm
2019-12-08T20:17:11.843Z [err]  ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2019-12-08T20:17:11.843Z [err] npm ERR!
2019-12-08T20:17:11.843Z [err]  Exit status 1
2019-12-08T20:17:11.844Z [err] npm
2019-12-08T20:17:11.844Z [err]  ERR! 
2019-12-08T20:17:11.844Z [err] npm ERR!
2019-12-08T20:17:11.844Z [err]  Failed at the @serialport/bindings@2.0.8 install script.
2019-12-08T20:17:11.844Z [err] npm ERR!
2019-12-08T20:17:11.845Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2019-12-08T20:17:12.409Z [err] 
2019-12-08T20:17:12.411Z [err] npm
2019-12-08T20:17:12.412Z [err]  
2019-12-08T20:17:12.412Z [err] ERR!
2019-12-08T20:17:12.413Z [err]  A complete log of this run can be found in:
2019-12-08T20:17:12.414Z [err] npm
2019-12-08T20:17:12.414Z [err]  
2019-12-08T20:17:12.415Z [err] ERR!
2019-12-08T20:17:12.415Z [err]      /root/.npm/_logs/2019-12-08T20_17_11_915Z-debug.log
2019-12-08T20:17:12.448Z rc=1

-----------------------------------------------------------
2019-12-08T20:18:53.947Z Install : node-red-contrib-modbus 5.2.0

2019-12-08T20:18:54.011Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-modbus@5.2.0
2019-12-08T20:19:11.959Z [out] 
2019-12-08T20:19:11.959Z [out] > @serialport/bindings@8.0.4 install /config/node-red/node_modules/@serialport/bindings
2019-12-08T20:19:11.959Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2019-12-08T20:19:11.959Z [out] 
2019-12-08T20:19:13.961Z [err] prebuild-install
2019-12-08T20:19:13.962Z [err]  WARN install
2019-12-08T20:19:13.962Z [err]  No prebuilt binaries found (target=10.16.3 runtime=node arch=arm libc=musl platform=linux)
2019-12-08T20:19:17.058Z [err] gyp
2019-12-08T20:19:17.060Z [err]  
2019-12-08T20:19:17.060Z [err] ERR! build error
2019-12-08T20:19:17.060Z [err]  
2019-12-08T20:19:17.062Z [err] gyp
2019-12-08T20:19:17.063Z [err]  ERR! stack
2019-12-08T20:19:17.063Z [err]  Error: not found: make
2019-12-08T20:19:17.063Z [err] gyp ERR!
2019-12-08T20:19:17.063Z [err]  stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2019-12-08T20:19:17.063Z [err] gyp ERR!
2019-12-08T20:19:17.064Z [err]  stack
2019-12-08T20:19:17.064Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2019-12-08T20:19:17.064Z [err] gyp 
2019-12-08T20:19:17.064Z [err] ERR! 
2019-12-08T20:19:17.064Z [err] stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2019-12-08T20:19:17.064Z [err] gyp
2019-12-08T20:19:17.064Z [err]  ERR! 
2019-12-08T20:19:17.064Z [err] stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2019-12-08T20:19:17.064Z [err] gyp
2019-12-08T20:19:17.065Z [err]  ERR! 
2019-12-08T20:19:17.065Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2019-12-08T20:19:17.065Z [err] gyp ERR!
2019-12-08T20:19:17.065Z [err]  stack
2019-12-08T20:19:17.067Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2019-12-08T20:19:17.068Z [err] gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
2019-12-08T20:19:17.069Z [err] gyp
2019-12-08T20:19:17.069Z [err]  ERR! System Linux 4.14.98-v7
2019-12-08T20:19:17.070Z [err] gyp
2019-12-08T20:19:17.070Z [err]  ERR! 
2019-12-08T20:19:17.070Z [err] command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-12-08T20:19:17.070Z [err] gyp ERR!
2019-12-08T20:19:17.071Z [err]  cwd
2019-12-08T20:19:17.071Z [err]  /config/node-red/node_modules/@serialport/bindings
2019-12-08T20:19:17.071Z [err] gyp
2019-12-08T20:19:17.071Z [err]  ERR! 
2019-12-08T20:19:17.071Z [err] node -v v10.16.3
2019-12-08T20:19:17.071Z [err] gyp ERR!
2019-12-08T20:19:17.072Z [err]  node-gyp -v
2019-12-08T20:19:17.072Z [err]  v3.8.0
2019-12-08T20:19:17.072Z [err] gyp
2019-12-08T20:19:17.072Z [err]  ERR! 
2019-12-08T20:19:17.072Z [err] not ok 
2019-12-08T20:19:17.113Z [out] 
2019-12-08T20:19:17.113Z [out] > @serialport/bindings@2.0.8 install /config/node-red/node_modules/modbus-serial/node_modules/@serialport/bindings
2019-12-08T20:19:17.113Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2019-12-08T20:19:17.113Z [out] 
2019-12-08T20:19:19.714Z [err] prebuild-install
2019-12-08T20:19:19.715Z [err]  WARN install No prebuilt binaries found (target=10.16.3 runtime=node arch=arm libc=musl platform=linux)
2019-12-08T20:19:22.738Z [err] gyp
2019-12-08T20:19:22.739Z [err]  
2019-12-08T20:19:22.740Z [err] ERR! build error
2019-12-08T20:19:22.740Z [err]  
2019-12-08T20:19:22.742Z [err] gyp
2019-12-08T20:19:22.743Z [err]  ERR! stack
2019-12-08T20:19:22.743Z [err]  Error: not found: make
2019-12-08T20:19:22.743Z [err] gyp ERR!
2019-12-08T20:19:22.743Z [err]  stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2019-12-08T20:19:22.743Z [err] gyp ERR!
2019-12-08T20:19:22.743Z [err]  stack
2019-12-08T20:19:22.744Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2019-12-08T20:19:22.744Z [err] gyp 
2019-12-08T20:19:22.744Z [err] ERR! 
2019-12-08T20:19:22.744Z [err] stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2019-12-08T20:19:22.744Z [err] gyp
2019-12-08T20:19:22.744Z [err]  ERR! 
2019-12-08T20:19:22.744Z [err] stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2019-12-08T20:19:22.744Z [err] gyp
2019-12-08T20:19:22.744Z [err]  ERR! 
2019-12-08T20:19:22.745Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2019-12-08T20:19:22.745Z [err] gyp 
2019-12-08T20:19:22.745Z [err] ERR! stack
2019-12-08T20:19:22.745Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2019-12-08T20:19:22.745Z [err] gyp ERR!
2019-12-08T20:19:22.745Z [err]  stack     at FSReqWrap.oncomplete (fs.js:153:21)
2019-12-08T20:19:22.747Z [err] gyp
2019-12-08T20:19:22.747Z [err]  ERR! System Linux 4.14.98-v7
2019-12-08T20:19:22.748Z [err] gyp
2019-12-08T20:19:22.748Z [err]  ERR! command
2019-12-08T20:19:22.748Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-12-08T20:19:22.748Z [err] gyp ERR!
2019-12-08T20:19:22.748Z [err]  cwd
2019-12-08T20:19:22.749Z [err]  /config/node-red/node_modules/modbus-serial/node_modules/@serialport/bindings
2019-12-08T20:19:22.749Z [err] gyp ERR!
2019-12-08T20:19:22.749Z [err]  node -v v10.16.3
2019-12-08T20:19:22.749Z [err] gyp 
2019-12-08T20:19:22.749Z [err] ERR! node-gyp -v
2019-12-08T20:19:22.749Z [err]  v3.8.0
2019-12-08T20:19:22.750Z [err] gyp 
2019-12-08T20:19:22.750Z [err] ERR! 
2019-12-08T20:19:22.750Z [err] not ok 
2019-12-08T20:19:27.461Z [err] npm
2019-12-08T20:19:27.461Z [err]  WARN optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@8.0.4 (node_modules/@serialport/bindings):
2019-12-08T20:19:27.462Z [err] npm WARN 
2019-12-08T20:19:27.462Z [err] optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@8.0.4 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2019-12-08T20:19:27.462Z [err] npm 
2019-12-08T20:19:27.462Z [err] WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
2019-12-08T20:19:27.463Z [err] 
2019-12-08T20:19:27.471Z [err] npm 
2019-12-08T20:19:27.471Z [err] ERR! code ELIFECYCLE
2019-12-08T20:19:27.471Z [err] npm
2019-12-08T20:19:27.472Z [err]  ERR! errno 1
2019-12-08T20:19:27.472Z [err] npm
2019-12-08T20:19:27.473Z [err]  ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2019-12-08T20:19:27.473Z [err] npm ERR!
2019-12-08T20:19:27.473Z [err]  Exit status 1
2019-12-08T20:19:27.474Z [err] npm
2019-12-08T20:19:27.474Z [err]  ERR! 
2019-12-08T20:19:27.474Z [err] npm
2019-12-08T20:19:27.474Z [err]  ERR! Failed at the @serialport/bindings@2.0.8 install script.
2019-12-08T20:19:27.474Z [err] npm
2019-12-08T20:19:27.474Z [err]  ERR!
2019-12-08T20:19:27.474Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2019-12-08T20:19:27.657Z [err] 
2019-12-08T20:19:27.658Z [err] npm
2019-12-08T20:19:27.659Z [err]  
2019-12-08T20:19:27.660Z [err] ERR!
2019-12-08T20:19:27.661Z [err]  A complete log of this run can be found in:
2019-12-08T20:19:27.661Z [err] npm
2019-12-08T20:19:27.662Z [err]  
2019-12-08T20:19:27.662Z [err] ERR!
2019-12-08T20:19:27.663Z [err]      /root/.npm/_logs/2019-12-08T20_19_27_525Z-debug.log
2019-12-08T20:19:27.697Z rc=1
```

Also screwed up MQTT connection.

**Comment by sinclairpaul** [comment]
Wait for the new addon build I may have missed a build dependency.

**Comment by PierreScerri** [comment]
I will.  Thanks

**Comment by PierreScerri** [comment]
Update works.  Only thing is that output frequency has slowed down from 10s to 90s as shown in the first image.  I have not changed any settings except that I've checked 'Reconnect on timeout' as previously instructed.

![Screen Shot 2019-12-09 at 21 18 49](https://user-images.githubusercontent.com/34303331/70469575-904dfc00-1ac9-11ea-90a5-ff8ad29bc1db.png)
![Screen Shot 2019-12-09 at 21 14 04](https://user-images.githubusercontent.com/34303331/70469588-980da080-1ac9-11ea-9faf-9808478668d0.png)
![Screen Shot 2019-12-09 at 21 14 41](https://user-images.githubusercontent.com/34303331/70469591-9b089100-1ac9-11ea-9612-a64a4815ad8b.png)

**Comment by sinclairpaul** [comment]
This would be out of scope for the addon itself (as it essentially packages the software up), you would need to address any queries specific to the node at the source repo (where you logged your issue previously).

**Comment by PierreScerri** [comment]
Yes I have just realised that. Thank you for your help.
