### ISSUE TITLE
6.0.3 Boot loop on Pi

### ISSUE THREAD

**Issue by jamestutton** [hassio-addons/addon-node-red#433]
# Problem/Motivation

Since upgrading to 6.0.3 Node Red will not start on Pi3

## Expected behavior

Should load and stay up

## Actual behavior
Boot loop with below message then container eventaully stops.

[12:36:56] INFO: Starting Node-RED...
> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
30 Jan 12:37:02 - [error] Failed to start server:
30 Jan 12:37:02 - [error] /opt/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/git/index.js:2
    "config": {
            ^
SyntaxError: Unexpected token ':'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/index.js:25:16)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)

## Steps to reproduce

Seems to be a happening on upgrade and clean install of component inside my enviroment (Arm Pi3).  Have even uninstalled and deleted the config/node-red folder to elminated that as issue.

Guessing possibly an issue with arm as also have hass.io x64 based VM and runs fine in that.

Reverted to 6.0.2 image via portaniner for now and that seems fine

**Comment by jamestutton** [comment]
Not sure on route cause but think it must be located to something local as stripped things back and seem to have managed to get in running again.  Sorry
