### ISSUE TITLE
Installation of node-red-contrib-mysensors fails due to missing make tools

### ISSUE THREAD

**Issue by rikki78** [hassio-addons/addon-node-red#446]
# Problem/Motivation

It is not possible to install node-red-contrib-mysensors, or better node-red-node-sqlite as that fails
I've searched around and also post the issue on the forum, but no replies yet. I hope you can help as the installation is stuck now.

## Expected behavior

The installation should finish without errors

## Actual behavior

```
2020-02-07T19:17:27.440Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-mysensors@3.3.1
2020-02-07T19:17:47.550Z [out] 
2020-02-07T19:17:47.550Z [out] > sqlite3@4.1.1 install /config/node-red/node_modules/sqlite3
2020-02-07T19:17:47.550Z [out] > node-pre-gyp install --fallback-to-build
2020-02-07T19:17:47.550Z [out] 
2020-02-07T19:17:49.866Z [err] node-pre-gyp
2020-02-07T19:17:49.869Z [err]  
2020-02-07T19:17:49.869Z [err] WARN 
2020-02-07T19:17:49.870Z [err] Using request for node-pre-gyp https download 
2020-02-07T19:17:51.001Z [err] node-pre-gyp
2020-02-07T19:17:51.002Z [err]  WARN
2020-02-07T19:17:51.002Z [err]  
2020-02-07T19:17:51.003Z [err] Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/node-v72-linux-arm.tar.gz
2020-02-07T19:17:51.003Z [err]  
2020-02-07T19:17:51.004Z [err] node-pre-gyp
2020-02-07T19:17:51.004Z [err]  WARN
2020-02-07T19:17:51.005Z [err]  Pre-built binaries not found for sqlite3@4.1.1 and node@12.14.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp)
2020-02-07T19:17:51.006Z [err]  
2020-02-07T19:17:56.207Z [err] gyp
2020-02-07T19:17:56.210Z [err]  
2020-02-07T19:17:56.210Z [err] ERR! 
2020-02-07T19:17:56.210Z [err] build error 
2020-02-07T19:17:56.213Z [err] gyp
2020-02-07T19:17:56.214Z [err]  ERR!
2020-02-07T19:17:56.214Z [err]  
2020-02-07T19:17:56.214Z [err] stack
2020-02-07T19:17:56.214Z [err]  Error: not found: make
2020-02-07T19:17:56.214Z [err] gyp
2020-02-07T19:17:56.215Z [err]  
2020-02-07T19:17:56.215Z [err] ERR! 
2020-02-07T19:17:56.216Z [err] stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-02-07T19:17:56.216Z [err] gyp ERR! stack
2020-02-07T19:17:56.217Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-02-07T19:17:56.217Z [err] gyp ERR!
2020-02-07T19:17:56.217Z [err]  stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-02-07T19:17:56.217Z [err] gyp 
2020-02-07T19:17:56.218Z [err] ERR! 
2020-02-07T19:17:56.218Z [err] stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-02-07T19:17:56.218Z [err] gyp
2020-02-07T19:17:56.218Z [err]  ERR!
2020-02-07T19:17:56.219Z [err]  stack
2020-02-07T19:17:56.219Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-02-07T19:17:56.219Z [err] gyp
2020-02-07T19:17:56.219Z [err]  ERR!
2020-02-07T19:17:56.219Z [err]  stack
2020-02-07T19:17:56.220Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-02-07T19:17:56.220Z [err] gyp
2020-02-07T19:17:56.220Z [err]  ERR!
2020-02-07T19:17:56.220Z [err]  
2020-02-07T19:17:56.220Z [err] stack     at FSReqCallback.oncomplete (fs.js:158:21)
2020-02-07T19:17:56.221Z [err] gyp
2020-02-07T19:17:56.221Z [err]  ERR! 
2020-02-07T19:17:56.222Z [err] System Linux 4.19.66-v7+
2020-02-07T19:17:56.222Z [err] gyp
2020-02-07T19:17:56.222Z [err]  ERR!
2020-02-07T19:17:56.223Z [err]  command
2020-02-07T19:17:56.223Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
2020-02-07T19:17:56.223Z [err] gyp
2020-02-07T19:17:56.223Z [err]  
2020-02-07T19:17:56.223Z [err] ERR! 
2020-02-07T19:17:56.223Z [err] cwd /config/node-red/node_modules/sqlite3
2020-02-07T19:17:56.224Z [err] gyp
2020-02-07T19:17:56.224Z [err]  ERR!
2020-02-07T19:17:56.224Z [err]  node -v
2020-02-07T19:17:56.224Z [err]  v12.14.0
2020-02-07T19:17:56.224Z [err] gyp
2020-02-07T19:17:56.225Z [err]  ERR!
2020-02-07T19:17:56.225Z [err]  node-gyp -v
2020-02-07T19:17:56.225Z [err]  v5.0.5
2020-02-07T19:17:56.225Z [err] gyp 
2020-02-07T19:17:56.225Z [err] ERR! 
2020-02-07T19:17:56.225Z [err] not ok 
2020-02-07T19:17:56.235Z [err] node-pre-gyp
2020-02-07T19:17:56.235Z [err]  ERR!
2020-02-07T19:17:56.235Z [err]  build error
2020-02-07T19:17:56.235Z [err]  
2020-02-07T19:17:56.238Z [err] node-pre-gyp
2020-02-07T19:17:56.239Z [err]  ERR! 
2020-02-07T19:17:56.239Z [err] stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-02-07T19:17:56.239Z [err] node-pre-gyp 
2020-02-07T19:17:56.240Z [err] ERR!
2020-02-07T19:17:56.245Z [err]  stack     at ChildProcess.<anonymous> (/config/node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2020-02-07T19:17:56.245Z [err] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
2020-02-07T19:17:56.245Z [err] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
2020-02-07T19:17:56.245Z [err] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
2020-02-07T19:17:56.245Z [err] node-pre-gyp ERR! System
2020-02-07T19:17:56.247Z [err]  Linux 4.19.66-v7+
2020-02-07T19:17:56.247Z [err] node-pre-gyp ERR! command "/usr/bin/node" "/config/node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2020-02-07T19:17:56.247Z [err] node-pre-gyp ERR! cwd /config/node-red/node_modules/sqlite3
2020-02-07T19:17:56.247Z [err] node-pre-gyp 
2020-02-07T19:17:56.248Z [err] ERR! node -v v12.14.0
2020-02-07T19:17:56.248Z [err] node-pre-gyp
2020-02-07T19:17:56.248Z [err]  ERR! 
2020-02-07T19:17:56.249Z [err] node-pre-gyp -v v0.11.0
2020-02-07T19:17:56.249Z [err] node-pre-gyp
2020-02-07T19:17:56.249Z [err]  ERR! 
2020-02-07T19:17:56.249Z [err] not ok 
2020-02-07T19:17:56.252Z [out] Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-02-07T19:17:57.481Z [err] npm
2020-02-07T19:17:57.481Z [err]  ERR! code ELIFECYCLE
2020-02-07T19:17:57.482Z [err] npm
2020-02-07T19:17:57.482Z [err]  ERR! 
2020-02-07T19:17:57.482Z [err] errno 1
2020-02-07T19:17:57.487Z [err] npm
2020-02-07T19:17:57.488Z [err]  ERR! sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
2020-02-07T19:17:57.488Z [err] npm
2020-02-07T19:17:57.488Z [err]  ERR!
2020-02-07T19:17:57.488Z [err]  Exit status 1
2020-02-07T19:17:57.488Z [err] npm ERR!
2020-02-07T19:17:57.489Z [err]  
2020-02-07T19:17:57.489Z [err] npm
2020-02-07T19:17:57.489Z [err]  ERR!
2020-02-07T19:17:57.489Z [err]  Failed at the sqlite3@4.1.1 install script.
2020-02-07T19:17:57.489Z [err] npm ERR!
2020-02-07T19:17:57.489Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2020-02-07T19:17:57.568Z [err] 
2020-02-07T19:17:57.569Z [err] npm ERR! A complete log of this run can be found in:
2020-02-07T19:17:57.569Z [err] npm
2020-02-07T19:17:57.569Z [err]  ERR!     /root/.npm/_logs/2020-02-07T19_17_57_530Z-debug.log
2020-02-07T19:17:57.591Z rc=1
```

## Steps to reproduce

install node-red-contrib-mysensors from the pallette, or node-red-node-sqlite 

## Proposed changes

I've tried to install node-red-node-sqlite manually, but that isn't possible as there is no make tool (see error logs). If that would be available, the installation can just finish
Any other suggestions to solve this are welcome!

**Comment by sinclairpaul** [comment]
You can add packages in the config.

https://github.com/hassio-addons/addon-node-red#option-system_packages

See #434 #431 and probably a few others 😉
