### ISSUE TITLE
Error installing NPM package 

### ISSUE THREAD

**Issue by ravenfz** [hassio-addons/addon-node-red#508]
# Problem/Motivation

Tried to install a new node to access sqlite DB through "Manage Palette" > Install > Search: node-red-node-sqlite > Click Install

Failed to install (log bellow).

Tried to do it from within the node red container using `npm install node-red-node-sqlite` and the behaviour was the same.

Tried to install other packages (sqlite3 for instance) and the error is similar.

## Expected behavior

Should have been installed successfully.

## Actual behavior

Error installing.

Log:

````
-----------------------------------------------------------
2020-03-21T16:52:08.391Z Install : node-red-node-sqlite 0.4.2

2020-03-21T16:52:08.465Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-node-sqlite@0.4.2
2020-03-21T16:52:13.324Z [err] npm
2020-03-21T16:52:13.324Z [err]  WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2020-03-21T16:52:30.617Z [out] 
2020-03-21T16:52:30.617Z [out] > sqlite3@4.1.1 install /config/node-red/node_modules/sqlite3
2020-03-21T16:52:30.617Z [out] > node-pre-gyp install --fallback-to-build
2020-03-21T16:52:30.617Z [out] 
2020-03-21T16:52:32.328Z [err] node-pre-gyp
2020-03-21T16:52:32.331Z [err]  
2020-03-21T16:52:32.332Z [err] WARN Using request for node-pre-gyp https download 
2020-03-21T16:52:33.370Z [err] node-pre-gyp
2020-03-21T16:52:33.371Z [err]  WARN
2020-03-21T16:52:33.371Z [err]  
2020-03-21T16:52:33.371Z [err] Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/node-v72-linux-arm.tar.gz 
2020-03-21T16:52:33.372Z [err] node-pre-gyp
2020-03-21T16:52:33.372Z [err]  WARN 
2020-03-21T16:52:33.372Z [err] Pre-built binaries not found for sqlite3@4.1.1 and node@12.15.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp) 
2020-03-21T16:52:37.845Z [err] gyp
2020-03-21T16:52:37.848Z [err]  
2020-03-21T16:52:37.848Z [err] ERR! build error 
2020-03-21T16:52:37.851Z [err] gyp
2020-03-21T16:52:37.851Z [err]  ERR!
2020-03-21T16:52:37.852Z [err]  stack
2020-03-21T16:52:37.852Z [err]  Error: not found: make
2020-03-21T16:52:37.852Z [err] gyp
2020-03-21T16:52:37.852Z [err]  ERR! 
2020-03-21T16:52:37.852Z [err] stack
2020-03-21T16:52:37.852Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-03-21T16:52:37.852Z [err] gyp
2020-03-21T16:52:37.853Z [err]  ERR! 
2020-03-21T16:52:37.853Z [err] stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-03-21T16:52:37.853Z [err] gyp
2020-03-21T16:52:37.853Z [err]  ERR! 
2020-03-21T16:52:37.853Z [err] stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-03-21T16:52:37.854Z [err] gyp ERR! stack
2020-03-21T16:52:37.854Z [err]      at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-03-21T16:52:37.854Z [err] gyp ERR!
2020-03-21T16:52:37.854Z [err]  stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-03-21T16:52:37.854Z [err] gyp
2020-03-21T16:52:37.854Z [err]  ERR! 
2020-03-21T16:52:37.854Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-03-21T16:52:37.855Z [err] gyp ERR!
2020-03-21T16:52:37.855Z [err]  stack     at FSReqCallback.oncomplete (fs.js:158:21)
2020-03-21T16:52:37.856Z [err] gyp
2020-03-21T16:52:37.856Z [err]  ERR! System Linux 4.19.93-v7
2020-03-21T16:52:37.856Z [err] gyp
2020-03-21T16:52:37.856Z [err]  ERR! command
2020-03-21T16:52:37.857Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
2020-03-21T16:52:37.857Z [err] gyp 
2020-03-21T16:52:37.857Z [err] ERR! cwd
2020-03-21T16:52:37.857Z [err]  /config/node-red/node_modules/sqlite3
2020-03-21T16:52:37.857Z [err] gyp
2020-03-21T16:52:37.857Z [err]  ERR! 
2020-03-21T16:52:37.857Z [err] node -v v12.15.0
2020-03-21T16:52:37.858Z [err] gyp ERR!
2020-03-21T16:52:37.858Z [err]  node-gyp -v v5.0.5
2020-03-21T16:52:37.858Z [err] gyp 
2020-03-21T16:52:37.858Z [err] ERR! not ok
2020-03-21T16:52:37.858Z [err]  
2020-03-21T16:52:37.867Z [err] node-pre-gyp
2020-03-21T16:52:37.867Z [err]  ERR! 
2020-03-21T16:52:37.867Z [err] build error 
2020-03-21T16:52:37.870Z [err] node-pre-gyp 
2020-03-21T16:52:37.871Z [err] ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-03-21T16:52:37.871Z [err] node-pre-gyp
2020-03-21T16:52:37.871Z [err]  ERR! stack
2020-03-21T16:52:37.871Z [err]      at ChildProcess.<anonymous> (/config/node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2020-03-21T16:52:37.871Z [err] node-pre-gyp ERR!
2020-03-21T16:52:37.871Z [err]  stack     at ChildProcess.emit (events.js:223:5)
2020-03-21T16:52:37.871Z [err] node-pre-gyp
2020-03-21T16:52:37.871Z [err]  ERR! 
2020-03-21T16:52:37.872Z [err] stack     at maybeClose (internal/child_process.js:1021:16)
2020-03-21T16:52:37.872Z [err] node-pre-gyp
2020-03-21T16:52:37.872Z [err]  ERR!
2020-03-21T16:52:37.872Z [err]  stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
2020-03-21T16:52:37.873Z [err] node-pre-gyp 
2020-03-21T16:52:37.874Z [err] ERR! System Linux 4.19.93-v7
2020-03-21T16:52:37.874Z [err] node-pre-gyp ERR!
2020-03-21T16:52:37.874Z [err]  command "/usr/bin/node" "/config/node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2020-03-21T16:52:37.874Z [err] node-pre-gyp ERR!
2020-03-21T16:52:37.875Z [err]  cwd /config/node-red/node_modules/sqlite3
2020-03-21T16:52:37.875Z [err] node-pre-gyp ERR! 
2020-03-21T16:52:37.875Z [err] node -v v12.15.0
2020-03-21T16:52:37.875Z [err] node-pre-gyp 
2020-03-21T16:52:37.875Z [err] ERR! node-pre-gyp -v
2020-03-21T16:52:37.876Z [err]  v0.11.0
2020-03-21T16:52:37.876Z [err] node-pre-gyp
2020-03-21T16:52:37.876Z [err]  ERR! not ok
2020-03-21T16:52:37.876Z [err]  
2020-03-21T16:52:37.878Z [out] Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-03-21T16:52:39.263Z [err] npm 
2020-03-21T16:52:39.264Z [err] ERR! code ELIFECYCLE
2020-03-21T16:52:39.264Z [err] npm ERR! errno
2020-03-21T16:52:39.265Z [err]  1
2020-03-21T16:52:39.289Z [err] npm 
2020-03-21T16:52:39.290Z [err] ERR! sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
2020-03-21T16:52:39.290Z [err] npm ERR! Exit status 1
2020-03-21T16:52:39.290Z [err] npm ERR!
2020-03-21T16:52:39.290Z [err]  
2020-03-21T16:52:39.290Z [err] npm
2020-03-21T16:52:39.290Z [err]  ERR! Failed at the sqlite3@4.1.1 install script.
2020-03-21T16:52:39.291Z [err] npm ERR!
2020-03-21T16:52:39.291Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2020-03-21T16:52:39.396Z [err] 
2020-03-21T16:52:39.397Z [err] npm ERR!
2020-03-21T16:52:39.397Z [err]  A complete log of this run can be found in:
2020-03-21T16:52:39.397Z [err] npm 
2020-03-21T16:52:39.397Z [err] ERR!     /root/.npm/_logs/2020-03-21T16_52_39_357Z-debug.log
2020-03-21T16:52:39.426Z rc=1
````

## Steps to reproduce

"Manage Palette" > Install > node-red-node-sqlite > Click Install

Setup: RPI3 with HassOS 3.11 and NodeRED 6.1.4 addon.

## Proposed changes

Not sure if its an issue with npm version that makes initial request deprecated failure but the option --fallback-to-build fails as "make" is not installed.

**Comment by frenck** [comment]
> Tried to install a new node to access sqlite DB through "Manage Palette" > Install > Search: node-red-node-sqlite > Click Install

Don't, we provide add-on options for that.


From the logs: `Error: not found: make`

Add the required build pages to the `system_packages` add-on option. Probably you need more than just make; gcc, build-base and possibly some others. Please consult the documentation of that node on the required build tools needed.
