### ISSUE TITLE
Rfxcom-node

### ISSUE THREAD

**Issue by Kouwe-sudo** [hassio-addons/addon-node-red#554]
# Can't add node-red-contrib-rfxcom 

> I'm using Hassio so I don't no how to fix it myself just by logging in as a root or something and add additional stuff like npm. I think this is something for the Add-on builders. The Contrib-rfxcom is very nice to have but with that you can easily control hoods and even some pellet stoves. 
This is the log I get. I hope it's helpful. But I think it's also easy to reproduce. Open Node-red go to 'Manage Palette' and try to install node-red-contrib-rfxcom.

LOG:

-----------------------------------------------------------
2020-05-01T14:46:48.627Z Install : node-red-contrib-rfxcom 2.10.0

2020-05-01T14:46:50.235Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-rfxcom@2.10.0
2020-05-01T14:47:15.839Z [out] 
2020-05-01T14:47:15.839Z [out] > @serialport/bindings@8.0.7 install /config/node-red/node_modules/@serialport/bindings
2020-05-01T14:47:15.839Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2020-05-01T14:47:15.839Z [out] 
2020-05-01T14:47:17.282Z [err] prebuild-install
2020-05-01T14:47:17.283Z [err]  WARN install No prebuilt binaries found (target=12.15.0 runtime=node arch=arm libc=musl platform=linux)
2020-05-01T14:47:20.182Z [err] gyp
2020-05-01T14:47:20.183Z [err]  
2020-05-01T14:47:20.184Z [err] ERR! build error 
2020-05-01T14:47:20.186Z [err] gyp
2020-05-01T14:47:20.187Z [err]  ERR! stack
2020-05-01T14:47:20.187Z [err]  Error: not found: make
2020-05-01T14:47:20.187Z [err] gyp ERR! stack
2020-05-01T14:47:20.187Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-05-01T14:47:20.187Z [err] gyp ERR! 
2020-05-01T14:47:20.188Z [err] stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-05-01T14:47:20.188Z [err] gyp
2020-05-01T14:47:20.188Z [err]  ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-05-01T14:47:20.188Z [err] gyp
2020-05-01T14:47:20.188Z [err]  ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-05-01T14:47:20.189Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-05-01T14:47:20.189Z [err] gyp
2020-05-01T14:47:20.189Z [err]  ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-05-01T14:47:20.189Z [err] gyp
2020-05-01T14:47:20.189Z [err]  ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
2020-05-01T14:47:20.190Z [err] gyp 
2020-05-01T14:47:20.190Z [err] ERR! System Linux 4.19.114-v7
2020-05-01T14:47:20.191Z [err] gyp ERR! 
2020-05-01T14:47:20.191Z [err] command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-05-01T14:47:20.191Z [err] gyp
2020-05-01T14:47:20.191Z [err]  ERR! cwd /config/node-red/node_modules/@serialport/bindings
2020-05-01T14:47:20.191Z [err] gyp 
2020-05-01T14:47:20.191Z [err] ERR! node -v
2020-05-01T14:47:20.192Z [err]  v12.15.0
2020-05-01T14:47:20.192Z [err] gyp ERR!
2020-05-01T14:47:20.192Z [err]  node-gyp -v v5.0.5
2020-05-01T14:47:20.192Z [err] gyp ERR!
2020-05-01T14:47:20.192Z [err]  not ok 
2020-05-01T14:47:21.207Z [err] npm
2020-05-01T14:47:21.208Z [err]  ERR! code ELIFECYCLE
2020-05-01T14:47:21.208Z [err] npm ERR! 
2020-05-01T14:47:21.209Z [err] errno 1
2020-05-01T14:47:21.219Z [err] npm 
2020-05-01T14:47:21.219Z [err] ERR! @serialport/bindings@8.0.7 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2020-05-01T14:47:21.219Z [err] npm ERR! Exit status 1
2020-05-01T14:47:21.219Z [err] npm ERR!
2020-05-01T14:47:21.220Z [err]  
2020-05-01T14:47:21.220Z [err] npm ERR!
2020-05-01T14:47:21.220Z [err]  Failed at the @serialport/bindings@8.0.7 install script.
2020-05-01T14:47:21.220Z [err] npm 
2020-05-01T14:47:21.220Z [err] ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-05-01T14:47:21.326Z [err] 
2020-05-01T14:47:21.327Z [err] npm ERR! A complete log of this run can be found in:
2020-05-01T14:47:21.328Z [err] npm ERR!
2020-05-01T14:47:21.328Z [err]      /root/.npm/_logs/2020-05-01T14_47_21_267Z-debug.log
2020-05-01T14:47:21.359Z rc=1

**Comment by frenck** [comment]
`Error: not found: make`

You need to install the proper system packages using the `system_packages` option that are needed to compile/build/install that node.

**Comment by Kouwe-sudo** [comment]
Can you please be more specific? You talk like I am a pro but if this was so easy I would have figured it out myself. As a hassio-user I assumed that I was not able to adjust the core myself. So how does that work. Even a link will do.
