### ISSUE TITLE
Can't install node-red-contrib-chatbot or @serdoo/node-red-contrib-chatbot

### ISSUE THREAD

**Issue by michas79** [hassio-addons/addon-node-red#566]
# Problem/Motivation

I try to install node-red-contrib-chatbot or @serdoo/node-red-contrib-chatbot  via node-red install page

## Expected behavior

Installation went well and I can use Red-Bot in node-red

## Actual behavior
There where errors during installation:

```
2020-05-19T15:45:08.259Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production @serdoo/node-red-contrib-chatbot@0.18.21
2020-05-19T15:46:49.492Z [err] npm
2020-05-19T15:46:49.494Z [err]  WARN deprecated @types/form-data@2.5.0: This is a stub types definition. form-data provides its own type definitions, so you do not need this installed.
2020-05-19T15:46:50.449Z [err] npm
2020-05-19T15:46:50.450Z [err]  WARN deprecated @types/p-cancelable@1.0.1: This is a stub types definition. p-cancelable provides its own type definitions, so you do not need this installed.
2020-05-19T15:46:50.716Z [err] npm
2020-05-19T15:46:50.718Z [err]  WARN deprecated @types/p-retry@3.0.1: This is a stub types definition. p-retry provides its own type definitions, so you do not need this installed.
2020-05-19T15:49:41.141Z [err] npm
2020-05-19T15:49:41.143Z [err]  WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
2020-05-19T15:49:41.171Z [err] npm
2020-05-19T15:49:41.172Z [err]  WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
2020-05-19T15:49:47.608Z [err] npm 
2020-05-19T15:49:47.612Z [err] WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
2020-05-19T15:50:37.142Z [err] npm
2020-05-19T15:50:37.144Z [err]  WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
2020-05-19T15:51:35.364Z [out] 
2020-05-19T15:51:35.364Z [out] > sqlite3@4.2.0 install /config/node-red/node_modules/sqlite3
2020-05-19T15:51:35.364Z [out] > node-pre-gyp install --fallback-to-build
2020-05-19T15:51:35.364Z [out] 
2020-05-19T15:51:42.205Z [err] node-pre-gyp
2020-05-19T15:51:42.217Z [err]  
2020-05-19T15:51:42.218Z [err] WARN Using request for node-pre-gyp https download 
2020-05-19T15:51:44.086Z [err] node-pre-gyp
2020-05-19T15:51:44.087Z [err]  
2020-05-19T15:51:44.089Z [err] WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v72-linux-arm.tar.gz
2020-05-19T15:51:44.091Z [err]  
2020-05-19T15:51:44.091Z [err] node-pre-gyp 
2020-05-19T15:51:44.092Z [err] WARN Pre-built binaries not found for sqlite3@4.2.0 and node@12.15.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp) 
2020-05-19T15:52:01.923Z [err] gyp
2020-05-19T15:52:01.932Z [err]  
2020-05-19T15:52:01.933Z [err] ERR! build error
2020-05-19T15:52:01.933Z [err]  
2020-05-19T15:52:01.941Z [err] gyp
2020-05-19T15:52:01.941Z [err]  ERR!
2020-05-19T15:52:01.942Z [err]  
2020-05-19T15:52:01.942Z [err] stack
2020-05-19T15:52:01.943Z [err]  Error: not found: make
2020-05-19T15:52:01.943Z [err] gyp
2020-05-19T15:52:01.943Z [err]  ERR! 
2020-05-19T15:52:01.944Z [err] stack
2020-05-19T15:52:01.944Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-05-19T15:52:01.944Z [err] gyp
2020-05-19T15:52:01.945Z [err]  ERR!
2020-05-19T15:52:01.945Z [err]  stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-05-19T15:52:01.946Z [err] gyp
2020-05-19T15:52:01.946Z [err]  ERR! 
2020-05-19T15:52:01.947Z [err] stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-05-19T15:52:01.947Z [err] gyp ERR!
2020-05-19T15:52:01.948Z [err]  stack
2020-05-19T15:52:01.948Z [err]      at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-05-19T15:52:01.948Z [err] gyp
2020-05-19T15:52:01.949Z [err]  ERR! stack
2020-05-19T15:52:01.949Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-05-19T15:52:01.949Z [err] gyp
2020-05-19T15:52:01.950Z [err]  ERR! 
2020-05-19T15:52:01.950Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-05-19T15:52:01.950Z [err] gyp
2020-05-19T15:52:01.951Z [err]  ERR!
2020-05-19T15:52:01.951Z [err]  stack     at FSReqCallback.oncomplete (fs.js:158:21)
2020-05-19T15:52:01.954Z [err] gyp
2020-05-19T15:52:01.954Z [err]  ERR! System Linux 4.19.114-v7
2020-05-19T15:52:01.955Z [err] gyp
2020-05-19T15:52:01.956Z [err]  ERR! command
2020-05-19T15:52:01.957Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
2020-05-19T15:52:01.957Z [err] gyp 
2020-05-19T15:52:01.958Z [err] ERR! cwd
2020-05-19T15:52:01.958Z [err]  /config/node-red/node_modules/sqlite3
2020-05-19T15:52:01.958Z [err] gyp
2020-05-19T15:52:01.959Z [err]  ERR! 
2020-05-19T15:52:01.959Z [err] node -v v12.15.0
2020-05-19T15:52:01.960Z [err] gyp 
2020-05-19T15:52:01.960Z [err] ERR! node-gyp -v v5.0.5
2020-05-19T15:52:01.961Z [err] gyp
2020-05-19T15:52:01.961Z [err]  ERR! 
2020-05-19T15:52:01.962Z [err] not ok 
2020-05-19T15:52:01.983Z [err] node-pre-gyp ERR! 
2020-05-19T15:52:01.985Z [err] build error 
2020-05-19T15:52:01.992Z [err] node-pre-gyp
2020-05-19T15:52:01.992Z [err]  ERR! stack
2020-05-19T15:52:01.993Z [err]  Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-05-19T15:52:01.993Z [err] node-pre-gyp
2020-05-19T15:52:01.993Z [err]  ERR! 
2020-05-19T15:52:01.994Z [err] stack     at ChildProcess.<anonymous> (/config/node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2020-05-19T15:52:01.995Z [err] node-pre-gyp ERR! 
2020-05-19T15:52:01.995Z [err] stack     at ChildProcess.emit (events.js:223:5)
2020-05-19T15:52:01.996Z [err] node-pre-gyp ERR!
2020-05-19T15:52:01.996Z [err]  stack     at maybeClose (internal/child_process.js:1021:16)
2020-05-19T15:52:01.996Z [err] node-pre-gyp 
2020-05-19T15:52:01.997Z [err] ERR! 
2020-05-19T15:52:01.997Z [err] stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
2020-05-19T15:52:02.000Z [err] node-pre-gyp 
2020-05-19T15:52:02.001Z [err] ERR! System Linux 4.19.114-v7
2020-05-19T15:52:02.002Z [err] node-pre-gyp
2020-05-19T15:52:02.003Z [err]  ERR! command
2020-05-19T15:52:02.003Z [err]  "/usr/bin/node" "/config/node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2020-05-19T15:52:02.004Z [err] node-pre-gyp ERR! 
2020-05-19T15:52:02.004Z [err] cwd /config/node-red/node_modules/sqlite3
2020-05-19T15:52:02.005Z [err] node-pre-gyp ERR!
2020-05-19T15:52:02.005Z [err]  node -v v12.15.0
2020-05-19T15:52:02.006Z [err] node-pre-gyp
2020-05-19T15:52:02.006Z [err]  ERR! node-pre-gyp -v
2020-05-19T15:52:02.007Z [err]  v0.11.0
2020-05-19T15:52:02.008Z [err] node-pre-gyp ERR! 
2020-05-19T15:52:02.009Z [err] not ok 
2020-05-19T15:52:02.013Z [out] Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-05-19T15:52:21.681Z [err] npm
2020-05-19T15:52:21.682Z [err]  WARN babel-loader@7.1.5 requires a peer of babel-core@6 but none is installed. You must install peer dependencies yourself.
2020-05-19T15:52:21.683Z [err] npm
2020-05-19T15:52:21.684Z [err]  WARN
2020-05-19T15:52:21.685Z [err]  babel-loader@7.1.5 requires a peer of webpack@2 || 3 || 4 but none is installed. You must install peer dependencies yourself.
2020-05-19T15:52:21.687Z [err] 
2020-05-19T15:52:21.768Z [err] npm
2020-05-19T15:52:21.769Z [err]  ERR! code
2020-05-19T15:52:21.770Z [err]  ELIFECYCLE
2020-05-19T15:52:21.770Z [err] npm
2020-05-19T15:52:21.770Z [err]  ERR! errno
2020-05-19T15:52:21.771Z [err]  1
2020-05-19T15:52:21.773Z [err] npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
2020-05-19T15:52:21.774Z [err] npm ERR!
2020-05-19T15:52:21.774Z [err]  Exit status 1
2020-05-19T15:52:21.774Z [err] npm
2020-05-19T15:52:21.775Z [err]  ERR! 
2020-05-19T15:52:21.775Z [err] npm
2020-05-19T15:52:21.776Z [err]  ERR! Failed at the sqlite3@4.2.0 install script.
2020-05-19T15:52:21.776Z [err] npm
2020-05-19T15:52:21.777Z [err]  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-05-19T15:52:22.349Z [err] 
2020-05-19T15:52:22.351Z [err] npm
2020-05-19T15:52:22.352Z [err]  
2020-05-19T15:52:22.353Z [err] ERR!
2020-05-19T15:52:22.353Z [err]  A complete log of this run can be found in:
2020-05-19T15:52:22.354Z [err] npm
2020-05-19T15:52:22.355Z [err]  
2020-05-19T15:52:22.356Z [err] ERR!     /root/.npm/_logs/2020-05-19T15_52_22_186Z-debug.log
```

**Comment by sinclairpaul** [comment]
You are missing the required system packages, there are quite a few other issues logged in the repo with the same problem.

**Comment by frenck** [comment]
`Error: not found: make`

You need to install the needed system packages to compile that. Please note, that that specific node will not work on ARM-based systems.

**Comment by michas79** [comment]
@frenck 

> Please note, that that specific node will not work on ARM-based systems.

Thats not true. By now this node in Verion 0.9.14 works perfectly fine on my Raspi 2. Could you be a liitle bit more specific please?

A few month ago there was a problem with a library in corralation with discord integration. This should be solved as I know. Current problem is with sqlite3 and the node version. This is at least what I found out. But I am not an expert on that topic.
