### ISSUE TITLE
node-red-contrib-rfxcom wont install

### ISSUE THREAD

**Issue by UIC** [hassio-addons/addon-node-red#576]
# Problem/Motivation
Installation of node-red-contrib-rfxcom.
In previous versions I have been able to get around this problem by installing the extension via node-red configuration. Like this:
--------------------
system_packages:
  - make gcc python linux-headers
npm_packages:
  - node-red-contrib-rfxcom
--------------------
 But this no longer works after this update.

My Versions is:
-----------------------------------------------------------
 Add-on version: 6.3.0
 You are running the latest version of this add-on.
 System: HassOS 3.13  (armv7 / raspberrypi3)
 Home Assistant Core: 0.110.4
 Home Assistant Supervisor: 225
-----------------------------------------------------------
## Expected behavior

Install success.

## Actual behavior
Install of node-red-contrib-rfxcom fail (Manage Palette - Install). 
with log:
-----------------------------------------------------------
2020-05-31T07:36:54.828Z Install : node-red-contrib-rfxcom 2.10.0

2020-05-31T07:36:54.974Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-rfxcom@2.10.0
2020-05-31T07:37:14.450Z [out] 
2020-05-31T07:37:14.450Z [out] > @serialport/bindings@8.0.8 install /config/node-red/node_modules/@serialport/bindings
2020-05-31T07:37:14.450Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2020-05-31T07:37:14.450Z [out] 
2020-05-31T07:37:15.987Z [err] prebuild-install
2020-05-31T07:37:15.988Z [err]  WARN install No prebuilt binaries found (target=12.15.0 runtime=node arch=arm libc=musl platform=linux)
2020-05-31T07:37:19.171Z [err] gyp
2020-05-31T07:37:19.174Z [err]  
2020-05-31T07:37:19.174Z [err] ERR!
2020-05-31T07:37:19.175Z [err]  
2020-05-31T07:37:19.176Z [err] build error
2020-05-31T07:37:19.176Z [err]  
2020-05-31T07:37:19.180Z [err] gyp
2020-05-31T07:37:19.181Z [err]  
2020-05-31T07:37:19.182Z [err] ERR!
2020-05-31T07:37:19.182Z [err]  
2020-05-31T07:37:19.183Z [err] stack
2020-05-31T07:37:19.184Z [err]  Error: not found: make
2020-05-31T07:37:19.184Z [err] gyp
2020-05-31T07:37:19.185Z [err]  
2020-05-31T07:37:19.185Z [err] ERR!
2020-05-31T07:37:19.186Z [err]  
2020-05-31T07:37:19.186Z [err] stack
2020-05-31T07:37:19.187Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-05-31T07:37:19.187Z [err] gyp
2020-05-31T07:37:19.187Z [err]  
2020-05-31T07:37:19.188Z [err] ERR!
2020-05-31T07:37:19.188Z [err]  
2020-05-31T07:37:19.189Z [err] stack
2020-05-31T07:37:19.189Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-05-31T07:37:19.190Z [err] gyp
2020-05-31T07:37:19.190Z [err]  
2020-05-31T07:37:19.191Z [err] ERR!
2020-05-31T07:37:19.191Z [err]  
2020-05-31T07:37:19.192Z [err] stack
2020-05-31T07:37:19.192Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-05-31T07:37:19.192Z [err] gyp
2020-05-31T07:37:19.193Z [err]  
2020-05-31T07:37:19.193Z [err] ERR!
2020-05-31T07:37:19.194Z [err]  
2020-05-31T07:37:19.199Z [err] stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-05-31T07:37:19.199Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-05-31T07:37:19.199Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-05-31T07:37:19.199Z [err] gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
2020-05-31T07:37:19.199Z [err] gyp ERR! System Linux 4.19.114-v7
2020-05-31T07:37:19.199Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-05-31T07:37:19.199Z [err] gyp ERR! cwd /config/node-red/node_modules/@serialport/bindings
2020-05-31T07:37:19.199Z [err] gyp ERR! node -v v12.15.0
2020-05-31T07:37:19.199Z [err] gyp ERR! node-gyp -v v5.0.5
2020-05-31T07:37:19.199Z [err] gyp ERR! not ok 
2020-05-31T07:37:20.061Z [err] npm
2020-05-31T07:37:20.062Z [err]  ERR! code ELIFECYCLE
2020-05-31T07:37:20.062Z [err] npm ERR! 
2020-05-31T07:37:20.063Z [err] errno 1
2020-05-31T07:37:20.069Z [err] npm 
2020-05-31T07:37:20.069Z [err] ERR! @serialport/bindings@8.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2020-05-31T07:37:20.069Z [err] npm ERR! Exit status 1
2020-05-31T07:37:20.070Z [err] npm ERR! 
2020-05-31T07:37:20.070Z [err] npm ERR!
2020-05-31T07:37:20.070Z [err]  Failed at the @serialport/bindings@8.0.8 install script.
2020-05-31T07:37:20.070Z [err] npm ERR!
2020-05-31T07:37:20.070Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2020-05-31T07:37:20.147Z [err] 
2020-05-31T07:37:20.147Z [err] npm ERR! A complete log of this run can be found in:
2020-05-31T07:37:20.147Z [err] npm ERR!     /root/.npm/_logs/2020-05-31T07_37_20_118Z-debug.log
2020-05-31T07:37:20.181Z rc=1

## Steps to reproduce

Ordinary install via Palette (or config file)

## Proposed changes

It looks like there is a problem with the serial port. The drivers are not compiled and the installation fails when compiling the new driver.
This is where my knowledge ends.
Pleas help!
regards 
Håkan

**Comment by frenck** [comment]
Can't help you there m8.

Looks like a dependency is missing or incompatible with `node-red-contrib-rfxcom`. Please raise an issue with `node-red-contrib-rfxcom`.

**Comment by UIC** [comment]
I have done this (when I have this problem in the earlier version) and according to him it works everywhere else except in HassIO.
Can it be a permission problem?
