### ISSUE TITLE
Node red crashing, bad gateway 502 + [error] 651#651

### ISSUE THREAD

**Issue by weirders** [hassio-addons/addon-node-red#618]
# Problem/Motivation
Node red keeps crashing and restarting. Having trouble finding the source of the issue. Appears to be happening since one of the later updates.

Here's the log from HA add-on. No idea how I can check out the on in /root/.npm/. Any tips?

`15 Jul 13:49:29 - [info] Server now running at http://127.0.0.1:46836/
15 Jul 13:49:29 - [info] Starting flows
15 Jul 13:49:36 - [info] Started flows
(node:21930) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
15 Jul 13:49:36 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
15 Jul 13:49:37 - [error] [function:calculate avg score] TypeError: Cannot read property '0' of undefined
15 Jul 13:49:37 - [info] [server:Home Assistant] WebSocket Connected to http://supervisor/core
15 Jul 13:51:40 - [red] Uncaught Exception:
15 Jul 13:51:40 - TypeError: Class constructor Listing cannot be invoked without 'new'
    at initCloneArray (/opt/node_modules/lodash.clonedeep/index.js:1235:22)
    at baseClone (/opt/node_modules/lodash.clonedeep/index.js:854:14)
    at /opt/node_modules/lodash.clonedeep/index.js:897:30
    at arrayEach (/opt/node_modules/lodash.clonedeep/index.js:140:9)
    at baseClone (/opt/node_modules/lodash.clonedeep/index.js:891:3)
    at /opt/node_modules/lodash.clonedeep/index.js:897:30
    at arrayEach (/opt/node_modules/lodash.clonedeep/index.js:140:9)
    at baseClone (/opt/node_modules/lodash.clonedeep/index.js:891:3)
    at cloneDeep (/opt/node_modules/lodash.clonedeep/index.js:1399:10)
    at Object.cloneMessage (/opt/node_modules/@node-red/util/lib/util.js:91:17)
    at SentimentNode.Node.send (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:410:61)
    at /opt/node_modules/node-red-node-sentiment/72-sentiment.js:15:26
    at /opt/node_modules/sentiment/lib/index.js:67:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:429:9)
[15/Jul/2020:13:51:40 +0200] 101 -(192.168.10.146) GET /comms HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36)
[15/Jul/2020:13:51:40 +0200] 101 192.168.10.132, 172.30.32.1(172.30.32.2) GET /comms HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-15T11_51_40_594Z-debug.log
[13:51:40] INFO: Starting Node-RED...
2020/07/15 13:51:42 [error] 651#651: *9476 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "mydomainredacted.duckdns.org:8123"
[15/Jul/2020:13:51:42 +0200] 502 192.168.10.132, 172.30.32.1(172.30.32.2) GET /comms HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36)`

**Comment by frenck** [comment]
This seems to be an issue with the Home Assistant node. Unfortunately, from an add-on perspective, there is not much I can do about is. Add-ons wrap existing software.

I guess the best place to report your issue would be here: <https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues>

Thanks 👍

**Comment by weirders** [comment]
appreciate it. And sorry for the code mess. Didn't copy well.

**Comment by frenck** [comment]
Don't worry, I was able to read it 😉
