### ISSUE TITLE
error grpc node-pre-gyp

### ISSUE THREAD

**Issue by TomasDlg** [hassio-addons/addon-node-red#630]
Hello,

I’ve try install node-red-contrib-alice but i’ve this error:

-----------------------------------------------------------
2020-07-26T14:17:16.653Z Install : node-red-contrib-alice 0.4.1

2020-07-26T14:18:07.882Z [out] 
2020-07-26T14:18:07.882Z [out] > grpc@1.24.2 install /config/node-red/node_modules/grpc
2020-07-26T14:18:07.882Z [out] > node-pre-gyp install --fallback-to-build --library=static_library
2020-07-26T14:18:07.882Z [out] 
2020-07-26T14:18:09.360Z [err] node-pre-gyp
2020-07-26T14:18:09.362Z [err]  
2020-07-26T14:18:09.362Z [err] WARN Using request for node-pre-gyp https download 
2020-07-26T14:18:10.126Z [err] node-pre-gyp
2020-07-26T14:18:10.127Z [err]  WARN
2020-07-26T14:18:10.127Z [err]  Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/node-v72-linux-arm-musl.tar.gz 
2020-07-26T14:18:10.128Z [err] node-pre-gyp WARN 
2020-07-26T14:18:10.128Z [err] Pre-built binaries not found for grpc@1.24.2 and node@12.17.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp) 
2020-07-26T14:18:14.230Z [err] gyp
2020-07-26T14:18:14.232Z [err]  
2020-07-26T14:18:14.233Z [err] ERR! build error 
2020-07-26T14:18:14.234Z [err] gyp
2020-07-26T14:18:14.235Z [err]  ERR! 
2020-07-26T14:18:14.235Z [err] stack Error: not found: make
2020-07-26T14:18:14.235Z [err] gyp ERR!
2020-07-26T14:18:14.235Z [err]  stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-07-26T14:18:14.235Z [err] gyp ERR! 
2020-07-26T14:18:14.236Z [err] stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-07-26T14:18:14.236Z [err] gyp ERR! 
2020-07-26T14:18:14.236Z [err] stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-07-26T14:18:14.236Z [err] gyp ERR!
2020-07-26T14:18:14.236Z [err]  stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-07-26T14:18:14.236Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-07-26T14:18:14.236Z [err] gyp ERR! 
2020-07-26T14:18:14.236Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-07-26T14:18:14.236Z [err] gyp 
2020-07-26T14:18:14.236Z [err] ERR! stack     at FSReqCallback.oncomplete (fs.js:167:21)
2020-07-26T14:18:14.237Z [err] gyp
2020-07-26T14:18:14.237Z [err]  ERR! System Linux 4.19.118-v7l+
2020-07-26T14:18:14.237Z [err] gyp
2020-07-26T14:18:14.238Z [err]  ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node" "--module_name=grpc_node" "--module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
2020-07-26T14:18:14.238Z [err] gyp ERR!
2020-07-26T14:18:14.238Z [err]  cwd /config/node-red/node_modules/grpc
2020-07-26T14:18:14.238Z [err] gyp ERR!
2020-07-26T14:18:14.238Z [err]  node -v v12.17.0
2020-07-26T14:18:14.238Z [err] gyp ERR! 
2020-07-26T14:18:14.238Z [err] node-gyp -v v5.1.0
2020-07-26T14:18:14.238Z [err] gyp
2020-07-26T14:18:14.238Z [err]  ERR! not ok
2020-07-26T14:18:14.238Z [err]  
2020-07-26T14:18:14.244Z [err] node-pre-gyp
2020-07-26T14:18:14.244Z [err]  ERR!
2020-07-26T14:18:14.244Z [err]  build error
2020-07-26T14:18:14.244Z [err]  
2020-07-26T14:18:14.246Z [err] node-pre-gyp
2020-07-26T14:18:14.246Z [err]  ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node --module_name=grpc_node --module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-07-26T14:18:14.246Z [err] node-pre-gyp
2020-07-26T14:18:14.247Z [err]  ERR! 
2020-07-26T14:18:14.247Z [err] stack     at ChildProcess.<anonymous> (/config/node-red/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2020-07-26T14:18:14.247Z [err] node-pre-gyp ERR! stack
2020-07-26T14:18:14.247Z [err]      at ChildProcess.emit (events.js:315:20)
2020-07-26T14:18:14.247Z [err] node-pre-gyp 
2020-07-26T14:18:14.247Z [err] ERR! stack
2020-07-26T14:18:14.247Z [err]      at maybeClose (internal/child_process.js:1021:16)
2020-07-26T14:18:14.247Z [err] node-pre-gyp ERR!
2020-07-26T14:18:14.247Z [err]  stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2020-07-26T14:18:14.248Z [err] node-pre-gyp
2020-07-26T14:18:14.248Z [err]  ERR! System Linux 4.19.118-v7l+
2020-07-26T14:18:14.248Z [err] node-pre-gyp
2020-07-26T14:18:14.249Z [err]  ERR! command
2020-07-26T14:18:14.249Z [err]  "/usr/bin/node" "/config/node-red/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
2020-07-26T14:18:14.249Z [err] node-pre-gyp
2020-07-26T14:18:14.249Z [err]  ERR! cwd
2020-07-26T14:18:14.249Z [err]  /config/node-red/node_modules/grpc
2020-07-26T14:18:14.249Z [err] node-pre-gyp ERR!
2020-07-26T14:18:14.249Z [err]  node -v v12.17.0
2020-07-26T14:18:14.249Z [err] node-pre-gyp 
2020-07-26T14:18:14.249Z [err] ERR! node-pre-gyp -v v0.14.0
2020-07-26T14:18:14.249Z [err] node-pre-gyp ERR! 
2020-07-26T14:18:14.249Z [err] not ok 
2020-07-26T14:18:14.251Z [out] Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node --module_name=grpc_node --module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-07-26T14:18:16.194Z [err] npm
2020-07-26T14:18:16.194Z [err]  
2020-07-26T14:18:16.195Z [err] ERR!
2020-07-26T14:18:16.195Z [err]  
2020-07-26T14:18:16.195Z [err] code
2020-07-26T14:18:16.195Z [err]  ELIFECYCLE
2020-07-26T14:18:16.196Z [err] npm
2020-07-26T14:18:16.196Z [err]  
2020-07-26T14:18:16.196Z [err] ERR!
2020-07-26T14:18:16.196Z [err]  
2020-07-26T14:18:16.196Z [err] errno
2020-07-26T14:18:16.196Z [err]  1
2020-07-26T14:18:16.199Z [err] npm
2020-07-26T14:18:16.200Z [err]  
2020-07-26T14:18:16.200Z [err] ERR!
2020-07-26T14:18:16.200Z [err]  grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
2020-07-26T14:18:16.200Z [err] npm
2020-07-26T14:18:16.200Z [err]  
2020-07-26T14:18:16.201Z [err] ERR!
2020-07-26T14:18:16.201Z [err]  Exit status 1
2020-07-26T14:18:16.201Z [err] npm
2020-07-26T14:18:16.202Z [err]  
2020-07-26T14:18:16.202Z [err] ERR!
2020-07-26T14:18:16.202Z [err]  
2020-07-26T14:18:16.202Z [err] npm
2020-07-26T14:18:16.203Z [err]  
2020-07-26T14:18:16.203Z [err] ERR!
2020-07-26T14:18:16.203Z [err]  Failed at the grpc@1.24.2 install script.
2020-07-26T14:18:16.204Z [err] npm
2020-07-26T14:18:16.204Z [err]  
2020-07-26T14:18:16.204Z [err] ERR!
2020-07-26T14:18:16.205Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2020-07-26T14:18:16.274Z [err] 
2020-07-26T14:18:16.275Z [err] npm ERR! A complete log of this run can be found in:
2020-07-26T14:18:16.275Z [err] npm 
2020-07-26T14:18:16.275Z [err] ERR!     /root/.npm/_logs/2020-07-26T14_18_16_240Z-debug.log
2020-07-26T14:18:16.310Z rc=1

How i can resolve this error?
thank you for help

<blockquote></blockquote>

**Comment by sinclairpaul** [comment]
> 2020-07-26T14:18:14.235Z [err] stack Error: not found: make

You need the pre-requisite packages installed.  There are a number of similar closed issues on this.

**Comment by TomasDlg** [comment]
Hi.
My config:

credential_secret: *******************************
dark_mode: false
http_node:
  username: ***********
  password: ***********
http_static:
  username: ''
  password: ''
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
require_ssl: true
system_packages: []
npm_packages:
  - node-pre-gyp
  - grpc
init_commands: []
log_level: info

Log:

[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 7.0.0
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 0.113.1
 Home Assistant Supervisor: 229
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
[18:30:55] INFO: Password is NOT in the Have I Been Pwned database! Nice!
patching file nodes/ui_base.html
Hunk #1 succeeded at 1177 (offset 646 lines).
audited 374 packages in 9.269s

17 packages are looking for funding
  run `npm fund` for details

found 11 vulnerabilities (5 low, 4 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] user.sh: executing... 
[18:31:11] INFO: Starting installation of custom NPM/Node-RED packages...

> grpc@1.24.3 install /opt/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.24.3/node-v72-linux-arm-musl.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for grpc@1.24.3 and node@12.17.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:167:21)
gyp ERR! System Linux 4.19.118-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/opt/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node" "--module_name=grpc_node" "--module_path=/opt/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /opt/node_modules/grpc
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/opt/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node --module_name=grpc_node --module_path=/opt/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.19.118-v7l+
node-pre-gyp ERR! command "/usr/bin/node" "/opt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /opt/node_modules/grpc
node-pre-gyp ERR! node -v v12.17.0
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/opt/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl/grpc_node.node --module_name=grpc_node --module_path=/opt/node_modules/grpc/src/node/extension_binary/node-v72-linux-arm-musl --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.24.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.24.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-27T14_32_03_029Z-debug.log
[18:32:03] FATAL: Failed to install a specified npm package
[cont-init.d] user.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by sinclairpaul** [comment]
```
system_packages:
  - make
```
