### ISSUE TITLE
Could not install doorbird node

### ISSUE THREAD

**Issue by Diddlik** [hassio-addons/addon-node-red#797]
I try to install doorbird node, but alway get the following error. I tried it on local node-red instalation and node-red from docker. in both cases it works fine.

`-----------------------------------------------------------
2020-12-07T21:43:34.658Z installieren : node-red-contrib-doorbird 0.2.8

2020-12-07T21:43:34.850Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-doorbird@0.2.8
2020-12-07T21:43:52.706Z [out] 
2020-12-07T21:43:52.706Z [out] > argon2@0.27.0 install /config/node-red/node_modules/argon2
2020-12-07T21:43:52.706Z [out] > node-pre-gyp install --fallback-to-build
2020-12-07T21:43:52.706Z [out] 
2020-12-07T21:43:53.866Z [err] node-pre-gyp
2020-12-07T21:43:53.869Z [err]  
2020-12-07T21:43:53.869Z [err] WARN Using request for node-pre-gyp https download 
2020-12-07T21:43:54.302Z [err] node-pre-gyp
2020-12-07T21:43:54.303Z [err]  WARN
2020-12-07T21:43:54.304Z [err]  Tried to download(404): https://github.com/ranisalt/node-argon2/releases/download/v0.27.0/argon2-v0.27.0-napi-v3-linux-arm64-musl.tar.gz 
2020-12-07T21:43:54.304Z [err] node-pre-gyp WARN Pre-built binaries not found for argon2@0.27.0 and node@12.18.4 (node-v72 ABI, musl) (falling back to source compile with node-gyp)
2020-12-07T21:43:54.304Z [err]  
2020-12-07T21:43:57.691Z [err] gyp
2020-12-07T21:43:57.693Z [err]  
2020-12-07T21:43:57.693Z [err] ERR! build error 
2020-12-07T21:43:57.695Z [err] gyp
2020-12-07T21:43:57.695Z [err]  ERR! stack Error: not found: make
2020-12-07T21:43:57.695Z [err] gyp ERR!
2020-12-07T21:43:57.696Z [err]  stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-12-07T21:43:57.696Z [err] gyp 
2020-12-07T21:43:57.696Z [err] ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-12-07T21:43:57.696Z [err] gyp ERR! stack
2020-12-07T21:43:57.696Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-12-07T21:43:57.696Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-12-07T21:43:57.696Z [err] gyp
2020-12-07T21:43:57.697Z [err]  ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-12-07T21:43:57.697Z [err] gyp
2020-12-07T21:43:57.697Z [err]  ERR! stack
2020-12-07T21:43:57.697Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-12-07T21:43:57.697Z [err] gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
2020-12-07T21:43:57.698Z [err] gyp
2020-12-07T21:43:57.698Z [err]  ERR! System Linux 5.4.79-v8
2020-12-07T21:43:57.698Z [err] gyp 
2020-12-07T21:43:57.698Z [err] ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/config/node-red/node_modules/argon2/lib/binding/napi-v3/argon2.node" "--module_name=argon2" "--module_path=/config/node-red/node_modules/argon2/lib/binding/napi-v3" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
2020-12-07T21:43:57.699Z [err] gyp ERR! cwd /config/node-red/node_modules/argon2
2020-12-07T21:43:57.699Z [err] gyp ERR! node -v
2020-12-07T21:43:57.699Z [err]  v12.18.4
2020-12-07T21:43:57.699Z [err] gyp
2020-12-07T21:43:57.699Z [err]  ERR! node-gyp -v v5.1.0
2020-12-07T21:43:57.699Z [err] gyp ERR! 
2020-12-07T21:43:57.710Z [err] not ok 
2020-12-07T21:43:57.711Z [err] node-pre-gyp ERR! build error 
2020-12-07T21:43:57.711Z [err] node-pre-gyp
2020-12-07T21:43:57.712Z [err]  ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/config/node-red/node_modules/argon2/lib/binding/napi-v3 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
2020-12-07T21:43:57.712Z [err] node-pre-gyp ERR!
2020-12-07T21:43:57.712Z [err]  stack     at ChildProcess.<anonymous> (/config/node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2020-12-07T21:43:57.712Z [err] node-pre-gyp 
2020-12-07T21:43:57.712Z [err] ERR! stack     at ChildProcess.emit (events.js:315:20)
2020-12-07T21:43:57.712Z [err] node-pre-gyp ERR! stack
2020-12-07T21:43:57.713Z [err]      at maybeClose (internal/child_process.js:1021:16)
2020-12-07T21:43:57.713Z [err] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2020-12-07T21:43:57.714Z [err] node-pre-gyp ERR! System
2020-12-07T21:43:57.714Z [err]  Linux 5.4.79-v8
2020-12-07T21:43:57.714Z [err] node-pre-gyp
2020-12-07T21:43:57.714Z [err]  ERR! command
2020-12-07T21:43:57.714Z [err]  "/usr/bin/node" "/config/node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2020-12-07T21:43:57.714Z [err] node-pre-gyp
2020-12-07T21:43:57.715Z [err]  ERR! cwd /config/node-red/node_modules/argon2
2020-12-07T21:43:57.715Z [err] node-pre-gyp 
2020-12-07T21:43:57.715Z [err] ERR! node -v v12.18.4
2020-12-07T21:43:57.715Z [err] node-pre-gyp 
2020-12-07T21:43:57.715Z [err] ERR! node-pre-gyp -v v0.15.0
2020-12-07T21:43:57.715Z [err] node-pre-gyp ERR!
2020-12-07T21:43:57.715Z [err]  not ok 
2020-12-07T21:43:57.717Z [out] Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/config/node-red/node_modules/argon2/lib/binding/napi-v3 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
2020-12-07T21:43:58.703Z [err] npm
2020-12-07T21:43:58.703Z [err]  
2020-12-07T21:43:58.703Z [err] ERR!
2020-12-07T21:43:58.704Z [err]  
2020-12-07T21:43:58.704Z [err] code
2020-12-07T21:43:58.704Z [err]  ELIFECYCLE
2020-12-07T21:43:58.705Z [err] npm
2020-12-07T21:43:58.705Z [err]  
2020-12-07T21:43:58.705Z [err] ERR!
2020-12-07T21:43:58.705Z [err]  errno 1
2020-12-07T21:43:58.715Z [err] npm
2020-12-07T21:43:58.716Z [err]  ERR! argon2@0.27.0 install: `node-pre-gyp install --fallback-to-build`
2020-12-07T21:43:58.716Z [err] npm ERR! Exit status 1
2020-12-07T21:43:58.716Z [err] npm ERR!
2020-12-07T21:43:58.716Z [err]  
2020-12-07T21:43:58.716Z [err] npm 
2020-12-07T21:43:58.716Z [err] ERR! Failed at the argon2@0.27.0 install script.
2020-12-07T21:43:58.716Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-12-07T21:43:58.751Z [err] 
2020-12-07T21:43:58.751Z [err] npm ERR!
2020-12-07T21:43:58.751Z [err]  A complete log of this run can be found in:
2020-12-07T21:43:58.751Z [err] npm 
2020-12-07T21:43:58.751Z [err] ERR!     /root/.npm/_logs/2020-12-07T21_43_58_737Z-debug.log`

**Comment by frenck** [comment]
`ERR! stack Error: not found: make`

Please install it.
