### ISSUE TITLE
Unable to install node-red-contrib-facial-recognition

### ISSUE THREAD

**Issue by kgalilio** [hassio-addons/addon-node-red#808]
# Problem/Motivation
Unable to install additional node, particularly [node-red-contrib-facial-recognition](https://discourse.nodered.org/t/announce-node-red-contrib-facial-recognition/37384)
> (Why the issue was filed)
I need help with installing the node, as the log does not indicate the reason behind the failure of the node to function.
## Expected behavior

> I expect the node to install and run properly.

## Actual behavior

> The node installs successfully, and I can use it in flows; however, the flow will not deploy because of this node. After restarting nod-red, the node disappears from the list, and when I check it in the palette list, it shows exclamation mark and "[object Object]" against the node.

## Steps to reproduce

> From node-red, click the hamburger menu at the top right corner> Manage palettes> Install> enter `node-red-contrib-facial-recognition` in the search field> click install.

## Proposed changes

> I am not sure what is causing the node to fail. Looking at the /config/node-red/node_modules directory, I can see the node has installed; but it seems that it requires some system dependencies for it to work. Therefore, I am unable to recommend any actions here.

**Comment by sinclairpaul** [comment]
It will mean a missing system dependency (likely build tools), please provide logs.

Also I would recommend installing the palette's via the config rather than in Node-Red itself.

**Comment by kgalilio** [comment]
> It will mean a missing system dependency (likely build tools), please provide logs.
> 
> Also I would recommend installing the palette's via the config rather than in Node-Red itself.

Thanks Paul. I tried installing through the config, but I got the same result.
Here is the log:

-----------------------------------------------------------
```
2020-12-15T05:52:52.611Z Install : node-red-contrib-facial-recognition 0.28.99

2020-12-15T05:52:52.224Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-facial-recognition@0.28.99
2020-12-15T05:54:01.208Z [out] 
2020-12-15T05:54:01.208Z [out] > @tensorflow/tfjs-node@2.7.0 install /config/node-red/node_modules/@tensorflow/tfjs-node
2020-12-15T05:54:01.208Z [out] > node scripts/install.js
2020-12-15T05:54:01.208Z [out] 
2020-12-15T05:54:01.320Z [out] CPU-linux-2.7.0.tar.gz
2020-12-15T05:54:01.323Z [err] * Downloading libtensorflow
2020-12-15T05:54:08.707Z [err] 
2020-12-15T05:54:08.716Z [err] * Building TensorFlow Node.js bindings
2020-12-15T05:54:10.120Z [out] node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
2020-12-15T05:54:10.120Z [out] node-pre-gyp WARN Using request for node-pre-gyp https download 
2020-12-15T05:54:10.120Z [out] node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v6/2.7.0/CPU-linux-2.7.0.tar.gz 
2020-12-15T05:54:10.120Z [out] node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node@2.7.0 and node@12.18.4 (node-v72 ABI, musl) (falling back to source compile with node-gyp) 
2020-12-15T05:54:10.120Z [out] gyp ERR! build error 
2020-12-15T05:54:10.120Z [out] gyp ERR! stack Error: not found: make
2020-12-15T05:54:10.120Z [out] gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-12-15T05:54:10.120Z [out] gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-12-15T05:54:10.120Z [out] gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-12-15T05:54:10.120Z [out] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-12-15T05:54:10.120Z [out] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-12-15T05:54:10.120Z [out] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-12-15T05:54:10.120Z [out] gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
2020-12-15T05:54:10.120Z [out] gyp ERR! System Linux 5.4.0-58-generic
2020-12-15T05:54:10.120Z [out] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/config/node-red/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=/config/node-red/node_modules/@tensorflow/tfjs-node/lib/napi-v6" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
2020-12-15T05:54:10.120Z [out] gyp ERR! cwd /config/node-red/node_modules/@tensorflow/tfjs-node
2020-12-15T05:54:10.120Z [out] gyp ERR! node -v v12.18.4
2020-12-15T05:54:10.120Z [out] gyp ERR! node-gyp -v v5.1.0
2020-12-15T05:54:10.120Z [out] gyp ERR! not ok 
2020-12-15T05:54:10.120Z [out] node-pre-gyp ERR! build error 
2020-12-15T05:54:10.120Z [out] node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node --module_name=tfjs_binding --module_path=/config/node-red/node_modules/@tensorflow/tfjs-node/lib/napi-v6 --napi_version=6 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
2020-12-15T05:54:10.120Z [out] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/config/node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2020-12-15T05:54:10.120Z [out] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
2020-12-15T05:54:10.120Z [out] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
2020-12-15T05:54:10.120Z [out] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2020-12-15T05:54:10.120Z [out] node-pre-gyp ERR! System Linux 5.4.0-58-generic
2020-12-15T05:54:10.120Z [out] node-pre-gyp ERR! command "/usr/bin/node" "/config/node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2020-12-15T05:54:10.120Z [out] node-pre-gyp ERR! cwd /config/node-red/node_modules/@tensorflow/tfjs-node
2020-12-15T05:54:10.120Z [out] node-pre-gyp ERR! node -v v12.18.4
2020-12-15T05:54:10.120Z [out] node-pre-gyp ERR! node-pre-gyp -v v0.14.0
2020-12-15T05:54:10.120Z [out] node-pre-gyp ERR! not ok 
2020-12-15T05:54:10.120Z [out] 
2020-12-15T05:54:10.142Z [out] 
2020-12-15T05:54:10.142Z [out] > core-js@3.8.1 postinstall /config/node-red/node_modules/core-js
2020-12-15T05:54:10.142Z [out] > node -e "try{require('./postinstall')}catch(e){}"
2020-12-15T05:54:10.142Z [out] 
2020-12-15T05:54:10.203Z [out] [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
2020-12-15T05:54:10.203Z [out] 
2020-12-15T05:54:10.203Z [out] [96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
2020-12-15T05:54:10.203Z [out] [96m>[94m https://opencollective.com/core-js [0m
2020-12-15T05:54:10.203Z [out] [96m>[94m https://www.patreon.com/zloirock [0m
2020-12-15T05:54:10.203Z [out] 
2020-12-15T05:54:10.203Z [out] [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2020-12-15T05:54:10.203Z [out] 
2020-12-15T05:54:10.580Z [out] + node-red-contrib-facial-recognition@0.28.99
2020-12-15T05:54:10.580Z [out] added 98 packages from 59 contributors in 77.733s
2020-12-15T05:54:10.593Z rc=0
```

**Comment by frenck** [comment]
`Error: not found: make`

You need to install system tools, like `make` as suggested in the logs. However, I cannot recommend using that node, as it is using tensorflow. You will have a hard time getting that up and running/compiled.
