### ISSUE TITLE
Unable to install node-red-contrib-gpio (also node-red-contrib-johnny-five and node-red-contrib-johnny5)

### ISSUE THREAD

**Issue by Plazmin** [hassio-addons/addon-node-red#809]
# Problem/Motivation

I cannot install node-red-contrib-gpio

## Expected behavior

Node-red-contrib-gpio can be installed.

## Actual behavior

2020-12-14T20:40:18.240Z Install : node-red-contrib-gpio 0.14.0
2020-12-14T20:40:18.337Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-gpio@0.14.0
2020-12-14T20:40:39.504Z [out] 
2020-12-14T20:40:39.504Z [out] > serialport@6.0.5 install /config/node-red/node_modules/firmata/node_modules/serialport
2020-12-14T20:40:39.504Z [out] > prebuild-install || node-gyp rebuild
2020-12-14T20:40:39.504Z [out] 
2020-12-14T20:40:40.395Z [err] prebuild-install
2020-12-14T20:40:40.396Z [err]  
2020-12-14T20:40:40.396Z [err] WARN
2020-12-14T20:40:40.396Z [err]  
2020-12-14T20:40:40.396Z [err] install
2020-12-14T20:40:40.396Z [err]  No prebuilt binaries found (target=12.18.4 runtime=node arch=x64 platform=linux)
2020-12-14T20:40:41.289Z [err] gyp
2020-12-14T20:40:41.290Z [err]  
2020-12-14T20:40:41.291Z [err] ERR!
2020-12-14T20:40:41.291Z [err]  
2020-12-14T20:40:41.291Z [err] build error
2020-12-14T20:40:41.291Z [err]  
2020-12-14T20:40:41.293Z [err] gyp
2020-12-14T20:40:41.293Z [err]  
2020-12-14T20:40:41.293Z [err] ERR!
2020-12-14T20:40:41.293Z [err]  
2020-12-14T20:40:41.293Z [err] stack
2020-12-14T20:40:41.293Z [err]  Error: not found: make
2020-12-14T20:40:41.293Z [err] gyp
2020-12-14T20:40:41.293Z [err]  
2020-12-14T20:40:41.294Z [err] ERR!
2020-12-14T20:40:41.294Z [err]  
2020-12-14T20:40:41.294Z [err] stack
2020-12-14T20:40:41.294Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-12-14T20:40:41.294Z [err] gyp
2020-12-14T20:40:41.294Z [err]  
2020-12-14T20:40:41.294Z [err] ERR!
2020-12-14T20:40:41.294Z [err]  
2020-12-14T20:40:41.294Z [err] stack
2020-12-14T20:40:41.294Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-12-14T20:40:41.295Z [err] gyp
2020-12-14T20:40:41.295Z [err]  
2020-12-14T20:40:41.295Z [err] ERR!
2020-12-14T20:40:41.295Z [err]  
2020-12-14T20:40:41.295Z [err] stack
2020-12-14T20:40:41.295Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-12-14T20:40:41.295Z [err] gyp
2020-12-14T20:40:41.295Z [err]  
2020-12-14T20:40:41.295Z [err] ERR!
2020-12-14T20:40:41.295Z [err]  
2020-12-14T20:40:41.295Z [err] stack
2020-12-14T20:40:41.296Z [err]      at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-12-14T20:40:41.296Z [err] gyp
2020-12-14T20:40:41.296Z [err]  
2020-12-14T20:40:41.296Z [err] ERR!
2020-12-14T20:40:41.296Z [err]  
2020-12-14T20:40:41.296Z [err] stack
2020-12-14T20:40:41.296Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-12-14T20:40:41.296Z [err] gyp
2020-12-14T20:40:41.296Z [err]  
2020-12-14T20:40:41.296Z [err] ERR!
2020-12-14T20:40:41.296Z [err]  
2020-12-14T20:40:41.296Z [err] stack
2020-12-14T20:40:41.297Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-12-14T20:40:41.297Z [err] gyp
2020-12-14T20:40:41.297Z [err]  
2020-12-14T20:40:41.297Z [err] ERR!
2020-12-14T20:40:41.297Z [err]  
2020-12-14T20:40:41.297Z [err] stack
2020-12-14T20:40:41.297Z [err]      at FSReqCallback.oncomplete (fs.js:168:21)
2020-12-14T20:40:41.297Z [err] gyp
2020-12-14T20:40:41.298Z [err]  
2020-12-14T20:40:41.298Z [err] ERR!
2020-12-14T20:40:41.298Z [err]  
2020-12-14T20:40:41.298Z [err] System
2020-12-14T20:40:41.299Z [err]  Linux 5.4.83
2020-12-14T20:40:41.299Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-12-14T20:40:41.299Z [err] gyp ERR! cwd /config/node-red/node_modules/firmata/node_modules/serialport
2020-12-14T20:40:41.299Z [err] gyp ERR! node -v v12.18.4
2020-12-14T20:40:41.299Z [err] gyp ERR! node-gyp -v v5.1.0
2020-12-14T20:40:41.299Z [err] gyp ERR! not ok 
2020-12-14T20:40:42.193Z [err] npm
2020-12-14T20:40:42.194Z [err]  
2020-12-14T20:40:42.194Z [err] WARN
2020-12-14T20:40:42.194Z [err]  node-red-contrib-ui-led@0.3.3 requires a peer of node-red-dashboard@2.23.x but none is installed. You must install peer dependencies yourself.
2020-12-14T20:40:42.195Z [err] 
2020-12-14T20:40:42.210Z [err] npm
2020-12-14T20:40:42.210Z [err]  
2020-12-14T20:40:42.210Z [err] ERR!
2020-12-14T20:40:42.211Z [err]  
2020-12-14T20:40:42.211Z [err] code
2020-12-14T20:40:42.211Z [err]  ELIFECYCLE
2020-12-14T20:40:42.211Z [err] npm
2020-12-14T20:40:42.211Z [err]  
2020-12-14T20:40:42.211Z [err] ERR!
2020-12-14T20:40:42.211Z [err]  
2020-12-14T20:40:42.211Z [err] errno
2020-12-14T20:40:42.211Z [err]  1
2020-12-14T20:40:42.214Z [err] npm
2020-12-14T20:40:42.214Z [err]  
2020-12-14T20:40:42.214Z [err] ERR!
2020-12-14T20:40:42.214Z [err]  serialport@6.0.5 install: `prebuild-install || node-gyp rebuild`
2020-12-14T20:40:42.214Z [err] npm
2020-12-14T20:40:42.215Z [err]  
2020-12-14T20:40:42.215Z [err] ERR!
2020-12-14T20:40:42.215Z [err]  Exit status 1
2020-12-14T20:40:42.215Z [err] npm
2020-12-14T20:40:42.215Z [err]  
2020-12-14T20:40:42.215Z [err] ERR!
2020-12-14T20:40:42.215Z [err]  
2020-12-14T20:40:42.215Z [err] npm
2020-12-14T20:40:42.215Z [err]  
2020-12-14T20:40:42.215Z [err] ERR!
2020-12-14T20:40:42.215Z [err]  Failed at the serialport@6.0.5 install script.
2020-12-14T20:40:42.216Z [err] npm
2020-12-14T20:40:42.216Z [err]  
2020-12-14T20:40:42.216Z [err] ERR!
2020-12-14T20:40:42.216Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2020-12-14T20:40:42.260Z [err] 
2020-12-14T20:40:42.261Z [err] npm
2020-12-14T20:40:42.261Z [err]  
2020-12-14T20:40:42.261Z [err] ERR!
2020-12-14T20:40:42.261Z [err]  A complete log of this run can be found in:
2020-12-14T20:40:42.261Z [err] npm
2020-12-14T20:40:42.261Z [err]  
2020-12-14T20:40:42.262Z [err] ERR!
2020-12-14T20:40:42.262Z [err]      /root/.npm/_logs/2020-12-14T20_40_42_240Z-debug.log
2020-12-14T20:40:42.277Z rc=1

## Steps to reproduce

Installing Node-red-contrib-gpio in Home Assistant Community Add-on: Node-RED

**Comment by sinclairpaul** [comment]
> Error: not found: make

You need the system dependencies.  If you search the closed issues you will find lots similar:)
