### ISSUE TITLE
Cant install Node "node-red-contrib-smartmeter"

### ISSUE THREAD

**Issue by dominikfe** [hassio-addons/addon-node-red#818]
# Problem/Motivation

To read values from my energy meter I need the node node-red-contrib-smartmeter. I tried installing it through Node Red manage palette menu.

## Expected behavior

node-red-contrib-smartmeter to be installed and working.

## Actual behavior

Installation fails
Logfile:

```
-----------------------------------------------------------
2020-12-18T09:53:34.869Z Install : node-red-contrib-smartmeter 0.3.1

2020-12-18T09:53:34.938Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-smartmeter@0.3.1
2020-12-18T09:53:58.210Z [out] 
2020-12-18T09:53:58.210Z [out] > @serialport/bindings@8.0.8 install /config/node-red/node_modules/@serialport/bindings
2020-12-18T09:53:58.210Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2020-12-18T09:53:58.210Z [out] 
2020-12-18T09:53:59.471Z [err] prebuild-install
2020-12-18T09:53:59.472Z [err]  WARN install No prebuilt binaries found (target=12.18.4 runtime=node arch=arm libc=musl platform=linux)
2020-12-18T09:54:01.544Z [err] gyp
2020-12-18T09:54:01.545Z [err]  
2020-12-18T09:54:01.546Z [err] ERR! build error 
2020-12-18T09:54:01.547Z [err] gyp
2020-12-18T09:54:01.548Z [err]  ERR! stack
2020-12-18T09:54:01.548Z [err]  Error: not found: make
2020-12-18T09:54:01.548Z [err] gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-12-18T09:54:01.548Z [err] gyp
2020-12-18T09:54:01.548Z [err]  ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-12-18T09:54:01.548Z [err] gyp 
2020-12-18T09:54:01.548Z [err] ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-12-18T09:54:01.548Z [err] gyp ERR! 
2020-12-18T09:54:01.549Z [err] stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-12-18T09:54:01.549Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-12-18T09:54:01.549Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-12-18T09:54:01.549Z [err] gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
2020-12-18T09:54:01.550Z [err] gyp 
2020-12-18T09:54:01.551Z [err] ERR! System Linux 5.4.51-v7l+
2020-12-18T09:54:01.551Z [err] gyp ERR! 
2020-12-18T09:54:01.551Z [err] command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-12-18T09:54:01.551Z [err] gyp ERR! cwd /config/node-red/node_modules/@serialport/bindings
2020-12-18T09:54:01.551Z [err] gyp 
2020-12-18T09:54:01.551Z [err] ERR! node -v v12.18.4
2020-12-18T09:54:01.551Z [err] gyp ERR! node-gyp -v
2020-12-18T09:54:01.551Z [err]  v5.1.0
2020-12-18T09:54:01.551Z [err] gyp ERR! not ok
2020-12-18T09:54:01.552Z [err]  
2020-12-18T09:54:03.167Z [err] npm
2020-12-18T09:54:03.167Z [err]  ERR! code ELIFECYCLE
2020-12-18T09:54:03.167Z [err] npm ERR! errno 1
2020-12-18T09:54:03.184Z [err] npm
2020-12-18T09:54:03.184Z [err]  ERR! @serialport/bindings@8.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2020-12-18T09:54:03.184Z [err] npm ERR! Exit status 1
2020-12-18T09:54:03.184Z [err] npm
2020-12-18T09:54:03.185Z [err]  ERR! 
2020-12-18T09:54:03.185Z [err] npm ERR!
2020-12-18T09:54:03.185Z [err]  Failed at the @serialport/bindings@8.0.8 install script.
2020-12-18T09:54:03.185Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-12-18T09:54:03.230Z [err] 
2020-12-18T09:54:03.230Z [err] npm ERR! A complete log of this run can be found in:
2020-12-18T09:54:03.230Z [err] npm 
2020-12-18T09:54:03.231Z [err] ERR!     /root/.npm/_logs/2020-12-18T09_54_03_200Z-debug.log
2020-12-18T09:54:03.253Z rc=1
```

## Steps to reproduce

Log in to Home Assistant, enter the Node Red frontend, chose "manage palette" from menu, search for node-red-contrib-smartmeter and click install. 

## Proposed changes

none yet.

**Comment by tjorim** [comment]
`Error: not found: make`

Check one of the 20+ other issues here
