### ISSUE TITLE
node-red-contrib-msg-queue

### ISSUE THREAD

**Issue by firestrife23** [hassio-addons/addon-node-red#83]
# Problem/Motivation

> Failed to install pallete

## Expected behavior

> It shouldn't happen.. 

## Actual behavior

> see log

## Steps to reproduce

> install node-red-contrib-msg-quene pallete

## Log Message

```
3 Dec 17:41:43 - [info] Installing module: node-red-contrib-msg-queue, version: 1.0.2
3 Dec 17:42:21 - [warn] Installation of module node-red-contrib-msg-queue failed:
3 Dec 17:42:21 - [warn] ------------------------------------------
3 Dec 17:42:21 - [warn] 
> sqlite3@4.0.4 install /config/node-red/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.4/node-v57-linux-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.4 and node@8.14.0 (node-v57 ABI, musl) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/config/node-red/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v57-linux-arm" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /config/node-red/node_modules/sqlite3
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v57-linux-arm --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/config/node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.14.79-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/config/node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /config/node-red/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v57-linux-arm --napi_version=3 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-03T23_42_21_333Z-debug.log

3 Dec 17:42:21 - [warn] ------------------------------------------



```

**Comment by firestrife23** [comment]
Update: adding the following to Node Red's Config:
```
  "system_packages": [
    "build-base",
    "gcc"
  ],
```

It allowed me to start building the package, however it brought my rpi 3+ down to knee and had to do hard reboot.

**Comment by frenck** [comment]
This is a third party node, that is not shipped with the add-on and therefore out of scope.
Sorry mister, I hope you'll find a solution to your issue. Seems like you are on the right path.

**Comment by firestrife23** [comment]
Thank you, I'm thinking of moving entire docker containers over to more powerful machine such as NUC instead of raspberry pi.

**Comment by frenck** [comment]
From personal experience, I can definitely recommend that @firestrife23! 👍
