### ISSUE TITLE
can not install node-red-contrib-rfxcom

### ISSUE THREAD

**Issue by lpt2007** [hassio-addons/addon-node-red#9]
I installed python and install still not woring:

```
/root/.node-gyp/8.9.3/include/node/v8.h:9743:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^~~~~
../src/serialport.cpp: In function 'void EIO_AfterFlush(uv_work_t*)':
../src/serialport.cpp:516:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(2, argv);
                              ^
In file included from ../src/./serialport.h:7:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:528:29: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->ToInt32()->Int32Value();
                             ^
In file included from /root/.node-gyp/8.9.3/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/./serialport.h:7,
                 from ../src/serialport.cpp:1:
/root/.node-gyp/8.9.3/include/node/v8.h:9743:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^~~~~
../src/serialport.cpp: In function 'void EIO_AfterSet(uv_work_t*)':
../src/serialport.cpp:573:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:7:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:585:29: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->ToInt32()->Int32Value();
                             ^
In file included from /root/.node-gyp/8.9.3/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/./serialport.h:7,
                 from ../src/serialport.cpp:1:
/root/.node-gyp/8.9.3/include/node/v8.h:9743:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^~~~~
../src/serialport.cpp: In function 'void EIO_AfterDrain(uv_work_t*)':
../src/serialport.cpp:617:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:7:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
../src/serialport_unix.cpp:32:26: fatal error: linux/serial.h: No such file or directory
 #include <linux/serial.h>
                          ^
compilation terminated.
make: *** [serialport.target.mk:95: Release/obj.target/serialport/src/serialport_unix.o] Error 1
make: Leaving directory '/config/node-red/node_modules/serialport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.50
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/config/node-red/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/config/node-red/node_modules/serialport/build/Release"
gyp ERR! cwd /config/node-red/node_modules/serialport
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/config/node-red/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/config/node-red/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.4.50
node-pre-gyp ERR! command "/usr/bin/node" "/config/node-red/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /config/node-red/node_modules/serialport
node-pre-gyp ERR! node -v v8.9.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/config/node-red/node_modules/serialport/build/Release' (1)
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@4.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-25T15_00_31_177Z-debug.log
25 Jun 17:00:31 - [warn] ------------------------------------------
```

**Comment by lpt2007** [comment]
I figured out :)

How to solve problem on alpine linux:

apk add alpine-sdk
apk add python
apk add linux-headers

Now you can install node-red-contrib-rfxcom.

Problem solved:)

**Comment by frenck** [comment]
I'm glad you've figured it out!

![bitmoji](https://render.bitstrips.com/v2/cpanel/7218c89b-a039-4a96-bab6-67c159880d85-82100c49-8c0a-4ae4-9b04-3a6d3eac9cc2-v1.png?transparent=1&palette=1&width=246)
