### ISSUE TITLE
Unable to install node-red-contrib-i2c nodes

### ISSUE THREAD

**Issue by V4l3n10** [hassio-addons/addon-node-red#900]
# Problem/Motivation

**I'm not able to install node-red-contrib-i2c** 

## Expected behavior

Simply install pallet 

## Actual behavior

021-02-14T19:28:39.533Z Install : node-red-contrib-i2c 0.8.0

2021-02-14T19:28:40.301Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-i2c@0.8.0
2021-02-14T19:28:44.978Z [out] 
2021-02-14T19:28:44.978Z [out] > i2c-bus@5.2.1 install /config/node-red/node_modules/i2c-bus
2021-02-14T19:28:44.978Z [out] > node-gyp rebuild
2021-02-14T19:28:44.978Z [out] 
2021-02-14T19:28:46.867Z [err] gyp
2021-02-14T19:28:46.868Z [err]  ERR!
2021-02-14T19:28:46.869Z [err]  build error 
2021-02-14T19:28:46.870Z [err] gyp 
2021-02-14T19:28:46.871Z [err] ERR! stack Error: not found: make
2021-02-14T19:28:46.871Z [err] gyp
2021-02-14T19:28:46.871Z [err]  ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2021-02-14T19:28:46.871Z [err] gyp 
2021-02-14T19:28:46.871Z [err] ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2021-02-14T19:28:46.871Z [err] gyp ERR!
2021-02-14T19:28:46.872Z [err]  stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2021-02-14T19:28:46.872Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2021-02-14T19:28:46.872Z [err] gyp 
2021-02-14T19:28:46.872Z [err] ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2021-02-14T19:28:46.872Z [err] gyp ERR! stack
2021-02-14T19:28:46.872Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2021-02-14T19:28:46.872Z [err] gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
2021-02-14T19:28:46.873Z [err] gyp ERR! 
2021-02-14T19:28:46.873Z [err] System Linux 5.4.83-v7l
2021-02-14T19:28:46.873Z [err] gyp ERR! command
2021-02-14T19:28:46.874Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-02-14T19:28:46.874Z [err] gyp ERR! cwd /config/node-red/node_modules/i2c-bus
2021-02-14T19:28:46.874Z [err] gyp ERR! node -v v14.15.4
2021-02-14T19:28:46.874Z [err] gyp ERR! node-gyp -v v5.1.0
2021-02-14T19:28:46.874Z [err] gyp ERR!
2021-02-14T19:28:46.875Z [err]  not ok 
2021-02-14T19:28:47.162Z [err] npm 
2021-02-14T19:28:47.162Z [err] ERR! code ELIFECYCLE
2021-02-14T19:28:47.163Z [err] npm ERR! errno 1
2021-02-14T19:28:47.181Z [err] npm ERR!
2021-02-14T19:28:47.181Z [err]  i2c-bus@5.2.1 install: `node-gyp rebuild`
2021-02-14T19:28:47.181Z [err] npm ERR! Exit status 1
2021-02-14T19:28:47.181Z [err] npm 
2021-02-14T19:28:47.181Z [err] ERR! 
2021-02-14T19:28:47.181Z [err] npm ERR! Failed at the i2c-bus@5.2.1 install script.
2021-02-14T19:28:47.181Z [err] npm 
2021-02-14T19:28:47.182Z [err] ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-02-14T19:28:47.206Z [err] 
2021-02-14T19:28:47.207Z [err] npm ERR! A complete log of this run can be found in:
2021-02-14T19:28:47.207Z [err] npm ERR!     /root/.npm/_logs/2021-02-14T19_28_47_185Z-debug.log
2021-02-14T19:28:47.230Z rc=1

## Steps to reproduce

Manage Pallets > Install >  node-red-contrib-i2c > Install

## Proposed changes

Please advise. 
Thanks!

**Comment by frenck** [comment]
`2021-02-14T19:28:46.871Z [err] ERR! stack Error: not found: make`

You need to install the required packages (like `make`) using the `system_packages`

**Comment by V4l3n10** [comment]
Frenck, 

I very much appreciate your prompt reply.

Please provide a step by step guide on this as I am new to your world.
Or perhaps direct me to a step by step guide on how to. 

Many thanks!

**Comment by frenck** [comment]
You are installing third-party software, while I've put capabilities in place that one can install it... I cannot document all third-party cases, nor will I support them. You install these at your own risk.

**Comment by V4l3n10** [comment]
Thanks for your reply, 

I am a bit confused. 
Is there another node preinstalled that I can use to communicate to I2C in Node Red ?

**Comment by frenck** [comment]
Nope, there is no pre-defined node to communicate over I2C.

There are thousands of nodes available, it is impossible to include or support them all. Hence it comes with a common set. Please note, that this add-on is designed to work with Home Assistant. Home Assistant can work with I2C already.

**Comment by V4l3n10** [comment]
I understand.  
It is just very frustrating that I am somehow familiar with node red and have my own flows ready that I am trying to import in the node red addon in Home assistant where I encountered the difficulty of installing it. 

I have seen the previously solved/closed issues with regards to the same problem. However, not understanding what installing the "(like make) using the system_packages" means I decided to open another issue asking for a bit of details on this. 

I understand from what you are saying that it might be preferable to not install third party software's and redesign the flows using the communication options already available. 
Is this correct?

**Comment by frenck** [comment]
> I understand from what you are saying that it might be preferable to not install third party software and redesign the flows using the communication options already available.

I do not have an opinion on how one would solve that. That is a choice up to you. I'm just saying that the add-on comes with a tested common set. Additional can be installed, that is up to you.

**Comment by V4l3n10** [comment]
I am happy to try an install additional, my problem is that I don't know how and while I much appreciate your effort in replying with a solution "You need to install the required packages (like make) using the system_packages" I am helpless as this is above my knowledge. 

I understand from your previous posts that the answer is in the text such as "ERR! stack Error: **not found: make**"  but don't know where to start ie.:
 What is make? Where do I get it from? Where do I install it? How do I install it? 

Have you seen it work ? Or, do you know someone that could help?

**Comment by frenck** [comment]
Try adding `build-base` (which includes `makes`) to the `system_packages` and try again.

For reference see the dependencies of `build-base` here: <https://pkgs.alpinelinux.org/package/v3.13/main/x86_64/build-base>

**Comment by V4l3n10** [comment]
Frenck, 

Thanks again for your reply.
I don t know how to do this and I spent my night and this morning searching online but I don't get it. 
Please advise on how do I add to the system_packages ? 

Thanks

**Comment by frenck** [comment]
Its part of the add-on configuration screen. It is documented in the add-on documentation, including examples.

**Comment by V4l3n10** [comment]
![System_packages_node red addon config](https://user-images.githubusercontent.com/79058457/107977394-f201d400-6fb2-11eb-8ae4-a73a1fd82757.PNG)

Something like this?

**Comment by frenck** [comment]
yes

**Comment by V4l3n10** [comment]
I start it and stops, 

I got this Log:
Any Idea of what next? 

(17/17) Installing build-base (0.5-r2)
Executing busybox-1.32.1-r0.trigger
OK: 255 MiB in 63 packages
[cont-init.d] customizations.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1158 (offset 627 lines).
npm ERR! code EJSONPARSE
npm ERR! file /config/node-red/package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token p in JSON at position 145 while parsing near '...dependencies": {}
npm ERR! JSON.parse }
npm ERR! JSON.parse pkgname=build-base
npm ERR! JSON.parse p...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-15T17_30_58_557Z-debug.log
[17:30:58] FATAL: Failed un-installing conflicting packages
[cont-init.d] node-red.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by frenck** [comment]
Nope. Sorry.

**Comment by V4l3n10** [comment]
Frenck, 

I made a mistake the last time by editing foolishly the node file. I removed the edited part, dded the build-base to the system_packages and now I get this:  

Please advise !

021-02-15T20:19:00.769Z Install : node-red-contrib-i2c 0.8.0

2021-02-15T20:19:01.788Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-i2c@0.8.0
2021-02-15T20:19:10.794Z [out] 
2021-02-15T20:19:10.794Z [out] > i2c-bus@5.2.1 install /config/node-red/node_modules/i2c-bus
2021-02-15T20:19:10.794Z [out] > node-gyp rebuild
2021-02-15T20:19:10.794Z [out] 
2021-02-15T20:19:12.686Z [out] make: Entering directory '/config/node-red/node_modules/i2c-bus/build'
2021-02-15T20:19:12.689Z [out]   CXX(target) Release/obj.target/i2c/src/i2c.o
2021-02-15T20:19:13.217Z [err] In file included from ../src/i2c.cc:17:
2021-02-15T20:19:13.217Z [err] ../src/./i2c-dev.h:26:10: fatal error: linux/types.h: No such file or directory
2021-02-15T20:19:13.217Z [err]    26 | #include <linux/types.h>
2021-02-15T20:19:13.217Z [err]       |          ^~~~~~~~~~~~~~~
2021-02-15T20:19:13.217Z [err] compilation terminated.
2021-02-15T20:19:13.226Z [err] make: *** [i2c.target.mk:109: Release/obj.target/i2c/src/i2c.o] Error 1
2021-02-15T20:19:13.226Z [out] make: Leaving directory '/config/node-red/node_modules/i2c-bus/build'
2021-02-15T20:19:13.229Z [err] gyp
2021-02-15T20:19:13.230Z [err]  ERR! 
2021-02-15T20:19:13.230Z [err] build error 
2021-02-15T20:19:13.232Z [err] gyp 
2021-02-15T20:19:13.232Z [err] ERR! stack Error: `make` failed with exit code: 2
2021-02-15T20:19:13.232Z [err] gyp ERR! stack
2021-02-15T20:19:13.232Z [err]      at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
2021-02-15T20:19:13.232Z [err] gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
2021-02-15T20:19:13.232Z [err] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
2021-02-15T20:19:13.233Z [err] gyp ERR! 
2021-02-15T20:19:13.234Z [err] System Linux 5.4.83-v7l
2021-02-15T20:19:13.234Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-02-15T20:19:13.234Z [err] gyp ERR! cwd /config/node-red/node_modules/i2c-bus
2021-02-15T20:19:13.234Z [err] gyp ERR! node -v v14.15.4
2021-02-15T20:19:13.235Z [err] gyp ERR! node-gyp -v v5.1.0
2021-02-15T20:19:13.235Z [err] gyp 
2021-02-15T20:19:13.235Z [err] ERR! not ok 
2021-02-15T20:19:13.455Z [err] npm 
2021-02-15T20:19:13.455Z [err] ERR! code ELIFECYCLE
2021-02-15T20:19:13.455Z [err] npm
2021-02-15T20:19:13.455Z [err]  ERR! errno 1
2021-02-15T20:19:13.475Z [err] npm 
2021-02-15T20:19:13.475Z [err] ERR! i2c-bus@5.2.1 install: `node-gyp rebuild`
2021-02-15T20:19:13.475Z [err] npm ERR! Exit status 1
2021-02-15T20:19:13.475Z [err] npm 
2021-02-15T20:19:13.475Z [err] ERR! 
2021-02-15T20:19:13.475Z [err] npm ERR! Failed at the i2c-bus@5.2.1 install script.
2021-02-15T20:19:13.475Z [err] npm
2021-02-15T20:19:13.475Z [err]  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-02-15T20:19:13.494Z [err] 
2021-02-15T20:19:13.494Z [err] npm ERR! A complete log of this run can be found in:
2021-02-15T20:19:13.494Z [err] npm ERR!
2021-02-15T20:19:13.494Z [err]      /root/.npm/_logs/2021-02-15T20_19_13_479Z-debug.log
2021-02-15T20:19:13.514Z rc=1

**Comment by frenck** [comment]
> 2021-02-15T20:19:13.217Z [err] ../src/./i2c-dev.h:26:10: fatal error: linux/types.h: No such file or directory
> 2021-02-15T20:19:13.217Z [err] 26 | #include <linux/types.h>

You need linux headers: `linux-headers`

To be honest, If you really need this level of help with this, I would strongly recommend you to not use it at all.

**Comment by V4l3n10** [comment]
Frenck, 

Thanks again for your reply. 

We all start from somewhere and yes, I am really at the beginning of it but not going to discourage on it as I want it bad :) 
I managed to put together most of the project and want to integrate it in Home assistant via node red but encountered this issue which is clearly above my experience.

If you feel capable and kindly willing of helping me at your convenience that I would much appreciate. I am sure I will find a way to make up for it somehow. 

If this is to much to ask, please advise on where to look for help on this issue and perhaps on the upcoming ones. Perhaps someone you know that is willing to give me support on this?

Many thanks

**Comment by V4l3n10** [comment]
> > 2021-02-15T20:19:13.217Z [err] ../src/./i2c-dev.h:26:10: fatal error: linux/types.h: No such file or directory
> > 2021-02-15T20:19:13.217Z [err] 26 | #include <linux/types.h>
> 
> You need linux headers: `linux-headers`
> 
> To be honest, If you really need this level of help with this, I would strongly recommend you to not use it at all.


How do I include/add 'linux-headers'? 

Thanks

**Comment by bonanitech** [comment]
```yaml
system_packages:
  - build-base
  - linux-headers
```

**Comment by V4l3n10** [comment]
@bonanitech,

Many thanks! It worked :) 

After I imported a flow that I used before in Node Red I got an error while trying to get data from an I2C address. 

"Error: ENOENT: no such file or directory, open '/dev/i2c-1'"

![Capture](https://user-images.githubusercontent.com/79058457/108104851-b7b43780-7083-11eb-8d37-7942b2ededc8.PNG)

Any thoughts? 
Many thanks for all your help guys!
