### ISSUE TITLE
Start failes after minor update to addon and hassio os

### ISSUE THREAD

**Issue by heikkis** [hassio-addons/addon-node-red#911]
# Problem/Motivation

Failed to start after latest minor update for addon and hassio os.

## Actual behavior

```
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 8.1.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.11  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.2.3
 Home Assistant Supervisor: 2021.02.11
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
... 
[cont-init.d] node-red.sh: executing... 
[07:51:15] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[07:51:17] INFO: Password is NOT in the Have I Been Pwned database! Nice!
patching file nodes/ui_base.html
Hunk #1 succeeded at 1159 (offset 628 lines).
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'nopt'
Require stack:
- /usr/lib/node_modules/npm/lib/config/defaults.js
- /usr/lib/node_modules/npm/lib/config/core.js
- /usr/lib/node_modules/npm/lib/npm.js
- /usr/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/config/defaults.js:8:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/npm/lib/config/defaults.js',
    '/usr/lib/node_modules/npm/lib/config/core.js',
    '/usr/lib/node_modules/npm/lib/npm.js',
    '/usr/lib/node_modules/npm/bin/npm-cli.js'
  ]
}
[07:51:18] FATAL: Failed un-installing conflicting packages
[cont-init.d] node-red.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

```

**Comment by heikkis** [comment]
The system is working unstable so error might not be part of node-red.

**Comment by heikkis** [comment]
Restore of previous version of node-red removed the error. The system is not stable yet so still uncertainty which caused the problem.

**Comment by frenck** [comment]
`Error: Cannot find module 'nopt'`

This is caused by installing third-party nodes. Please make sure you add those via the add-on configuration, so the add-on can pick them up correctly at boot.

**Comment by heikkis** [comment]
My configuration file was like this:

```yaml
credential_secret: xxxxxxxx
dark_mode: false
http_node:
  username: node
  password: xxxxxxx
http_static:
  username: node
  password: xxxxx
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
require_ssl: true
system_packages: []
npm_packages: []
init_commands: []
```

Im not aware that I have any 3rd party modules installed. Is there easy way to identify the 3rd party which is causing it?

Starting log with 8.1.1:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 8.1.1
 There is an update available for this add-on!
 Latest add-on version: 8.1.2
 Please consider upgrading as soon as possible.
 System: Home Assistant OS 5.11  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.2.3
 Home Assistant Supervisor: 2021.02.11
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] customizations.sh: executing... 
[cont-init.d] customizations.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
[17:38:26] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[17:38:27] INFO: Password is NOT in the Have I Been Pwned database! Nice!
patching file nodes/ui_base.html
Hunk #1 succeeded at 1158 (offset 627 lines).
up to date in 0.767s
found 0 vulnerabilities
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:38:30] INFO: Starting Node-RED...
> addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
21 Feb 17:38:34 - [info] 
Welcome to Node-RED
===================
21 Feb 17:38:34 - [info] Node-RED version: v1.2.9
21 Feb 17:38:34 - [info] Node.js  version: v14.15.4
21 Feb 17:38:34 - [info] Linux 5.4.83-v8 arm64 LE
21 Feb 17:38:35 - [info] Loading palette nodes
21 Feb 17:38:39 - [info] Dashboard version 2.27.0 started at /endpoint/ui
/bin/sh: /opt/node_modules/node-red-node-pi-gpio/testgpio.py: not found
21 Feb 17:38:40 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
21 Feb 17:38:40 - [info] Settings file  : /etc/node-red/config.js
21 Feb 17:38:40 - [info] Context store  : 'default' [module=memory]
21 Feb 17:38:40 - [info] User directory : /config/node-red/
21 Feb 17:38:40 - [warn] Projects disabled : editorTheme.projects.enabled=false
21 Feb 17:38:40 - [info] Flows file     : /config/node-red/flows.json
21 Feb 17:38:40 - [info] Server now running at http://127.0.0.1:46836/
21 Feb 17:38:40 - [info] Starting flows
21 Feb 17:38:41 - [info] Started flows
[17:38:41] INFO: Starting NGinx...
21 Feb 17:38:45 - [info] [server:Home Assistant] Connecting to http://supervisor/core
21 Feb 17:38:45 - [info] [server:Home Assistant] Connected to http://supervisor/core
```

**Comment by frenck** [comment]
That startup is fine. 

> Error: Cannot find module 'nopt'

Is not part of this add-on, so I'm not able to tell you how it got into your system. I don't manage that system.

**Comment by heikkis** [comment]
It sounds strange because node-red is in a container, rebuild does not help and it's minor update back and forth with will cause the container log the error. I'm not aware any 3rd party modules installed inside node-red and my config is simple. But I will keep looking, need to disable auto update for now.

Thank you for you help.
