### ISSUE TITLE
Installing node_red-contrib-nefit-easy from the node-red  node-red wont’t come up again. 

### ISSUE THREAD

**Issue by tsien-bier** [hassio-addons/addon-node-red#94]
After installing node_red-contrib-nefit-easy from the node-red configuration nodes - install tab node-red wont’t come up again. The web-interfaces is unavailable. When i check the log i see te following:

```
11 Dec 20:52:32 - [info] Installing module: node-red-contrib-nefit-easy2, version: 1.3.0
11 Dec 20:52:54 - [info] Installed module: node-red-contrib-nefit-easy2
11 Dec 20:52:56 - [info] Added node types:
11 Dec 20:52:56 - [info] - node-red-contrib-nefit-easy2:nefit-easy
11 Dec 20:52:56 - [info] - node-red-contrib-nefit-easy2:nefit-easy-config
11 Dec 20:52:56 - [red] Uncaught Exception:
11 Dec 20:52:56 - TypeError: tls.convertNPNProtocols is not a function
at new TLSSocket (_tls_wrap.js:269:9)
at Server. (_tls_wrap.js:852:18)
at emitOne (events.js:116:13)
at Server.emit (events.js:211:7)
at TCP.onconnection (net.js:1570:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio-addon-node-red@ start: node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hassio-addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2018-12-11T19_52_56_108Z-debug.log

hassio-addon-node-red@ start /opt
node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
11 Dec 20:53:02 - [info]
```
What is wrong here? I used the component before. Then there was no problem en could use the installed components and connect to my Nefit Easy.

I did test the installation on a on Ubuntu 18.4 node-red installation. The component is installing good and is working.

**Comment by frenck** [comment]
Seems like it is missing some libraries that the node needs?
Not sure. I cannot support all nodes out there, that would be impossible.
I'm sorry to say, but in this case, you are on your own.
Maybe somebody in the community is able to help?
